### ISSUE TITLE
Raiden Network - Due diligence

### ISSUE THREAD

**Issue by hterrence** [ico-check/ico-check#1]
Company's website: https://raiden.network/

**Comment by icochecker** [comment]
## Company
[Brainbot Labs Establishment](https://brainbot.li/)            
Lettstrasse 12                
FL-9490 Vaduz              
Liechtenstein             
            
**Incorporated on:** 13 September 2017        
**Authorized to sign documents:** Florian Tobias Glatz (Maybe related to: [http://blockchain.lawyer/](http://blockchain.lawyer/))

#### Addtional company info for Brainbot Labs Establishment: 
- [http://www.firmensuche.li/htm/647/de/Firmendaten-Brainbot-Labs-Establishment.htm?subj=2586276](http://www.firmensuche.li/htm/647/de/Firmendaten-Brainbot-Labs-Establishment.htm?subj=2586276)

- [Brainbot Technologies AG](http://www.brainbot.com/) is maybe connected to [Brainbot Labs Establishment](https://brainbot.li/).           

- [Heiko Hees](https://www.linkedin.com/in/heikohees) - Founder & CEO of Brainbot Technologies AG   

## Vesting
No information about vesting schedule

**Devs claim:**
> They didn’t grant the developers any free tokens, but instead let them only participate in the overall success of the company and have set a 4 year(!) cliff.

**Source:** [https://www.reddit.com/r/ethtrader/comments/7676wj/misconceptions_about_raiden/](https://www.reddit.com/r/ethtrader/comments/7676wj/misconceptions_about_raiden/)
