### ISSUE TITLE
Crypterium - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#10]
# [Crypterium](https://crypterium.io/) (CRPT)

## Team
- Gleb Markov (COO, Co-founder) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/gdmarkov/)
- Steven Polyak (Managing Director, Co-founder) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/steven-polyak-4443872/)
- Vladimir Gorbunov (CCO, Co-founder) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/gorbunov-v/)
- Austin Kimm (Financial Director, Co-founder) - May 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/austin-kimm-486b5a22/)
- Pavel Rasputin (CMO) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/pavelrasputin/)
- Dimitriy Fomin (CTO, Head of Security & QA) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/dmitriy-fomin-95238446/)
- Ilya Churakov (Video Producer) | [Linkedin profile](https://www.linkedin.com/in/ilya-churakov-b36116b/) **does not mention Crypterium**
- Simon Sergeev (Head of Support & Communications) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/comm/in/simon-sergeev-93781028)
- George Ermakov (Strategy Development Manager) | **No Linkedin profile**
- Igor Tszyan-Nyn-Tsay (Head of Law & Regulation) - Sep 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/igor-tszyan-nyn-tsay-9b661025/) **does not mention Crypterium**
- Ruff Rubaker (Аrt Director) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/rubakerruff/)
- Ivan Vasiliev (Senior R&D Engineer) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/ivan-vasiliev-22688314a/)
- Igor Semenchenko (Lead Mathematician, Senior Architect Developer) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/igor-semenchenko-28b8a214a/)

### Advisors
- Keith Teare | [Linkedin profile](https://www.linkedin.com/in/kteare)
- Elie Galem | [Linkedin profile](https://www.linkedin.com/in/elie-galam-85414b3)
- Katrina Arden | [Linkedin profile](https://www.linkedin.com/in/katrina-arden-70260426)
- Fabio Tamburrano | [Linkedin profile](https://www.linkedin.com/in/fabio-tamburrano-45b8a216)
- Roger Crook | [Linkedin profile](https://www.linkedin.com/in/rogercrook)
- Andras Kristof | [Linkedin profile](https://www.linkedin.com/in/andraskristof)
- Vladimir Kapustin | [Linkedin profile](https://www.linkedin.com/in/vladimir-kapustin-993726150/)
- Hazem Danny Al Nakib | [Linkedin profile](https://www.linkedin.com/in/hdnakib/)
- Mike Raitsyn | [Linkedin profile](https://www.linkedin.com/in/mike-raitsyn-05b5b9b4)
- Gabriel Zanko | [Linkedin profile](https://co.linkedin.com/in/gabrielzanko)

## Company
[Crypterium R&D OU](https://crypterium.io/)            
Parnu mnt 141             
pk 59            
11314 Tallinn               
Estonia         
**Registry code:** 14352837                        

- [Estonia company registry](https://ariregister.rik.ee/index?lang=eng)

![company](https://user-images.githubusercontent.com/32852887/33223871-3ee1aaac-d164-11e7-92a0-4bfd68455052.png)

## Smart contract
- [Deployed - View on etherscan](https://etherscan.io/address/0x80a7e048f37a50500351c204cb407766fa3bae7f#code)
- **Vesting schedule not coded in the deployed smart contract**

![vesting-not-in-smartcontract](https://user-images.githubusercontent.com/32852887/33224036-8969bcd0-d165-11e7-9c1f-714405003fd4.png)

![crypterium-not-in-smartcontract](https://user-images.githubusercontent.com/32852887/33224770-51cb56c8-d16d-11e7-8144-1d008346770e.png)

## Github
- No Github

![no-github](https://user-images.githubusercontent.com/32852887/33224041-9d83e7ae-d165-11e7-9ad6-694b2cea1540.png)

## Product
- No working product to test
- [Video of product](https://www.youtube.com/watch?v=-Q3ILm8of6Y)

![crypterium-chat-3](https://user-images.githubusercontent.com/32852887/33223938-fefdf778-d164-11e7-8a4a-ea03290c10a1.png)

## Vesting
- No information regarding vesting schedules on the white paper or web site. Got info from telegram chat and Crypterium medium post.
- 9% of tokens for founders and management with a 10 month vesting schedule
- 15% of tokens for reserved fund with a 15 month vesting schedule
- [Source on medium](https://medium.com/@crypterium_io/crypterium-faq-2c3d0d1167a9)

![crypterium-support-4](https://user-images.githubusercontent.com/32852887/33224018-63f5ded4-d165-11e7-9229-ec948025409e.png)

**Comment by MrNicodemuz** [comment]
@icochecker possible to add info about team members?

**Comment by icochecker** [comment]
@MrNicodemuz will do 🙂

**Comment by icochecker** [comment]
@MrNicodemuz Team info added 🙂

**Comment by emreboy** [comment]
I don't see how this project has multiple red flags?

**Comment by MrNicodemuz** [comment]
@icochecker I think the "No working product" label does not apply anymore:
https://play.google.com/store/apps/details?id=com.crypterium&hl=en
https://itunes.apple.com/us/app/crypterium-cryptofinance/id1360632912?mt=8

**Comment by icochecker** [comment]
@emreboy Red flags: 
- Short vesting schedule for Team tokens (10 Month). 
- Vesting schedule not coded in the smart contract.
- No product during the ICO
- Not Github during the ICO

@MrNicodemuz Labels are for the ICO period. I will add labels and comments for the Post-ICO period
