### ISSUE TITLE
Akasha - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#104]
# [Akasha](https://akasha.world/) (AETH)

## Team
- Mihai Alisie (Founder) - Oct 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/mihaialisie/) | [Twitter](https://twitter.com/mihaialisie) | [Github](https://github.com/MihaiAlisie)
- Roxana Sureanu (CAO) - Oct 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/roxana-adriana-sureanu-13a6b791/)
- Marius Darila (CTO) - Oct 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/marius-darila-8706506a/) | [Github](https://github.com/kenshyx)
- Sever Abibula (Software Developer) - May 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/severabibula/) | [Github](https://github.com/SeverS)
- Bogdan Brezuica (Software Developer) - Oct 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/bogdan-brezuica-98b57682/)
- Sebastian Kleinkauf (Community Caretaker)
- Lorenzo Patuzzo (Creative Consultant) | [Twitter](twitter.com/lorenzopatuzzo)
- Mariana Gomes (UI Consultant)
- Bogdan Pavel (UX Consultant)
- Vali Cotea (Software Developer)
- Jarred Chase Cole | [Keybase](https://keybase.io/jchasecole) | [Github](https://github.com/ChaceHunter)

### Advisors
- Vitalik Buterin | [Linkedin profile](https://ca.linkedin.com/in/vitalik-buterin-267a7450) | [Twitter](https://twitter.com/VitalikButerin)
- Juan Benet | [Linkedin profile](https://www.linkedin.com/in/jbenetcs)

# Company
## AKASHA International GmbH
**Address:**     
Gotthardstrasse 14    
6300 Zug       
Switzerland     
**Registered on:** 23 July 2015     
**UID:** CHE-269.291.541   
**Commercial register number:** CH-170.4.013.462-7    
**Legal Form:** 	Limited liability company  

### Management
- **Mihai-Valeriu Alisie** | Managing director | **Since:** 28 July 2015
- **AKASHA Stiftung** | Partner | **Since:** 5 March 2018

#### Source
- [Kanton Zug commercial register](https://zg.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-269.291.541)

## AKASHA Stiftung (Foundation)
**Address:**     
Gotthardstrasse 14    
6300 Zug       
Switzerland      
**Registered on:** 14 December 2017     
**UID:** CHE-189.356.574   
**Commercial register number:** CH-170.7.000.840-8 

### Management
- **Herbert Sterchi** | Foundation board-President | **Since:** 19 December 2017
- **Marius-Ionut Darila** | Foundation board-President | **Since:** 19 December 2017
- **Mihai-Valeriu Alisie** | Foundation board-President | **Since:** 19 December 2017

#### Source
- [Kanton Zug commercial register](https://zg.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-189.356.574)

## Smart contract
N/A

## Github
- [AkashaProject](https://github.com/AkashaProject)

## Product
- The alpha version is already available for Linux, MacOS, and Windows and currently runs on a private Ethereum testnet. The main Ethereum network launch (AKASHA 1.0) is expected to happen around Q3/Q4 2018.

- [Dashboard](https://akasha.network/#/dashboard)
- [Beta download](https://github.com/AkashaProject/dapp/releases/tag/0.6.2)
- [Beta instructions](https://blog.akasha.world/2018/02/10/akasha-beta-emergence/)

### Roadmap
![akasha-roadmap](https://user-images.githubusercontent.com/32852887/38527701-66e589ca-3c5c-11e8-9fd2-2b02de607165.png)

#### N/A

# Q&A
![akasha-qa1](https://user-images.githubusercontent.com/32852887/38527709-70f526dc-3c5c-11e8-8c09-57b8c610de38.png)
![akasha-qa2](https://user-images.githubusercontent.com/32852887/38527710-72aa4890-3c5c-11e8-9672-a88c272e37a8.png)

# Flags
**Real Team:** ✅      
**GitHub:** ✅          
**Smart Contract:** - N/A    
**Working Product:** - Beta available      
**+2 yr Vesting for team:** - N/A yet     
**Have a company:** ✅                 
**Transparent:** -          

# IcoCheck
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by icoDD** [comment]
No ICO for this project I don't think
