### ISSUE TITLE
Orchid Protocol - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#106]
# [Orchid Protocol](https://orchidprotocol.com/) (OCT)

## Team
- Stephen Francis Bell (Co-founder) - Mar 2017 - Jan 2018 | [Linkedin profile](https://www.linkedin.com/in/stevebell)
- Steven Richard Waterhouse (Co-founder & CEO) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/waterhousephd/) | [Email](mailto:stevew@meshlabs.org)
- Brian J. Fox (Co-founder) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/brianjhanfox/)
- Jay Freeman (Co-founder) | [Linkedin profile](https://www.linkedin.com/in/saurik/) | [Github](https://github.com/saurik)
- Gustav Simonsson (Co-founder) | [Github](https://github.com/Gustav-Simonsson)
- Jackie Peters (Lead UX Designer) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/jackiepeters/)
- Alexander Kehaya (Business Development) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/afkehaya/)
- Louise Conroy-Callagy (Interim CMO) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/louisecallagy/)
- David Salamon (Researcher) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/david-salamon-b77a693/)
- Lauryn Guridi (Chief of Staff) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/lauryng/)
- Marit Davey (Investor Relations) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/maritdavey)
- Brian Vohaska | [Linkedin](https://www.linkedin.com/in/brian-vohaska-02618b130/)

### Advisors
- Paul Veradittakit | [Linkedin profile](https://www.linkedin.com/in/veradittakit/)
- Chance Barnett | [Linkedin profile](https://www.linkedin.com/in/chancebarnett/)

### Investor
- Faizan J. Khan | [Linkedin profile](https://www.linkedin.com/in/faizanjkhan/)
- Adam B. Struck | [Linkedin profile](https://www.linkedin.com/in/adam-b-struck-19361249/)

# Funding Rounds

![orchid-formd](https://user-images.githubusercontent.com/32852887/39088920-630c5f28-45bb-11e8-81e7-946cdba77f74.png)

### Federal Exemption and Exclusion Claimed:
**Rule 506(c)**

### Offering and Sales Amounts:
- Total Offering Amount $125,595,882 USD
- Total Amount Sold	$36,128,073 USD
- Total Remaining to be Sold $89,467,809 USD

### Federal Exemption and Exclusion Claimed:
**Rule 506(b)**

### Offering and Sales Amounts:
- Total Offering Amount	 $4,500,000 USD	
- Total Amount Sold	$4,500,000 USD
- Total Remaining to be Sold $0 USD

### [Source: SEC Form D - 8 November 2017](https://www.sec.gov/Archives/edgar/data/1721086/000172108617000001/xslFormDX01/primary_doc.xml)

# Company 
## Orchid Labs Inc
**Previous Names:** Mesh Network Lab Inc.    
**File Number:** 6476833       
**Incorporation Date / Formation Date:** 13 July 2017       
**Entity Kind:** Corporation           
**Entity Type:** General          
**Residency:** Domestic         
**State:** Delaware    

**Office address:**
182 Howard Street #423       
San Francisco       
California 94105     

**Phone:** 512-903-1269    

**Registered Agent Information:**     
COGENCY GLOBAL INC.    
850 New Burton Road, Suite 201     
Dover          
Kent County        
Delaware 19904     
USA      

#### Management
- **Stephen Francis Bell** | Director, Executive Officer
- **Steven Richard Waterhouse** | Director, Executive Officer
- **Brian J. Fox** | Director
- **Jay Freeman** | Director
- **Gustav Simonsson** | Director
      

### [Delaware entity search](https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx)

![orchid-delaware](https://user-images.githubusercontent.com/32852887/38671122-d2d4734a-3e4a-11e8-89a1-c97293dcb7a4.png)

## Smart contract
N/A

# Github
- [Orchid Labs](https://github.com/orchidsource)

### Other repo
- [Orchid Lib](https://github.com/Gustav-Simonsson/orchid-lib)

## Product
N/A

## Vesting
N/A

### Token distribution
N/A

### Token allocation
N/A

# Flags
**Real Team:** ✅      
**GitHub:** ✅           
**Smart Contract:** -        
**Working Product:** ❌       
**+2 yr Vesting for team:** -     
**Have a company:** ✅                 
**Transparent:** -          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by coinbala** [comment]
The private presale round TOKEN price was 0.03$ USD and the private sale 0.70$

**Comment by goktugyil** [comment]
@coinbala do you have source for that?

**Comment by goktugyil** [comment]
Wow.. Thanks.

Do you know whats the minimum entry price for SAFTs? And are you guys purchasing it?

**Comment by sjcnova** [comment]
This information is not correct.

**Comment by sjcnova** [comment]
Team information is not correct. Updated information below.
**Louise Conroy-Callagy (Interim CMO) - Aug 2017 - March 2018 | Linkedin profile**
David Salamon (Researcher) - Aug 2017 - Present | Linkedin profile
**Lauryn Guridi (Chief of Staff) - Aug 2017 - Oct 2018 | Linkedin profile**
**Marit Davey (Investor Relations) - Aug 2017 - Sept 2018 | Linkedin profile**
Brian Vohaska | Linkedin

**Comment by sjcnova** [comment]
Deleware Entity Search - Office Address NOT correct. 
Incorrect address -
Office address:
182 Howard Street #423
San Francisco
California 94105

CORRECT ADDRESS
Orchid Labs, Inc. 1288 Columbus Ave. #122, San Francisco, CA 94133

**Comment by sjcnova** [comment]
NOT Correct -

The private presale round TOKEN price was 0.03$ USD and the private sale 0.70$
--
Orchid never had a token sale. Please remove.
