### ISSUE TITLE
Akash Network - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#107]
# [Akash Network](https://akash.network/)

[![telegram-chat](https://user-images.githubusercontent.com/32852887/38760208-611df88a-3f7a-11e8-83bc-ca7ba4076a10.png)](https://t.me/AkashNW)

# Team

![akash-team-new](https://user-images.githubusercontent.com/32852887/39894777-425206b0-54a8-11e8-8704-2f594cf69f54.png)

### Greg Osuri (Founder & CEO) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/gosuri) | [Twitter](https://twitter.com/gregosuri) | [Github](https://github.com/gosuri) | [Personal site](http://gregosuri.com) | [Facebook](https://www.facebook.com/osuri)      
 - [Overlock Labs](https://www.ovrclk.com/) | Founder & CEO - Jun 2015 - Present
 - [Angel Hack](http://www.angelhack.com/) | Founder & CTO - Nov 2011 - Jul 2013
 - [Marketron](http://www.marketron.com) | Lead Architect - Nov 2011 - Jan 2013

### Adam Bozanich (Co-founder & CTO) | [Linkedin profile](https://www.linkedin.com/in/abozanich)  | [Github](https://github.com/boz)
 - [Overlock Labs](https://www.ovrclk.com/) | Co-founder & CTO - Jan 2016 - Present
 - [Sprouts Tech](https://web.archive.org/web/20160601033843/http://www.sproutstech.com) | Co-founder & Tech Lead - Jan 2014 - Mar 2016

### Aaron Stein (Software Engineer) | [Linkedin profile](https://www.linkedin.com/in/aastein1) | [Github](https://github.com/aastein)
 - [Overlock Labs](https://www.ovrclk.com/) | Software Engineer - Sept 2017 - Present
 - [Navar](https://corp.narvar.com/) | Software Engineer - Aug 2016 -  Sept 2017

### Nick Alesandro (VP of Product) | [Linkedin profile](https://www.linkedin.com/in/nalesandro/) | [Github](https://github.com/nalesandro)
 - [Overlock Labs](https://www.ovrclk.com/) | Software Engineer - Jan 2018 - Present
 - [Timshel](https://timshel.com) | Software Engineer - Dec 2015 - Dec 2017

### Allison Silber (Head of Operations) | [Linkedin profile](https://www.linkedin.com/in/allison-silber-81804340/) | [AboutMe](https://about.me/allisonsilber) | [Twitter](https://twitter.com/allisonsilber)
 - [Overlock Labs](https://www.ovrclk.com/) | Head of Operations - Oct 2017 - Present
 - [Engaged & Inspired](http://www.engagedandinspired.com/) | Founder, Creative Director & Lead Planner - Jun 2010 - Present

## Advisors & Investors

![akash-advisor](https://user-images.githubusercontent.com/32852887/38759075-554d93d6-3f74-11e8-91db-0d0f77dd1bd4.png)

- CrunchFund | [Website](https://cf.vc/)
- Hone | [Website](http://honecap.com/)
- Auren Hoffman | [Linkedin profile](https://www.linkedin.com/in/auren)
- Steven Fan | [Linkedin profile](https://www.linkedin.com/in/stevenweifan)
- Charles Songhurst | [Linkedin profile](https://www.linkedin.com/in/charlessonghurst/)
- Jaron Lukasiewicz | [Linkedin profile](https://www.linkedin.com/in/jaronlukasiewicz)
- Brandon Goldman | [Linkedin profile](https://www.linkedin.com/in/bgoldman)
- Lee Linden | [Linkedin profile](https://www.linkedin.com/in/lclinden)

# OFAC Check ✅
![akash-network-ofac](https://user-images.githubusercontent.com/32852887/39897508-d0183672-54b2-11e8-895f-fae41fc6b1dd.png)

### [Source: OFAC Search Tool](https://ofac.finra.org)

# Funding Rounds

![overlock-formd](https://user-images.githubusercontent.com/32852887/39896682-73b66a1e-54af-11e8-945d-adda4cb8a918.png)

### Federal Exemption and Exclusion Claimed:
**Rule 506(c)**

Under Rule 506(c), a company can broadly solicit and generally advertise the offering and still be deemed to be in compliance with the exemption’s requirements if:

>The investors in the offering are all accredited investors; and

>The company takes reasonable steps to verify that the investors are accredited investors, which could include reviewing documentation, such as W-2s, tax returns, bank and brokerage statements, credit reports and the like.

### Offering and Sales Amounts:
- Total Offering Amount	 $34,000,000 USD	
- Total Amount Sold	$0 USD
- Total Remaining to be Sold $34,000,000 USD

### Federal Exemption and Exclusion Claimed:
**Rule 506(b)**

>**The company cannot use general solicitation or advertising to market the securities.**

>The company may sell its securities to an **unlimited number of "accredited investors" and up to 35 other purchasers**. All non-accredited investors, either alone or with a purchaser representative, **must be sophisticated—that is**, they must have sufficient knowledge and experience in financial and business matters to make them capable of evaluating the merits and risks of the prospective investment.

>Companies must decide what information to give to accredited investors, so long as it does not violate the antifraud prohibitions of the federal securities laws. This means that any information a company provides to investors must be free from false or misleading statements.  Similarly, a company should not exclude any information if the omission makes what is provided to investors false or misleading.  Companies must give non-accredited investors disclosure documents that are generally the same as those used in Regulation A or registered offerings, including financial statements, which in some cases may need to be certified or audited by an accountant.  If a company provides information to accredited investors, it must make this information available to non-accredited investors as well.
The company must be available to answer questions by prospective purchasers.

### Offering and Sales Amounts:
- Total Offering Amount	 $5,000,000 USD	
- Total Amount Sold	$1,269,127 USD
- Total Remaining to be Sold $3,730,873 USD

### [Source: SEC Form D - April 13th 2018](https://www.sec.gov/Archives/edgar/data/1734871/000173487118000002/xslFormDX01/primary_doc.xml)

# Company
## Overclock Labs, Inc.
**File Number:** 5765292         
**Incorporation Date / Formation Date:** 12 June 2015        
**Entity Kind:** Corporation           
**Entity Type:** General          
**Residency:** Domestic         
**State:** Delaware     

**Office Address:**     
530 Brannan Street, Suite 404  
San Francisco   
CA 94107   
USA   
        
**Registered Agent Information:**        
INCORPORATING SERVICES, LTD.         
3500 S DUPONT HWY           
Dover         
Kent County       
Delaware 19901    
USA        

#### Directors
- **Gangadharam Osuri** | Director, Executive
- **Adam Bozanich** | Director, Executive

### [Source: Delaware entity search](https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx)

![akash-delaware](https://user-images.githubusercontent.com/32852887/38647837-900ffd88-3dee-11e8-91c1-0b15fe497c64.png)

# Trademark
**Word Mark:**	AKASH NETWORK     
**Goods and Services:** IC 042. US 100 101. G & S: Decentralized blockchain-based auction marketplace for buying, selling, and deploying cloud infrastructure; Providing on-line software tools for deploying, configuring and managing computing workloads, storage systems, and network configuration in any cloud computing system   

**Mark Drawing Code:**	(4) STANDARD CHARACTER MARK     
**Serial Number:** 87832063   
**Filing Date:**	 March 13, 2018   

**Correspondent:**	
[Grace Neibaron](https://hoban.law/Grace-Neibaron)       
Hoban Law Group          
235 Foss Creek Circle      
Healdsburg, CA 95448       

![akash-trademark](https://user-images.githubusercontent.com/32852887/38771202-1cff86f0-401f-11e8-8a0b-705491140bcc.png)

### [Source: USPTO](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4807:e8uiuo.2.1)

# Smart contract
### N/A

# Github
- [Ovrclk](https://github.com/ovrclk)

![akash-github](https://user-images.githubusercontent.com/32852887/38647900-e989c592-3dee-11e8-972c-c865784f3e3b.png)

### Commits
- [Akash commits](https://github.com/ovrclk/akash/graphs/commit-activity) 

![akash-commit](https://user-images.githubusercontent.com/32852887/38647918-0319e726-3def-11e8-96de-c4081f32cb11.png)

# Product
### Prototype
- [Akash](https://github.com/ovrclk/akash/#running)

# Vesting
- Team tokens vest over 2 years with a 1 year cliff.
- Advisors tokens vest over 12 months with a 6 months cliff.

### Codify vesting on the native blockchain. To check once the network is live.

# Additional info
- [Photon](https://photonnetwork.org/) rebranded to [Akash](https://akash.network/)

### Team is working toward filing a Form D for exemption under Regulation D’s rule 506(c).

>**Under Rule 506(c), a company can broadly solicit and generally advertise the offering and still be deemed to be in compliance with the exemption’s requirements if:**    

- The investors in the offering are all accredited investors; and
- The company takes reasonable steps to verify that the investors are accredited investors, which could include reviewing documentation, such as W-2s, tax returns, bank and brokerage statements, credit reports and the like.

### Hard cap changed from $34MM to $20MM

![akash-network-terms-1](https://user-images.githubusercontent.com/32852887/41487867-9f33789c-70ea-11e8-921c-8152e19e0ef0.png)
![akash-network-terms-2](https://user-images.githubusercontent.com/32852887/41487868-a13c394e-70ea-11e8-92e9-6da29e737805.png)

### Token distribution
![akash-network-terms-distribution](https://user-images.githubusercontent.com/32852887/41487879-b0630a88-70ea-11e8-8406-a387d9004f5d.png)

### Token allocation
N/A

# Q&A
>**1. Where is your company registered? Could i have a copy of certificate of incorporation, list of directors and details of registered office address?**            
The company is Overclock Labs, a Delaware corporation. You can see a bit here [https://www.crunchbase.com/organization/ovrclk](https://www.crunchbase.com/organization/ovrclk) Our SEC Form D is at [https://www.sec.gov/Archives/edgar/data/1734871/000173487118000002/xslFormDX01/primary _doc.xml](https://www.sec.gov/Archives/edgar/data/1734871/000173487118000002/xslFormDX01/primary_doc.xml). If you want the actual certificate of incorporation I can dig that up.

>**2. Can i have details of any intellectual property which the company has created, registered or applied to register?**      
We’ve not yet registered any patents but plan to.

>**3. Can you share your Cap Table?**       
After a deeper discussion, yes.

>**4. What is the vesting schedule for Team and Advisors token? (% and how long vested)**          
Founders, employees, and early investors will vest over 24 months with a 1 year lockup; Advisors will vest over 12 months with 6 months lockup. Token terms available at https://akash.network/terms.pdf

>**5. Is vesting for Team and Advisors coded in the smart contract?**              
No it is not (no smart contracts per se).

>**6. Is your smart contract deployed for the ICO?**           
We use the tendermint framework and define blockchain operations in the Go programming language, so no smart contracts per se. These operations are included in our open source project here.

>**7. Was your smart contract audited by an independent cybersecurity company?**          
Moot, see above

>**8. Could I have a link to your github repo?**       
[https://github.com/ovrclk/akash/](https://github.com/ovrclk/akash/)

>**9. Do you have a working product available to test?**      
There is a working prototype marketplace available at [https://github.com/ovrclk/akash/#running](https://github.com/ovrclk/akash/#running) . You will see in there that the datacenters are stubbed out. This is because it is not yet a working product that can be installed at a datacenter. We are working on that now!

>**10. Has the code for your product been published, and has is it been audited by an independent cybersecurity company?**      
It is open source so yes it has been published, but no, not yet audited (though we’d welcome it!)
      
>**11. Are you using a reputable 3rd party for KYC verification? How safe is it to upload my Identity Document on your site?**     
We are using Shufti as our third party KYC service. We’ve developed against their APIs and hope to roll it out during the week of 9-April. Akash doesn’t view or store ID docs - they are passed directly to Shufti in an iframe. Shufti encrypts all data in transit and at rest and are fully PCI/GDPR compliant, with servers residing in EU.

>**12. Can us investors participate in the sale? If yes did you secure Reg-D?**      
Yes you can and yes we have filed for 506(b). We plan to file for 506(c) soon.

>**13. Where is my money going and what will it be used for? Is my money going to be used to "cash out" others?**        
The funds will be used for development, maintenance and distribution of Akash Network over the course of next five years. There are no “cash out” events.

>**14. What specific rights come with my investment?**       
Full refund upon dissolution and/or termination (Please see SAFT agreement)

>**15. Are there financial statements? If so, are they audited, and by whom?**       
Yes. Unaudited. Data Room is available after a deeper discussion

>**16. How, when, and at what cost can I sell my investment? For example, do I have a right to give the token or coin back to the company or to receive a refund? Can I resell the coin or token, and if so, are there any limitations on my ability to resell?**      
The crowd sale price is set at $0.14 currently. You can resell the token after 6 months of issuance. You do not have the “right” to give the coin back but the company is planning on hosting an exchange for provide early liquidity. There are no limitations on your ability to resell.

>**17. If a digital wallet is involved, what happens if I lose the key? Will I still have access to my investment?**     
We are selling SAFTs right now. When it is converted to a token, we assume that if you lose access to your wallet, you will lose access to your investment.

>**18. Has the offering been structured to comply with the securities laws and, if not, what implications will that have for the stability of the enterprise and the value of my investment?**     
We’re structured to comply with ever-evolving US Securities laws (see reg D answer above)

>**19. What legal protections may or may not be available in the event of fraud, a hack, malware, or a downturn in business prospects? Who will be responsible for refunding my investment if something goes wrong?**       
If the company fails to launch the network by December 31st, 2020, the company is contractually obliged to repay the purchaser the discount purchase amount.

>**20. If I do have legal rights, can I effectively enforce them and will there be adequate funds to compensate me if my rights are violated?**         
Yes

# Flags
**Real Team:** ✅      
**GitHub:** ✅          
**Smart Contract:** - N/A | New blockchain      
**Working Product:** - Prototype. Mainnet before or during Public sale.      
**+2 yr Vesting for team:** - Team tokens vest over 2 years with a 1 year cliff. Advisors tokens vest over 12 months with a 6 months cliff. Codify vesting on the native blockchain. To check once the network is live.  
**Have a company:** ✅                 
**Transparent:** ✅        

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)
- Follow us on [Twitter](https://twitter.com/icocheckio)

**Comment by nalesandro** [comment]
Hi all, I'd like to request a couple changes to this review:
1) Please remove Greg Gopman, he is no longer active with the team
2) We have now filed our 506(c) exemption https://www.sec.gov/Archives/edgar/data/1734871/000173487118000003/xslFormDX01/primary_doc.xml
3) In case you want to add some additional detail to the codified vesting language, I probably answered that question too quickly when originally asked - assumed you meant specifically an ERC-20 contract.  We will have tokens released programmatically, just on our own native chain (not ERC-20)

**Comment by icochecker** [comment]
@nalesandro issue updated

**Comment by nalesandro** [comment]
Thanks!  Could I get you to update the main page text as well?  ❤️❤️❤️

**Comment by icochecker** [comment]
@nalesandro comments updated on the main page 🙂

**Comment by nalesandro** [comment]
Hi there, we updated our terms to lower our hard cap, token price, and discount schedule.  You can get the latest here https://akash.network/terms.pdf/

Could I get you to update the review and main page appropriately?

Many thanks
Nick

**Comment by icochecker** [comment]
@nalesandro issue and main page comment updated
