### ISSUE TITLE
Menlo One - Due diligence

### ISSUE THREAD

**Issue by icoDD** [ico-check/ico-check#108]
# [Menlo One](https://menlo.one/)

## Core Team

- Matthew Nolan (CEO / Engineering) | [Linkedin profile](https://www.linkedin.com/in/buildbuildbuild/) | [Twitter](https://twitter.com/ImMatthewNolan)
- Anthony Martin (CTO) | [Linkedin profile](https://www.linkedin.com/in/admartin/)
- Scott Kraft (CMO) | [Linkedin profile](https://www.linkedin.com/in/scottmkraft)
- Marcie Grambeau (Marketing) | [Linkedin profile](https://www.linkedin.com/in/marcie-grambeau-664179146/)
- Rick Bross (Engineering) | [Linkedin profile](http://linkedin.com/in/rickbross3)
- Brandon Carlson (Engineering) | [Linkedin profile](https://www.linkedin.com/in/bcarl314/)
- Felix Watkins (Engineering) | [GitHub](https://github.com/OperationNine) 
- Nathan Windsor (Community) | [Linkedin profile](https://www.linkedin.com/in/iamnathanwindsor/) 
- Rick Dudley (Blockchain Architect) | [GitHub](https://github.com/AFDudley) 

### Advisors

- Richard Titus (Business) | [Linkedin profile](https://www.linkedin.com/in/rxdxt/) 
- Jill Richmond (Marketing) | [Linkedin profile](https://www.linkedin.com/in/jillrichmond/) 
- Markus Ament (Marketing) | [Linkedin profile](https://www.linkedin.com/in/ament/) 
- Marissa Kim (Legal) 
- Elissa Shevinsky (Product) 
- Mike Hostetler (Engineering) 

## Company
Menlo.one Inc.

![menlocorp](https://user-images.githubusercontent.com/38394062/38775996-6cf3a87c-4087-11e8-9d75-1d56ac1c4a0f.PNG)

## Smart contract
Audit pending - confirmed by email.

![menlomail](https://user-images.githubusercontent.com/38394062/38776412-bb2503a0-408d-11e8-9059-5b2fa7390bf5.jpg)

## Github
[Link](https://github.com/MenloOne/)

## Product
[Blue Paper - Product Vision](https://menloone.docsend.com/view/uu6vcy9)

[White Paper](https://menloone.docsend.com/view/zgf6d4e)

![image](https://user-images.githubusercontent.com/35730440/38494314-531d1e40-3bed-11e8-8d4b-ac1956425fa3.png)

## Vesting
2 months lockup then 2 years vesting

## Additional info
Telegram channel https://t.me/Menloone
Medium https://medium.com/@menloone

### Token sale & distribution
Total Supply: 1,000,000,000 MET
Token sold: 300,000,000 MET
1 ETH = 5000 MET

The MET tokens dedicated to purchasers will represent a maximum of 30% of the total MET outstanding.

- 30% growth pool locked up for future usage.
- 20% team with a lock-up vested over 2 years.
- 10% + 10%  will be used for strategic partners and advisors

![menlo token distribution](https://user-images.githubusercontent.com/38394062/38776470-10c44720-408f-11e8-92a9-c2f8f8854de5.png)

# Flags
**Real Team:** Background checks ongoing ⚠️   
**GitHub:** ✅         
**Smart Contract:** -     
**Working Product (Mainnet):** -      
**+2 yr Vesting for team:** -  Check for codified vesting      
**Have a company:** -  Check if founders are directors                
**Transparent:** -

**Comment by RickBross** [comment]
Awesome! Thanks guys!
