### ISSUE TITLE
DAOstack - Due diligence

### ISSUE THREAD

**Issue by kuangli2000** [ico-check/ico-check#110]
# [DAOstack](https://daostack.io/) (GEN)

[![telegram-chat](https://user-images.githubusercontent.com/32852887/38760208-611df88a-3f7a-11e8-83bc-ca7ba4076a10.png)](https://t.me/daostackcommunity)

# Team
- Matan Field (CEO & Architect) - Nov 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/matan-field-92a2b396/)
- Adam Levi (CTO & Technology) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/adam-levi-ph-d-3bb5164/)
- Nathalia Scherer (Community & Biz dev) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/nathalia-scherer-b181b044/)
- Josh Zemel (Communication) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/joshzemel/)
- Oren Sokolowsky (Lead developer) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/oren-sokolowsky-5505331/)
- Roberto Klein (Legal & Finance) - Jun 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/roberto-klein-a57a95/)
- Shira Smilanski (Administration) | **No Linkedin profile**
- Yehonatan Goldman (Operations) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yehonatan-goldman-90a437a0/)
- Primavera De Filippi (Alchemy) | [Linkedin profile](https://www.linkedin.com/in/primavera-de-filippi-07558536/) **does not mention DAOstack**
- Dor Garbash (Alchemy lead) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/garbash/)
- Tibet Sprague (Alchemy Technical lead) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/tibet-sprague-a135622/)
- Aaron Brodeur (Alchemy Design & UX lead) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/aaronbrodeur/)
- Matan Tsuberi (Developer) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/matan-tsuberi-2b2226a2/)
- Erik Rodrigues (Community management & Research) **No Linkedin profile**
- Danilo Vaz (Community management & Research)
- Patrick Rawson (Community management & Research) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/patrick-rawson-48306867/)

### Advisors
- Daniel Schmachtenberger (Co-founder, Neurohacker Collective) | [Linkedin profile]()
- Jordan Greenhall (Co-founder and ex-CEO of Divx. Co-founder of MP3.com) | [Linkedin profile]()
- Yoni Assia (Founder and CEO of eToro.com.) | [Linkedin profile]()
- Martin Köppelmann (Co Founder and CEO of Gnosis) | [Linkedin profile]()

# Company 

## DAOstack Limited

**Registered office address:**     
GX11 1AA    
Gibraltar      

Private company limited by shares      
Incorporated and registered in Gibraltar      

**Company Number:** 116055            
**Incorporation Date:** 16 Nov 2017     
**Company Type:** Private Company Limited By Shares      
**Status:** Active       

#### Filings
- Mar 15, 2018 - Re-registration private limited to limited by guarantee
- Mar 15, 2018 - Duplicate certificate of re-registration
- Mar 15, 2018 - Amended memorandum of association
- Mar 1, 2018 - Cancellation of shares not issued
- Mar 1, 2018 - 	Amended memorandum of association
- Feb 1, 2018 - Particulars of directors, managers and secretaries, and of any change therein 
- Nov 16, 2017 - Special resolution amending name
- Nov 16, 2017 - Duplicate certificate of change of name
- Nov 16, 2017 - Amended memorandum of association
- Nov 16, 2017 - Amended articles of association

![daostack-gibraltar](https://user-images.githubusercontent.com/32852887/38866971-ead476d8-4242-11e8-8f17-1fd52b9f156c.png)

- [Source](https://portal.kyckr.com/companySearch.aspx)

## Smart contract
- N/A

## Github
- [Daostack](https://github.com/daostack)

## Product
- To check

## Vesting
- To check

### Token distribution
![dao](https://user-images.githubusercontent.com/35653014/38845549-80856778-422a-11e8-9404-3091793b3d29.png)

### Token allocation

# Flags
**Real Team:** -      
**GitHub:** ✅          
**Smart Contract:** -     
**Working Product:** -      
**+2 yr Vesting for team:** -        
**Have a company:** -                  
**Transparent:** -          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by goktugyil** [comment]
this seams to have real team and company right?
