### ISSUE TITLE
Ommer - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#111]
# [Ommer](https://www.ommer.com) (OMR)

### Edit: 12 Nov 2018 - ICO Postponed
![ommer-postponed](https://user-images.githubusercontent.com/32852887/48354009-85fecb80-e645-11e8-92ac-86f0fb9c580d.png)

[![telegram-chat](https://user-images.githubusercontent.com/32852887/38760208-611df88a-3f7a-11e8-83bc-ca7ba4076a10.png)](https://t.me/OmmerDotCom)

## Team
- TK Wong (Chairman) | [Linkedin profile](https://www.linkedin.com/in/tkwong) **profile does not mention Ommer**
- JD Lee (CEO) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/jrande)
- Simon Gerovich (Trading Expert) | [Linkedin profile](https://www.linkedin.com/in/gerovich) **profile does not mention Ommer**
- Tomas Libal (Blockchain Engineer) | **No Linkedin profile** | [Twitter](https://twitter.com/tomas_lbl) | [Github](https://github.com/tomaslibal) | [Keybase](https://keybase.io/goodtay)
- Tors Dalid (Software Engineer) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/torsd) | [Github](https://github.com/tors) | [Keybase](https://keybase.io/torsd)
- Tommy Sim (Emerging Markets Expert) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/tommy-sim-8833ab11)
- Zhiwei Ng (Operations) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/zhi-wei-ng-868551159/) **profile only shows Ommer** | [Github](https://github.com/zhiwei)
- Darren Lee (Business Lead) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/leetd/)
- Cris Factolerin (Software Engineer) | [Linkedin profile](https://www.linkedin.com/in/cris-factolerin-b4114032/) **profile does not mention Ommer** | [Github](https://github.com/cfactolerin)

### Advisors
- Lyn Kok | [Linkedin profile](https://www.linkedin.com/in/lynkok)
- John Lee | [Linkedin profile](https://www.linkedin.com/in/c-g-john-lee-%E6%9D%8E%E6%B3%89%E6%BA%90-80186928)
- Clarence Guo | [Linkedin profile](https://www.linkedin.com/in/clarence-guo-650b8330/)

# Company 

### Pulsar Ventures Pte Ltd.
**Registered Address:**
31, Jurong West Street 41   
16-34
The Lakeshore
Singapore 649412

**Office Address (From website | To check):**    
02-01, Odeon Towers      
331 North Bridge Road     
Singapore 188720                    

**UEN:** 201731274C         
**Company Type Description:** EXEMPT PRIVATE COMPANY LIMITED BY SHARES           
**Incorporation Date:** 1 NOVEMBER 2017                     
**Status:** LIVE COMPANY                

![ommer-singapore](https://user-images.githubusercontent.com/32852887/38869765-09e6e386-424c-11e8-91f6-e4d44e045287.png)

- [Source: SG UEN Search](https://www.uen.gov.sg/)

## Smart contract
- [Contract on Github](https://github.com/OmmerDotCom/ommer-token/tree/master/contracts)

## Github
- [OmmerDotCom](https://github.com/OmmerDotCom)

## Product
- To check

## Vesting
- To check

### Token distribution
- 50% of tokens for sale
- 20% of tokens held as reserves
- 10% of tokens as operational float
- 10% of tokens for incentives

### Token allocation
![ommer-allocation](https://user-images.githubusercontent.com/32852887/38874287-06ab6d98-4258-11e8-8503-cac4c0aaf18b.png)

# Flags
**Real Team:** - To check     
**GitHub:** ✅          
**Smart Contract:** - Not yet deployed      
**Working Product:** - To check    
**+2 yr Vesting for team:** - To check in smart contract 
**Have a company:** - Check if directors are team members.                
**Transparent:** -        

# IcoCheck
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by kuangli2000** [comment]
Too many similar products, this area is too crowded

**Comment by tors** [comment]
@kuangli2000 Hi! I'm from the Ommer team. We're geographically focused and target HENRY demographic - high earners, not rich yet - individuals. We do not aim to conquer the world but rather we strive to cultivate local trading communities specifically in ASEAN. Our goals include offering the best service and onboarding as many people as we can by making it really easy to acquire and sell cryptocurrency. It should be win all around especially to the crypto community.
