### ISSUE TITLE
QuarkChain - Due diligence

### ISSUE THREAD

**Issue by kuangli2000** [ico-check/ico-check#112]
# [QuarkChain](https://quarkchain.io/) (QKC)

[![telegram-chat](https://user-images.githubusercontent.com/32852887/38760208-611df88a-3f7a-11e8-83bc-ca7ba4076a10.png)](https://t.me/QuarkChainio)

# Development Team

![quarkchain-team](https://user-images.githubusercontent.com/32852887/38967678-7ecc44d8-4388-11e8-9417-5b1dd7b40a51.png)

### Qi Zhou (Founder) - Mar 2018 - Present | [Linkedin profile](http://linkedin.com/in/qi-zhou-9a668715)
 - [Facebook](http://www.facebook.com/careers) | Software Engineer - Mar 2017 - Mar 2018 | **1 yr 1 mo**
 - [Dell EMC](http://www.dellemc.com/) | Consultant Software Engineer - Feb 2017 - Jul 2017 | **9 mos**
 - [EMC](http://www.dellemc.com/) | Principle Software Engineer - Dec 2014 - Jun 2016 | **1 yr 7mos**
 - [Google](http://www.google.com/) | Software Engineer - Apr 2014 - Dec 2014 | **9 mos**
 - [Ratrix Technologies](http://www.ratrixtech.com/) | Senior Engineer - Jul 2013 - Apr 2014 | **10 mos**

### Zhaoguang Wang (Software Engineer) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/zhaoguang-wang-436b8029)
 - [Facebook](http://www.facebook.com/careers) | Software Engineer - Feb 2017 - Mar 2018 | **1 yr 2 mo**
 - [Instagram](http://www.instagram.com/) | Consultant Software Engineer - Mar 2017 - Jun 2017 | **4 mos**
 - [Google](http://www.google.com/) | Principle Software Engineer - Jan 2012 - Jan 2017 | **5 yr 1mos**
 - [AT&T Labs, Inc.](https://www.att.com) | Software Engineer - Jun 2011 - Aug 2011 | **3 mos**

### Wencen Wu (Research Scientist) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/wencen-wu-8b924621/)

# Operation Team

![quarkchain-operation](https://user-images.githubusercontent.com/32852887/38967669-71afc7d4-4388-11e8-8280-5545d27006e1.png)

## Advisors
- Arun G. Phadke | [Wikipedia](https://en.wikipedia.org/wiki/Arun_G._Phadke) | [Virginia tech profile](https://ece.vt.edu/people/profile/phadke)
- Bill Moore | [Linkedin profile](https://www.linkedin.com/in/zfsguy/)
- Mike Miller | [Linkedin profile](https://www.linkedin.com/in/mlmilleratmit/)
- Kevin Hsu | [Linkedin profile](www.linkedin.com/in/yingkaixu/) | [BlockVC](https://blockvcfund.com/team)
- Leo Wang | [Linkedin profile](https://www.linkedin.com/in/betashow/) | [Website](https://www.pre-angel.com)
- Zhiyun Qian | [Linkedin profile](https://www.linkedin.com/in/zhiyun-qian-8410ab25) | [UC Riverside](http://www.cs.ucr.edu/~zhiyunq/)

# OFAC Check
![quarkchain-ofac](https://user-images.githubusercontent.com/32852887/38970259-c6e218cc-4394-11e8-8134-f8e5095c3fb3.png)

### [Source: OFAC Search Tool](https://ofac.finra.org)

# Company 
## QUARKCHAIN FOUNDATION LTD.
**Registered Address:**    
6, EU TONG SEN STREET       
12, THE CENTRAL      
SINGAPORE 059817                     

**UEN:** 201800617H         
**Company Type Description:** EXEMPT PRIVATE COMPANY LIMITED BY SHARES           
**Incorporation Date:** 4 Jan 2018                     
**Status:** LIVE COMPANY                

![quarkchain-singapore](https://user-images.githubusercontent.com/32852887/39884371-ed39ff20-5489-11e8-9bc2-f1b0fad0564e.png)

- [Source: SG UEN Search](https://www.uen.gov.sg/)

## QUARKCHAIN INC.

![4151-middlefield-rd](https://user-images.githubusercontent.com/32852887/38967054-95dd221c-4385-11e8-8c0e-910b4f293ea9.jpg)

**File Number:** 6743508        
**Incorporation Date / Formation Date:** 5 February 2018        
**Entity Kind:** Corporation           
**Entity Type:** General          
**Residency:** Domestic         
**State:** Delaware

**Office Address:**      
4151 Middlefield Rd    
Suite 100c      
Palo Alto     
CA 94303    

**Registered Agent Information:**        
HARVARD BUSINESS SERVICES, INC.         
16192 COASTAL HWY           
LEWES         
Sussex County       
Delaware 19958    
USA

#### Directors
- **Qi Zhou** | Executive Officer, Director

### [Source: Delaware entity search](https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx)

![quarkchain-delaware](https://user-images.githubusercontent.com/32852887/38966847-876a16aa-4384-11e8-987c-b44ed90d09cc.png)

![quarkchain-ca-si-complete](https://user-images.githubusercontent.com/32852887/38967303-ae675fae-4386-11e8-8ed3-c476b6d5a9c0.png)
![quarkchain-ca-registration-1](https://user-images.githubusercontent.com/32852887/38967295-a6c2e8f4-4386-11e8-9282-89b643524d03.png)
![quarkchain-ca-registration-2](https://user-images.githubusercontent.com/32852887/38967299-a85f0328-4386-11e8-8af8-3096ba27e103.png)

# Smart contract
- [Deployed - See on etherscan](https://etherscan.io/address/0xea26c4ac16d4a5a106820bc8aee85fd0b7b2b664#code)

# Github
- [QuarkChain](https://github.com/QuarkChain)

![quarkchain-github](https://user-images.githubusercontent.com/32852887/38890853-e451410c-4282-11e8-883a-d79630f03d84.png)

### Code in private repo
![quarkchain-opensource](https://user-images.githubusercontent.com/32852887/39649206-451bf076-4fe5-11e8-958b-237e0c884408.png)

# Product
- N/A

![quarkchain-testnet-1](https://user-images.githubusercontent.com/32852887/38968447-d677ea90-438b-11e8-8c09-a886cf557062.png)
![quarkchain-testnet-2](https://user-images.githubusercontent.com/32852887/38968449-d7f1ccb0-438b-11e8-9eff-b31266f729fa.png)

## Roadmap
![quarkchain-roadmap](https://user-images.githubusercontent.com/32852887/38967848-3eb25738-4389-11e8-8e49-44599aa81377.png)

# Vesting
- Team and advisors tokens vest over 2 years.
- Foundation tokens locked for 2 years.

### Vesting schedule not coded in the smart contract.

# Additional info
- Whitelist/KYC starts on May 7th, 00:00:01 AM PST
- Private sale hard cap $16M. Public sale hard cap $4M. Total supply 10B QKC.

## Questions not answered by the team
![quarkchain-questions-not-answered-1](https://user-images.githubusercontent.com/32852887/38968632-a3fd1e5e-438c-11e8-96ca-ed633b27d95c.png)
![quarkchain-questions-not-answered-2](https://user-images.githubusercontent.com/32852887/38968634-a60aea8c-438c-11e8-935d-f4187ca0e69c.png)
![quarkchain-questions-not-answered-3](https://user-images.githubusercontent.com/32852887/38968636-a77ea250-438c-11e8-9daf-7add7a99e71b.png)
![quarkchain-questions-not-answered-4](https://user-images.githubusercontent.com/32852887/38968637-a8fbe34a-438c-11e8-8df6-bea64a872d13.png)
![quarkchain-questions-not-answered-5](https://user-images.githubusercontent.com/32852887/39653494-8147b57e-4ff1-11e8-8e71-168b1fe8823e.png)

### May 2nd 2018: User asks about use of proceeds
![quarkchain-questions-not-answered-6](https://user-images.githubusercontent.com/32852887/39653476-6c402f26-4ff1-11e8-8862-83af2b13052f.png)

### May 4th 2018: User asks about use of proceeds
![quarkchain-questions-not-answered-8](https://user-images.githubusercontent.com/32852887/39653572-cceb2fba-4ff1-11e8-938b-8788f4dc74e2.png)
![quarkchain-questions-not-answered-9](https://user-images.githubusercontent.com/32852887/39653574-cef2f888-4ff1-11e8-8ac3-22acf82a7a87.png)
![quarkchain-questions-not-answered-10](https://user-images.githubusercontent.com/32852887/39653576-d1f3bc66-4ff1-11e8-815b-8149859078a8.png)
![quarkchain-questions-not-answered-11](https://user-images.githubusercontent.com/32852887/39653579-d3e110be-4ff1-11e8-9de5-b261db581e43.png)

## Token distribution
![quarkchain-distribution](https://user-images.githubusercontent.com/32852887/39648505-b481542c-4fe2-11e8-9013-b90ffa2c63cb.jpg)

## Token allocation
- N/A

### ‼️ Use of proceeds N/A ‼️

# Flags
**Real Team:** ✅  
**GitHub:** ❌ Code in Private repo. Team said that they will be open sourcing their code in Q2 2018.      
**Smart Contract:** ✅   
**Working Product (Mainnet):** ❌ Public testnet end of Q2    
**+2 yr Vesting for team (codified vesting):** ❌ Team and advisors tokens vest over 2 years. Vesting schedule not codified.      
**Have a company:** ✅                  
**Transparent:** ❌ Use of proceeds not available. The Quarkchain team never replied to investors' questions, showing total disregard to their concerns.      

# IcoCheck.io
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)
- Follow us on [Twitter](https://twitter.com/icocheckio)

**Comment by sky2018hao** [comment]
https://github.com/QuarkChain   This is empty, without any code. However, this project has always been favored by some top ICO consultants. I am a bit difficult to understand. Can someone tell me why?
![dcoitvqvmae_tdb](https://user-images.githubusercontent.com/38766801/39561949-8898aa70-4edb-11e8-9614-aeb85890951f.jpg)
![dcmqwxdwkaayam2](https://user-images.githubusercontent.com/38766801/39561957-92a8c4aa-4edb-11e8-8015-8da8dcdc9029.jpg)

**Comment by zebracrossingblog** [comment]
https://steemit.com/quarkchain/@bitcoinstartrek/quarkchain-red-flags-we-know-something-you-don-t-know
