### ISSUE TITLE
Solana - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#113]
# [Solana](https://solana.io/)

[![telegram-chat](https://user-images.githubusercontent.com/32852887/38760208-611df88a-3f7a-11e8-83bc-ca7ba4076a10.png)](https://t.me/solanaio)

![solana-team](https://user-images.githubusercontent.com/32852887/39085908-466eccba-458a-11e8-96e2-d8a3e306d03a.png)

## Team
- Anatoly Yakovenko (Co-founder & CEO) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/anatoly-yakovenko/) | [Github](https://github.com/aeyakovenko)
- Greg Fitzgerald (Co-founder & CTO) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/gregoryrfitzgerald/) | [Github](https://github.com/garious)
- Eric Williams (Data Science, Token Economics) | [Linkedin profile](https://www.linkedin.com/in/sciencethedata/) **does not mention Solana** | [Github](https://github.com/ericlwilliams) **Joined the solana-labs organization on Mar 19** | [Twitter](https://twitter.com/sciencethedata)
- Raj Gokal (Co-founder & Operations, Product, Finance) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/rajgokal/) | [Github](https://github.com/rajgokal)
- Alan Yu (Co-founder & Strategy, BD, Marketing) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/alan-yu/)
- Stephen Akridge (Co-founder & Engineering) - Apr 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/stephenakridge/) | [Github](https://github.com/sakridge)

### Advisors
- No advisors

# OFAC Check
![solana-ofac](https://user-images.githubusercontent.com/32852887/39085946-e434bc70-458a-11e8-8700-4805f225dfa8.png)

### [Source: OFAC Search Tool](https://ofac.finra.org)

# Company 
## Solana Labs, Inc.
**File Number:** 6790417           
**Incorporation Date / Formation Date:** 9 March 2018           
**Entity Kind:** Corporation           
**Entity Type:** General          
**Residency:** Domestic         
**State:** Delaware     

**Office Address:**     
2 Hoffman Ave 
San Francisco   
CA 94133   
USA   
        
**Registered Agent Information:**        
THE CORPORATION TRUST COMPANY         
CORPORATION TRUST CENTER 1209 ORANGE ST           
WILMINGTON         
New Castle County       
Delaware 19801    
USA     
 
#### Directors
- **Anatoly Yakovenko**
- **Raj Gokal**
        
### [Source: Delaware entity search](https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx)

![solana-delaware](https://user-images.githubusercontent.com/32852887/39085883-f2adbec4-4589-11e8-817f-5466813a2c0f.png)
![solana-statement-of-information](https://user-images.githubusercontent.com/32852887/39085885-f7d9e616-4589-11e8-899f-483f6e174d9c.png)
![solana-reg-1](https://user-images.githubusercontent.com/32852887/39085886-fa216962-4589-11e8-9091-30cf6afecc60.png)
![solana-reg-2](https://user-images.githubusercontent.com/32852887/39085888-fba52698-4589-11e8-8c06-90209e3613f7.png)

## Smart contract
N/A

## Github
- [Solana-labs](https://github.com/solana-labs)

### Commits
- [Solana](https://github.com/solana-labs/solana/graphs/commit-activity)

## Product
 - [Demo](https://github.com/solana-labs/solana)

### Roadmap
![solana-roadmap](https://user-images.githubusercontent.com/32852887/39085976-4bef5e1a-458b-11e8-8fee-51a246865c25.png)

## Vesting
N/A

### Token distribution
N/A

### Token allocation
N/A

# Q&A
![solana-q a-1](https://user-images.githubusercontent.com/32852887/39086022-f818bf10-458b-11e8-81dc-efd8ab25e4f1.png)

# Flags
**Real Team:** ✅      
**GitHub:** ✅          
**Smart Contract:** -     
**Working Product:** -      
**+2 yr Vesting for team:** -        
**Have a company:** ✅                  
**Transparent:** -          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by sky2018hao** [comment]
Qualcomm employees are likely to be a low-key project and successful
