### ISSUE TITLE
Sentinel Protocol - Due diligence

### ISSUE THREAD

**Issue by ymoctavia** [ico-check/ico-check#114]
# [Sentinel Protocol](https://sentinelprotocol.io/) (UPP)

[![telegram-chat](https://user-images.githubusercontent.com/32852887/38760208-611df88a-3f7a-11e8-83bc-ca7ba4076a10.png)](https://t.me/sentinelprotocol)

## Team that recently joined Uppsala Foundation
- Patrick Kim (Founder & CEO) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/%ED%98%95%EC%9A%B0-%EA%B9%80-0880b467/)
- HM Park (Co-founder & Head of Operations) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/hae-min-park-92027049/)
- John Kirch (Chief Evangelist) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/johnkirch/)
- Narong Chong (Head of Security Operations) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/narong-chong-0262322/)
- Minwoo Ku (Head of Product) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/min-woo-ku-50341821/)
- Karly Choi (Head of Marketing) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/choisoojin/)

## Team members with no mention of Uppsala Foundation in their Linkedin profiles:
- Dayeol Lee (Core Development) | [Linkedin profile](https://www.linkedin.com/in/lee-dayeol-4b70688a/) **does not mention Uppsala Foundation**
- Michael Zhou (Head of Threat Intelligence) | [Linkedin profile](https://www.linkedin.com/in/michaelzhouchong/) **does not mention Uppsala Foundation**

### Advisors
N/A

### UPPSALA PTE. LTD.
**Registered Address:**
80, RAFFLES PLACE       
32-01       
UOB PLAZA       
SINGAPORE 048624  

**Other Address:**    
6 EU TONG SEN STREET      
09-12        
THE CENTRAL      
SINGAPORE 059817                        

**UEN:** 201801451C         
**Company Type Description:** EXEMPT PRIVATE COMPANY LIMITED BY SHARES           
**Incorporation Date:** 11 Jan 2018                     
**Status:** LIVE COMPANY                

![sentinel-protocol-singapore](https://user-images.githubusercontent.com/32852887/39096358-262b917a-464f-11e8-901a-0ca67a565e53.png)

- [Source: SG UEN Search](https://www.uen.gov.sg/)

## Smart contract
- Github N/A, cannot audit smart contract.
- ERC20 token

![sentinel-protocol-erc20](https://user-images.githubusercontent.com/32852887/39096688-b3da2708-4653-11e8-9dc3-814a007ee6eb.png)

## Github
- N/A

## Product
- Public beta in june.

### Roadmap
![sentinel-protocol-roadmap](https://user-images.githubusercontent.com/32852887/39097051-25d1fa36-4657-11e8-8caf-89cbb261d304.png)

### Team and advisors tokens vest over 2 years but not coded in the smart contract.

# Additional info
## Token distribution
![sentinel-protocol-distribution](https://user-images.githubusercontent.com/32852887/39096978-80337730-4656-11e8-9ead-2c966eb5ec07.png)

## Token allocation
![sentinel-protocol-allocation](https://user-images.githubusercontent.com/32852887/39096982-8911e562-4656-11e8-9279-7f28377ece4c.png)

# Q&A
![sentinel-protocol-qa-1](https://user-images.githubusercontent.com/32852887/39096362-345d5fbc-464f-11e8-9836-8c9bf62382ce.png)
![sentinel-protocol-qa-2](https://user-images.githubusercontent.com/32852887/39096363-35b8980e-464f-11e8-95d1-7c1c1e0e5753.png)
![sentinel-protocol-qa-3](https://user-images.githubusercontent.com/32852887/39096364-36db4916-464f-11e8-8956-5e2624385628.png)

# Flags
**Real Team:** ✅     
**GitHub:** ❌          
**Smart Contract:** - Not yet deployed. Not available to audit.    
**Working Product (Mainnet):** ❌ Public beta in june.
**+2 yr Vesting for team:** ❌ Team and advisors tokens vest over 2 years but not coded in the smart contract.        
**Have a company:** ✅                  
**Transparent:** - Smart contract was not audited by an independent cybersecurity company.          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by icochecker** [comment]
@ymoctavia issue updated
