### ISSUE TITLE
edenchain

### ISSUE THREAD

**Issue by sky2018hao** [ico-check/ico-check#116]
# [ICO name](ICO website)
https://edenchain.io/
## Team
*Here list team members with links to their LinkedIn accounts in here*
James Ahn
CEO, Founde   https://www.linkedin.com/in/james-ahn-b5aa02140/
Jenny Ryoo
Co-Founder,
Blockchain Developer  https://www.linkedin.com/in/jenny-ryoo-017626159/
Hokyun Kim
Blockchain Developer   https://www.linkedin.com/in/hokyun-kim-b292a511/
Brian Park
Blockchain Developer   https://www.linkedin.com/in/brian-park-2965a815b/
Kangho Kim
Chief Strategy Officer   https://www.linkedin.com/in/kangho-kim-83024079/

HJ Moon
Chief of Business Development, 
Asia    https://www.linkedin.com/in/hj-moon-96772b20/
 
Richard Jahnke
Business Development, 
US and Europe (San Francisco)   https://www.linkedin.com/in/richard-jahnke-554a7a3/

Kathy Roe
Marketing    https://www.linkedin.com/in/kathy-roe-822b6015b/

Jessica Park
Marketing     https://www.linkedin.com/in/jessica-park-387b5a15b/ 

 Aaron Tay
Financial Advisor (Singapore)   https://www.linkedin.com/in/aarontwl/

### Advisors
*Here list advisors with links to their LinkedIn accounts in here*
Don Chang, Ph.D.
Advisor     https://www.linkedin.com/in/don-chang-334b822/
Joongheon Kim, Ph.D.
Advisor     https://www.linkedin.com/in/joongheon/

Sungho Kim, Ph.D.
Advisor      https://www.linkedin.com/in/sungho-kim-12a54a73/

Alan Moonsoo Kim
Advisor      https://www.linkedin.com/in/alanmoonsookim/

 James Jahnke
Advisor      https://www.linkedin.com/in/jojahnke/

 Mina Jeong
Advisor     https://www.linkedin.com/in/minajeongkoreaprspecialist/

Marat Zhanispayev
Advisor     https://www.linkedin.com/in/marat-zhanispayev-61568024/

Young Choe, Ph.D.
Advisor      https://www.linkedin.com/in/young-choe-8033684/

Mirza Uddin
Advisor     https://www.linkedin.com/in/themirzauddin/  

## Company
*Here put company information if company exsits. Also provide links (and possibly screenshots) where it can be verified that company exists*

## Smart contract
*Here put e.g. link to contract address on etherscan*

## Github
*Here put link to company's GitHub*

## Product
*Here put link to the product if exists and attach screenshots.*
EDENCHAIN
A programmable economy platform
A next-generation blockchain platform for a decentralized world

## Vesting
*Here put information where vesting information was found and attach screenshots.*

## Additional info
*Here put additional comments about the company, with links when possible*

### Token distribution
*Here put token distribution screenshot or info, with links when possible*
![default](https://user-images.githubusercontent.com/38766801/39327427-92271696-49ca-11e8-8fd0-c6e9da7bdc0d.png)

### Token allocation
*Here put token allocation screenshot or info, with links when possible*

**Comment by icochecker** [comment]
@sky2018hao Duplicate see https://github.com/ico-check/ico-check/issues/87
