### ISSUE TITLE
Cointal - Background check

### ISSUE THREAD

**Issue by Empresaria** [ico-check/ico-check#117]
# [Cointal](https://www.cointal.com/page/aboutus)

# [Fraud - Source: reddit](https://www.reddit.com/r/Bitcoin/comments/80s19k/cointal_exchange_is_a_fraud_they_are_being_sued/)

## Mohammed Imad pending.. 
*Here list team members with links to their LinkedIn accounts in here*

### Advisors
*Here list advisors with links to their LinkedIn accounts in here*

## Company
*Here put company information if company exsits. Also provide links (and possibly screenshots) where it can be verified that company exists*

## Smart contract
*Here put e.g. link to contract address on etherscan*

## Github
*Here put link to company's GitHub*

## Product
*Here put link to the product if exists and attach screenshots.*

## Vesting
*Here put information where vesting information was found and attach screenshots.*

## Additional info
*Here put additional comments about the company, with links when possible*

### Token distribution
*Here put token distribution screenshot or info, with links when possible*

### Token allocation
*Here put token allocation screenshot or info, with links when possible*

**Comment by icochecker** [comment]
@Empresaria An issue with no information is not very helpful. In the future please give more info before opening an issue. Thanks

**Comment by Empresaria** [comment]
I apologize I am working on this these issues now.  It will not happen
again.
