### ISSUE TITLE
FTEC - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#119]
# [FTEC](https://ftec.io/) (FTEC)

### Web archive for ftec.io
- [27 Mar 2018](https://web.archive.org/web/20180327095514/https://ftec.io/)
- [4 Apr 2018](https://web.archive.org/web/20180327095514/https://ftec.io/)
- [18 Apr 2018](https://web.archive.org/web/20180327095514/https://ftec.io/)

# Whois lookup for FTEC.IO
```
Domain Name: FTEC.IO
Registry Domain ID: D503300000061705794-LRMS
Registrar WHOIS Server:
Registrar URL: https://www.101domain.com
Updated Date: 2018-04-11T16:11:03Z
Creation Date: 2018-02-04T23:40:59Z
Registry Expiry Date: 2022-02-04T23:40:59Z
Registrar Registration Expiration Date:
Registrar: 101domain GRS Ltd
Registrar IANA ID: 1011
Registrar Abuse Contact Email: abuse@101domain.com
Registrar Abuse Contact Phone: +1.8582954626
Reseller:
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: serverTransferProhibited https://icann.org/epp#serverTransferProhibited
Registrant Name: Daniel O'Donoghue
Registrant Organization: MITRIDAT GROUP LP
Name Server: CHUCK.NS.CLOUDFLARE.COM
Name Server: VAL.NS.CLOUDFLARE.COM
DNSSEC: unsigned
```

# Team

![evgeniy-sidelnikov-ownership-mitridat](https://user-images.githubusercontent.com/32852887/39574900-feb5f42c-4ed8-11e8-8890-b4a297ad6178.png)

![ftec-evgeniy-sidelnikov-question](https://user-images.githubusercontent.com/32852887/39575196-f47a9ea8-4ed9-11e8-8c24-1495e62b7318.png)

## Evgeniy Sidelnikov (CFO) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/evgeniy-sidelnikov-5b3507159/)

![ftec-evgeniy sidelnikov](https://user-images.githubusercontent.com/32852887/39574441-86d5d22a-4ed7-11e8-823b-32e9eb4fd058.png)

- Ihor Torshyn (CEO) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/ihortorshyn/)
- Stanislav Ochkur (Business Development) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/stasochkur/)
- Luis Felicio (CTO) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/luis-felicio-b45368102/)
- Julián Marcelo Bernal González (Cyber Security Specialist) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/juli%C3%A1n-marcelo-bernal-gonz%C3%A1lez-4578a285/)
- Tim Marchini (Head of Marketing) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/tmarchini/)
- Viktor Daverman (Developer TeamLead) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/viktordaverman/)
- Roscislav Gorbachov (Head Trader) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/roscislavgorbachov/)
- Vlad Nesmiian (Legal Advisor) | [Linkedin profile](https://www.linkedin.com/in/vlad-nesmiian-599159131/) **does not mention FTEC Foundation**
- Max Bashmakov (Art Director) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/maximbashmakov/)
- Andrea Meeld (Senior Trading Advisor) - Jul  2017 - Present | [Linkedin profile](https://www.linkedin.com/in/andreameeld/)
- Egor Osaulenko (Software Developer) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/egor-osaulenko-b073444b/)
- Kate Klymko (UI/UX Designer) - Jul 2017 - Present | [Linkedin profile](http://linkedin.com/in/kate-klymko-305036160) **does not mention any work experience between 2012 and Jul 2017**
- Denys Bannikov (Blockchain Developer) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/denys-bannikov-2a056a73/)
- Janine Lakhotska (Trading Analyst) | [Twitter](https://twitter.com/JLokhotska) | **No linkedin profile**
- Oleg Mazurok (Trading Analyst) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/olegmazurok/)
- Alena Tymoshenko (Content Manager) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/alenatymoshenko/)

### Advisors
- Jack Shin | [Linkedin profile](https://www.linkedin.com/in/jackhex/)
- Alex Gokul | [Linkedin profile](https://www.linkedin.com/in/gokulbabyalex/)
- Tyler Sanford | [Linkedin profile](https://www.linkedin.com/in/tylersanford/)
- Andrei Popescu | [Linkedin profile](https://www.linkedin.com/in/andreidragospopescu/)
- Vladimir Nikitin | [Linkedin profile](https://www.linkedin.com/in/icoadv/)
- Andrey Dryga | [Linkedin profile](https://www.linkedin.com/in/andrey-dryga/)

# Company

### [FTEC TECHNOLOGIES LIMITED](https://beta.companieshouse.gov.uk/company/11393317) 
**Company number:** 11393317              
**Registered office address:**            
Suite 6      
5 Percy Street      
London W1T 1DG            
United Kingdom     
**Incorporated on:** 1 June 2018  
**Share Capital:** 100 GBP       
**Nature of business (SIC)**        
58290 - Other software publishing

### Director: Ihor TORSHYN        
**Nationality:** Ukrainian        
**Country of residence** Ukraine          
**Role:** Director       
**Date of birth:** August 1990

### [MITRIDAT GROUP LP](https://beta.companieshouse.gov.uk/company/SL031014)
**LP Number:** 11174171              
**Registered office address:**            
Suite 4531             
Mitchell House          
5 Mitchell Street           
Edinburgh EH67BD       
Scotland            
**Registered on:** 19 April 2017         
**Company type** Limited partnership     

### General partner:
- BRENNAN DEVELOPMENT INC.
- NIS GLOBAL CORP. | Director: James Dickins     

### Brennan Development Inc.              
**Registered office address:**            
Suite 208 Blake Building   
Corner Eyre & Hutson Streets     
Belize City      
Belize                 
        
**Registration Number:** 159858     
**Director:** Danny O'Donoghue     

### NIS GLOBAL CORP.              
**Registered office address:**            
Suite 208 Blake Building   
Corner Eyre & Hutson Streets     
Belize City      
Belize                 
        
**Registration Number:** 159857    
**Director:** James Dickins      

### [Source: NIS Global Corp - Companies house](https://beta.companieshouse.gov.uk/search?q=NIS+GLOBAL+CORP.)

# Smart contract
- [Contract source on Gist](https://gist.github.com/siman/a234e5b918804d8b687f9a40184a2f52)
- [Deployed - see on etherscan](https://etherscan.io/address/0x75b3abf31ca0e8ba36bf3938b6095a5b7f8b4c71#code)

# Github
- [FtecFoundation](https://github.com/FtecFoundation)

### Commits
- [FtecMainModule](https://github.com/FtecFoundation/FtecMainModule/graphs/commit-activity)

![ftecmainmodule-commits](https://user-images.githubusercontent.com/32852887/39530838-15628b90-4e2a-11e8-9839-267387c3ebe0.png)

# Product
- [Demo on iOS](https://itunes.apple.com/us/app/ftec/id1365040387?mt=8)
- [Demo on Android](https://play.google.com/store/apps/details?id=ftec.app)

![ftec-app](https://user-images.githubusercontent.com/32852887/39530152-a5bc400c-4e28-11e8-983d-e6a4e953d1a1.png)

# Vesting ‼️
### Token distribution
![ftec-distribution](https://user-images.githubusercontent.com/32852887/39531834-6163270a-4e2c-11e8-9e08-2fa7c28edf8d.png)

### Token allocation
- 

# Flags
**Real Team:** ✅ Linked profile of CFO Evgeniy Sidelnikov is confusing as it shows that he was 13yo when he went to grad school (MIT). It has been verified that he never went to MIT.  
**GitHub:** ✅          
**Smart Contract:** ✅    
**Working Product (mainnet):** ❌ Demo on IOS and Android. Products not connected to blockchain.     
**+2 yr Vesting for team:** ❌ Team tokens vest over 1 year. No vesting schedule for advisors tokens.       
**Have a company:** ✅ FTEC registered a new limited company in the UK for the ICO. Ihor Torshyn (CEO) is director.           
**Transparent:** ❌ Linked profile of CFO Evgeniy Sidelnikov is confusing as it shows that he was 13yo when he went to grad school (MIT). It has been verified that he never went to MIT.        

# IcoCheck.io
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by FtecFoundation** [comment]
Hello! Thank you for review! So, our CFO Evgeniy Sidelnikov is the Owner of Mitridat LP by the Trust declaration, and documents clearly saying that he is OWNER. I would like to share this document with your team member and change the warning of the review. Please tell me what is the best way to do that.

**Comment by FtecFoundation** [comment]
Also I would like to ask why you said that we don’t have working product?
If you are speaking about MVP which we have in App Store and Android, then it is just demo, you can check future design , etc
But we also have ready and working product coinbot.club which is one of the biggest part of our future ecosystem FTEC.

**Comment by FtecFoundation** [comment]
Coinbot.club is ready product and have more than 10 000 active users for now. But if you require decentralised product, than it is not about coinbot.club..we will do FTEC decentralised and coinbot will be part of it, but our product  is centralised for now. So yes, you are right.
