### ISSUE TITLE
Bankorus - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#125]
# [Bankorus](https://www.bankorus.com/) (BKT)

[![telegram-chat](https://user-images.githubusercontent.com/32852887/38760208-611df88a-3f7a-11e8-83bc-ca7ba4076a10.png)](https://t.me/bankorus)

## [Whitepaper 1.0.1](https://www.docdroid.net/CdWRVkD/bankorus-whitepaper-101.pdf)

# 🔥 Update 17 May 2018 - The latest statement made by Stephen Kade saying that he is transitioning from CTO of Bankorus to CTO Advisory contradicts what he previously wrote, stating that Bankorus should not have listed him as the CTO, and misrepresented his relationship with them. 🔥

![stephen-kade-bankorus-statement-17-may](https://user-images.githubusercontent.com/32852887/40333901-31818e44-5d5b-11e8-8a99-baec2393150b.png)

# 🔥 Update 10 May 2018 - Stephen Kade has confirmed that he is not the CTO of Bankorus 🔥
![trusttoken-stephen-kade-update](https://user-images.githubusercontent.com/32852887/39842970-2e7c601e-53e9-11e8-8faa-07aa846537f9.png)

![bankorus-cto-stephen-kade](https://user-images.githubusercontent.com/32852887/39773779-4c4395f4-52f9-11e8-993c-bae908f6c746.png)

# Questions about CTO Stephen Kade
![bankorus-stephen-kade](https://user-images.githubusercontent.com/32852887/39770876-a2efceee-52f0-11e8-8b57-f26fdc074645.png)
![bankorus-stephen-kade-2](https://user-images.githubusercontent.com/32852887/39770879-a555fd48-52f0-11e8-9e99-788ea67af4cb.png)
![bankorus-stephen-kade-3](https://user-images.githubusercontent.com/32852887/39770882-a75ebe40-52f0-11e8-8679-0dc26f58d913.png)

## Team
- Gregory Van den Bergh (CEO) - **Month?** 2014 - Present | [Linkedin profile](https://www.linkedin.com/in/gregoryvandenbergh/)
- 安 An华国 Eagle (Co-Founder & President) - Aug 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/%E5%8D%8E%E5%9B%BD-eagle-%E5%AE%89-an-4b67a633/)
- Anne-Flore Goldsberry (Chief Marketing Officer) - **Month?** 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/afgoldsberry/)
- Prof Geert Bekaert (Co-Chief Investment Officer) | [Linkedin profile](https://www.linkedin.com/in/geert-bekaert-11a2456/) **does not mention Bankorus**
- Prof Ouyang Hui (Co-Chief Investment Officer) | [Linkedin profile](https://www.linkedin.com/in/hui-ou-yang-75094016/) **does not mention Bankorus**
- Stephen Kade (Chief Technology Officer) | [Linkedin profile](https://www.linkedin.com/in/stephenkade/) **does not mention Bankorus** (Co-founder & COO of Trust Token)
- Fiona Guo (Head of human capital) - Mar 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/fionaguo)
- Liyu Shen (Dev-OPS Engineer) | **no linkedin profile**
- Jenny Sun (Finance Manager) | **no linkedin profile**
- Zhifang Du (User Experience Design Lead) - Jun 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/duzhifang/)
- Kevin Yang (Product Manager) | **no linkedin profile**
- Xiaobo Yang (Sr. Front-to-End Engineer) | **no linkedin profile**
- Ming Gao (UI Designer) | **no linkedin profile**
- Aaron Luo (Head of Engineer) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/aaron-luo-b4399691/) **only mentions Bankorus**
- Tom Li (Python Engineer) - Aug 2017 - Present | [Linkedin profile](www.linkedin.com/in/tom-li-7a859025)
- Qiang Li (Machine Learning Engineer) | **no linkedin profile**
- Eric Du (UI Designer) | **no linkedin profile**
- Ryan Shan (AQR Director) | **no linkedin profile**
- Cici Guo (Project Manager) | **no linkedin profile**
- Meredith Darden (Community Manager) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/meredithadarden)
- Dayan Paiewonsky (Community Manager) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/meredithadarden)
- Allen Yilun Zhang (Business Analyst at Bankorus) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/allen-yilun-zhang-49068591)
- J K **Full name?** (Recruiting Manager) - Mar 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/j-k-644224b0/)
- Jay Majumdar (Business Analyst) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/jay-majumdar-407b46121)
- Nicholas Waln (Marketing Manager) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/nicholas-waln-b3572b57/)
- Steffi Kwo (Business Analyst Intern) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/steffi-kwo-bbaa1a157/)
- Claudio Facheris (Business Analyst Intern) - Apr 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/claudio-facheris-5667b067/)
- Temirlan Moltoev (Business Analyst Intern) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/temirlan-moltoev-b45316158/)

## Micai (Parent company)
- Konrad Wojas (CTO) - Jan 2014 - Present | [Linkedin profile](https://www.linkedin.com/in/konradwojas/)
- Menglong(梦龙) Li (Python Engineer) - Apr 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/limenglong/)

### Advisors
- Carl Bennetts | [Linkedin profile](https://www.linkedin.com/in/carlbennetts/)
- David Johnston | [Linkedin profile](https://www.linkedin.com/in/davidajohnston/)
- Sonic Zhang | [Linkedin profile](https://www.linkedin.com/in/sonic-zhang-61180253/)
- Lon Wong | [Linkedin profile](https://www.linkedin.com/in/lonwong1/)
- Sebastian Quinn-Watson | [Linkedin profile](https://www.linkedin.com/in/sebastian-quinn-watson-645457b3/)
- Georgina Tan | [Linkedin profile](https://www.linkedin.com/in/georginat/)
- Charles-Edouard Bouée | [Linkedin profile](https://www.linkedin.com/in/charlesedouardbouee/)
- Roger W. Kirby | [Bio](http://www.kmllp.com/attorney.asp?key=1)
- Antanas Guoga | [Linkedin profile](https://www.linkedin.com/in/antanasguoga/)

# Company 
## Micai Limited
**Registered Address:**
FLAT B, 4/F, Kingswell Commercial Tower          
171-173 Lockhart road        
Wanchai        
Hong Kong         

**Business Name:** China International ETF Association           
**CR No.:** 2058941        
**Company Type:** Private company limited by shares         
**Date of Incorporation:** 20 Mar 2014         
**Active status:** Live         

**Class of shares:** Ordinary          
**Total number of shares:** 1    
**Share capital:** 1             
**Currency:** HKD           

### Director
- Gregory Van den Bergh        

####  OCR Company Secretary Services Limited     
Suite 603, 6/F                        
Laws Commercial Plaza                   
788 Cheung Sha Wan Road, Kowloon           
Hong Kong     
        
## Micai Inc.
**Address:**
P.O. Box 2075        
George Town      
Grand Caymans KY1-1105    
Cayman Islands      

# MiCai registered as investment Advisor with Finra and SEC

### On Bankorus website
![bankorus-finra-sec](https://user-images.githubusercontent.com/32852887/39777772-bf5fcd54-5304-11e8-927c-28c09933d4aa.png)

### SEC Investment adviser public disclosure
![bankorus-advisery-firm](https://user-images.githubusercontent.com/32852887/39778052-94c6e8ec-5305-11e8-961d-c468474be106.png)

## Smart contract
- N/A

## Github
- N/A

## Product
![bankorus-product](https://user-images.githubusercontent.com/32852887/39770256-c4675ff8-52ee-11e8-83fe-1d4c158f4e16.png)

## Roadmap
![bankorus-roadmap](https://user-images.githubusercontent.com/32852887/39773509-a6aa7324-52f8-11e8-860b-756eeba9e72e.png)

## Vesting
- Team tokens vest over 4 years. 

![bankorus-vesting-1](https://user-images.githubusercontent.com/32852887/39770640-e2c1d02c-52ef-11e8-987d-eb2cf8295eed.png)
![bankorus-vesting-2](https://user-images.githubusercontent.com/32852887/39770646-e4b60aba-52ef-11e8-9d11-3b6c2eb47d4f.png)

### Token distribution
- N/A

### Token allocation
- N/A

# Bankorus  Flags
**Real Team:** - Cannot verify that all team members work for Bankorus. Stephen Kade has confirmed that he is not the CTO of Bankorus but a remote technology advisor. **Update: Stephen Kade Contradicted himself by admitting that he is the CTO of Bankorus.**
**GitHub:** ❌ Available after the conclusion of the token sale          
**Smart Contract:** - N/A yet    
**Working Product (Mainnet):** ❌      
**+2 yr Vesting for team:** - Team tokens vest over 4 years. To check in the deployed smart contract        
**Have a company:** ✅                  
**Transparent:** ❌ Stephen Kade Contradicted himself by admitting that he is the CTO of Bankorus.         

# IcoCheck.io
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)
- Follow us on [Twitter](https://twitter.com/icocheckio)

**Comment by icochecker** [comment]
🔥 Update 10 May 2018 - Stephen Kade has confirmed that he is not the CTO of Bankorus 🔥

![trusttoken-stephen-kade-update](https://user-images.githubusercontent.com/32852887/39843762-f445099c-53ec-11e8-90ae-113050bef4a0.png)

**Comment by Hodlito** [comment]
Hello. Im Hodlito from IcoCheck team. Regarding  Bankorus issue:

1- We analyze the current state of the Bankorus project, and since their smart contract is not deployed and they have no github, that's what we stated. Once they fix those issues (if they ever do) we will update the check.

2- Regarding Stephen Kade, who appears as CTO of Bankorus:

    - As you can see on the github issue screenshots, Stephen himself assured that he was NOT the CTO of Bankorus, and that he was only a remote technology *advisor*. He also said that "Bankorus should not have listed me as the CTO, and misrepresented my relationship with them by doing so. I have asked them to correct the webpage to list me as an advisor".
    
    - After reaching out to all Bankorus team members, Seb QW (bankorus chat admin and Partner at First Point Ventures) said that "Stephen has clarified the misunderstanding and retracted his incorrect assertions.". When asked for a source to prove that claim, he didn't provide one.
    
    - Stephen Kade then wrote a vague statement, on bankorus chat, where he claimed that "I look forward to supporting the team as Technical Advisor for the foreseeable future. ".
    
    -When asked the specific questions: "Were you at any point CTO of bankorus? If yes, for how long, in which period of time, and part or full time?" and after insisting for 2 days with no answer, he replied: "I'm advising the incoming CTO and will remain advising the project. Bankorus has a strong team, technology, and network of partners - it's bigger than me or any other particular person. Let's move past the particulars of the CTO conversation, look forward to the incoming Bankorus team, and focus on what's ahead."
    
    -Since he hasn't directly confirm that he was at some point CTO of Bankorus, we will consider that he wasn't, and are willing to update the issue once we get official confirmation from him, from Bankorus CEO, as well as get the pertinent legal documents as a proof of veracity.
    
3- In relation to the product, we reached Bankorus on twitter and telegram, so that they could comment on it and provide any extra information that we may have missed. However, they didn't make any comment, so we assumed that they agreed with out analysis. We will look for the app and if we manage to find and test it, and check that it indeed uses blockchain related technology in any way,  we will update the issue as well.

4- We at IcoCheck would like to state that we do not have any particular preference towards or against the teams we analyze. We aim to be as objective as possible and provide the most truthful information to help users make more educated decisions as well as avoid getting scammed. All our reviews are open and any project we analyze as well as any Github user can comment on a specific issue and bring any extra information they consider important.
