### ISSUE TITLE
CERTIK - Due Diligence

### ISSUE THREAD

**Issue by TuanDo67** [ico-check/ico-check#127]
# [CERTIK](https://certik.org) (CTK)

[![telegram-chat](https://user-images.githubusercontent.com/32852887/38760208-611df88a-3f7a-11e8-83bc-ca7ba4076a10.png)](https://t.me/certikorg)

# Web archive
- [May 11 2018](https://web.archive.org/web/20180511174307/https://certik.org/)
- [Mar 9 2018](https://web.archive.org/web/20180309055627/https://certik.org/)
- [Jan 5 2018](https://web.archive.org/web/20180309055627/https://certik.org/)

# Whois Lookup
```
Domain Name: CERTIK.ORG
Registry Domain ID: D402200000004610893-LROR
Registrar WHOIS Server: whois.godaddy.com
Registrar URL: http://www.godaddy.com
Updated Date: 2018-02-21T03:48:18Z
Creation Date: 2017-12-22T06:38:30Z
Registry Expiry Date: 2019-12-22T06:38:30Z
Registrar Registration Expiration Date:
Registrar: GoDaddy.com, LLC
Registrar IANA ID: 146
Registrar Abuse Contact Email: abuse@godaddy.com
Registrar Abuse Contact Phone: +1.4806242505

Registrant Contact
Name: Ronghui Gu
Organization: Yale University
Mailing Address: 76 Everit St, New Haven Connecticut 06511 US
Phone: +1.2034302840
Ext:
Fax:
Fax Ext:
Email:guronghuieric@gmail.com
```

# Team
### Ronghui Gu (Co-founder) | [Linkedin profile](https://www.linkedin.com/in/guronghui) **does not mention Certik, LLC** ⚠️ | [Personal website](http://guronghui.com/)
 - [Columbia University (NY)](http://columbia.edu/) | **Assistant Professor** - Jan 2018 - Present
 - [Yale University](http://yale.edu/) | **Associate Research Scientist** - Sep 2016 - Dec 2017

### Zhong Shao (Co-founder) | [Linkedin profile](https://www.linkedin.com/in/zhong-shao-545b754) **does not mention Certik, LLC** ⚠️ | [Yale Bio](http://www.cs.yale.edu/homes/shao-zhong/)
 - [Yale University](http://yale.edu/) | Thomas L. Kempner **Professor of Computer Science** - Dec 2017 - Present
 - [Yale University](http://yale.edu/) | **Department Chair for Computer Science** - Jul 2017 - Present
 - [Yale University](http://yale.edu/) | **Professor Of Computer Science** - Jul 2003 - Present
 - [Yale University](http://yale.edu/) | **Associate Professor Of Computer Science** - Jul 2000 - Jun 2003
 - [Yale University](http://yale.edu/) | **Assistan Professor of Computer Science** - Jul 1994 - Jun 2000

### Vilhelm Sjöberg (Research Scientist) | [Linkedin profile](https://www.linkedin.com/in/vilhelm-sj%C3%B6berg-9b667a94) **does not mention Certik, LLC and is empty** ⚠️ | [Yale Bio](http://www.cs.yale.edu/homes/vilhelm/)

![vilhelm-sjoberg](https://user-images.githubusercontent.com/32852887/39938589-ba33c0aa-5553-11e8-9eed-ad9efaf6c847.png)

# OFAC Check ✅
![certik-ofac](https://user-images.githubusercontent.com/32852887/39938682-04c9efae-5554-11e8-814a-4b07473a5956.png)

# Advisors
- No advisors

# Company

## CERTIK, LLC
**File Number:** 1265751          
**Incorporation Date / Formation Date:** Mar 08, 2018          
**Entity Kind:** Corporation           
**Entity Type:** General          
**Residency:** Domestic         
**State:** Delaware     

**Business Address:**     
5 AUTUMN RIDGE ROAD     
BRANFORD       
CT 0640 5     
USA    
        
**Registered Agent Information:**        
CT CORPORATION SYSTEM    
Corporation Trust Center        
1209 ORANGE STREET           
WILMINGTON          
New Castle County        
Delaware 19801      
USA      
 
#### Directors
- **Ronghui Gu** | Director, Executive
        
### [Source: Connecticut entity search](https://www.concord-sots.ct.gov/CONCORD/online?sn=PublicInquiry&eid=9740)

![certik-connecticut](https://user-images.githubusercontent.com/32852887/39962548-0ad5d012-5652-11e8-8e52-72719345e311.png)

## CERTIK FOUNDATION LTD.
**Registered Address:**    
9, TEMASEK BOULEVARD       
04-02        
SUNTEC TOWER TWO    
SINGAPORE 038989                    

**UEN:** 201804796Z         
**Company Type Description:** EXEMPT PRIVATE COMPANY LIMITED BY SHARES           
**Incorporation Date:** 6 Feb 2018                     
**Status:** LIVE COMPANY                

![certik-singapore](https://user-images.githubusercontent.com/32852887/40284771-3d5710a8-5c94-11e8-968c-e7820e85ca11.png)

- [Source: SG UEN Search](https://www.uen.gov.sg/)

## From the "TERMS AND CONDITIONS OF TOKEN SALE AND USAGE" page
>Your purchase, whether through an intermediary or otherwise, of CertiK tokens (CTK) from **CertiK Limited, a company incorporated in the British Virgin Islands** ....

## CertiK Limited (BVI)      
**Address:** N/A
     
**Registration Number:** N/A   

# Smart contract
- N/A

# Github
- [CertikProject](https://github.com/CertiKProject)

### 2 Forks and no other repos

# Product
- N/A

# Vesting
- N/A

# Additional info
### Token distribution
- N/A

### Token allocation
- N/A

# Flags
**Real Team:** ⚠️ 3 team members listed on [Certik](https://certik.org) website. Cannot verify that all team members work for Certik, LLC.      
**GitHub:** ⚠️ 2 Forks and no other repos        
**Smart Contract:** -     
**Working Product:** - To check.     
**+2 yr Vesting for team:** - To check.       
**Have a company:** Check if founders are directors of CertiK Limited (BVI). Address and registration number missing.              
**Transparent:** -          

# IcoCheck.io
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)
- Follow us on [Twitter](https://twitter.com/icocheckio)

**Comment by jeffreyrufino** [comment]
So is this a scam or not?

**Comment by jaggedsoft** [comment]
```Finally, Binance Labs stated that they have already invested in four projects. These are: the cryptocurrency MobileCoin, a high-performance public blockchain by Oasis Labs, verification platform known as Certik, and a crowdfunding platform called Republic.```
https://www.newsbtc.com/2018/06/01/binance-announces-the-formation-of-a-1-billion-blockchain-investment-fund/
Looks like Binance, Ontology, NEO and Qtum have actually invested in this project.

https://medium.com/ontologynetwork/ontology-partners-with-certik-to-build-reliable-blockchain-security-5faf7e681801
https://medium.com/neo-smart-economy/neo-partners-with-certik-for-next-secure-smart-economic-model-7f342d98e30e
https://www.reddit.com/r/Qtum/comments/8cvi46/the_yale_project_certik_will_provide_formal/
