### ISSUE TITLE
Potentiam - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#13]
# [Potentiam](https://www.potentiam.io) (PTM)

## Team
- Marcus O Adetola (Co-founder & CEO) - 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/marcusadetola/) | **Location:** London, United Kingdom
- Ben Balogun (Co-founder & COO) - 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/ben-balogun-986a4b144/) | **Location:** London, United Kingdom
- Ali Zain (CTO) | [Linkedin profile](https://www.linkedin.com/in/ali-zain-a31a0932/) **does not mention Potentiam** | **Location:** Pakistan
- Kim Barsegyan (Freelance) | [Linkedin profile](https://www.linkedin.com/in/4lutter/) **does not mention Potentiam** | **Location:** Armenia
- Wang Dan - May 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/wang-dan-18671a102) **does not mention Potentiam** | **Location:** China

### Advisors
- Stefano Paluello (Team advisor) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/stefanopaluello/)
- Sean Brizendine (Advisor Board) - May 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/sean-brizendine-a71634b8/)

### [POTENTIAM NETWORK LIMITED](https://beta.companieshouse.gov.uk/company/11098018)            
71-75 Shelton Street          
London WC2H 9JQ        
United Kingdom       
**Incorporated on:** 5 December 2017

- [UK registrar of companies](https://beta.companieshouse.gov.uk/company/11098018)

#### BRITZ N BEATZ LTD
71-75 Shelton Street          
Covent Garden          
London          
United Kingdom        
WC2H 9JQ          

**Company number:** 10118654    
**Director:** ADETOLA, Olusegun Oluseun      
**Director:** BALOGUN, Ben              
        
- [UK registrar of companies](https://beta.companieshouse.gov.uk/company/10118654)

## Smart contract
- [Contract on github](https://github.com/Potentiam/SmartContract/blob/master/PTM.sol)
- [Deployed - View on etherscan](https://etherscan.io/address/0x9B6337547026342d4C8922537cc23268D1d75284#code)

## Github
- [Potentiam](https://github.com/potentiam)

## Product
- No product

## Vesting
- ~~50 % of team token locked for a year. Not coded in smart contract.~~
- **Update: (10 dec 2017)** 2 year vesting for team tokens, coded in the smart contract.

### Screenshot taken before Potentiam registered UK company
![chat-1](https://user-images.githubusercontent.com/32852887/33580665-54c0dc98-d94e-11e7-90f5-b3bfd476c576.png)
![chat-2](https://user-images.githubusercontent.com/32852887/33580674-5f2efad4-d94e-11e7-8fb5-09bde428b14f.png)
![chat-3](https://user-images.githubusercontent.com/32852887/33580682-66797a1c-d94e-11e7-90a0-95d1b00d5336.png)

**Comment by Jarray01** [comment]
a design is a 
![plagiarism](https://user-images.githubusercontent.com/17760824/35397781-9f5bba78-01f0-11e8-93bb-57635da772f4.png)
copy/pas from Blockv

**Comment by Jarray01** [comment]
design is a copy/past from Blockv 
![plagiarism](https://user-images.githubusercontent.com/17760824/35397781-9f5bba78-01f0-11e8-93bb-57635da772f4.png)
