### ISSUE TITLE
Announcement from the IcoCheck team

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#131]
### We are glad to announce that development of the new version of the website [IcoCheck](https://icocheck.io/) 2.0 is about to start. 
This new version will improve user experience, as well as add features such as:  

- Tags on the main page, to allow users to get more information at a glance
  
- Short explanations for each item we check, to allow users - especially less experienced ones - to understand the importance of having a registered company or a proper vesting schedule
  
- Interface improvements, to make navigating the webpage an easier experience
  
As always, don't hesitate to let us know how you would like us improve our site, by writing to us on our official social media channels: 

- [Twitter](https://twitter.com/icocheckio)  
- [Telegram](https://t.me/checkico)

**Comment by Empresaria** [comment]
Thank you!

**Comment by DasCryptoEngineer** [comment]
Great stuff. Thanks guys for your hard work. It is appreciated!
