### ISSUE TITLE
HAT.Exchange formerly Hawala.Today - Due Diligence

### ISSUE THREAD

**Issue by cryptocheckr** [ico-check/ico-check#136]
# ‼️ Update: Kucoin and IDEX delisted HAT token ‼️

# No ICO but an airdrop instead.

[![telegram-chat](https://user-images.githubusercontent.com/32852887/38760208-611df88a-3f7a-11e8-83bc-ca7ba4076a10.png)](https://t.me/hat_public)

# [HAT.Exchange](https://hat.exchange) (formerly Hawala.Today, HAT)

## [Bynary](http://bynaryinc.com)

![](https://image.ibb.co/hx0m1d/image.png)
![](https://image.ibb.co/k1ef4d/image.png)

- Bynary, Inc. is supposedly the holding company of HAT.Exchange.

# Team

**Refused to provide any LinkedIn profiles** for the _"team"_ members instead preferring absurd excuses and non-answers:

![](https://image.ibb.co/j4Vrhy/image.png)
![](https://image.ibb.co/m4tGFJ/image.png)
![](https://image.ibb.co/dOyf9d/image.png)

Googling around, you can find _some_ of them

## Zeeshan Masood (CEO/CTO) | [LinkedIn](https://www.linkedin.com/in/zeeshan-t-36b3a812/)

From [CorporationWiki](https://www.corporationwiki.com/p/31oc38/zeeshan-taj):

![](https://image.ibb.co/ku0t9o/image.png)

LinkedIn profile in April left much to be desired:
![](https://image.ibb.co/eXMdaT/image.png)
![](https://image.ibb.co/fzMTaT/image.png)

It's recently been suspiciously spruced up with debatable info:
![](https://image.ibb.co/cJGi9o/image.png)
![](https://image.ibb.co/hnUyaT/image.png)
![](https://image.ibb.co/kR9Lpo/image.png)

He claims to have been CEO of Bynary since **March 2017** even though it didn't exist until **March 2018** and also claims he was working for TekSystems at the same time he was supposedly working for Reach Communications Inc. as seen in the old profile. Both companies have been contacted to confirm links but are yet to respond. 

As to the part that has been suspiciously left out of the revamped profile, he was the [founder of _ToggleWave_](https://www.corporationwiki.com/p/2fzi7a/togglewave-llc), **a company which was [terminated](https://mycpa.cpa.state.tx.us/coa/coaSearchBtn) by the authorities because [of tax issues](https://www.goamplify.com/blog/business/has-your-business-been-terminated.aspx)**:

![](https://image.ibb.co/hLd3Ey/image.png)

He and Navaid Yusuf were also involved in [WorldTradeCorp](https://www.nvsos.gov/sosentitysearch/CorpDetails.aspx?lx8nvq=uDx%252fPn%252fZmj5UAzcRjpL%252bvA%253d%253d&nt7=0) as Treasurer and President respectively, yet another company that **met its demise at the [hands of the law](https://www.leg.state.nv.us/NAC/NAC-078.html):**

![](https://image.ibb.co/kuOEMd/image.png)

## Navaid Yusuf (Board Director) | **No LinkedIn** ‼️

In addition to the failed WorldTradeCorp above, he was also the president of [Micronix](https://www.nvsos.gov/sosentitysearch/CorpDetails.aspx?lx8nvq=tfl0NnjGQqMeJ6Up39wmrA%253d%253d&nt7=0) which is **yet another company taken down by the law:**

![](https://image.ibb.co/ir611d/image.png)
- Sean Pettersen (Board Director) | [LinkedIn](https://www.linkedin.com/in/sean-p-7b0568a/)
This one went from knowing nothing about blockchain and being just another guy that works at TekSystems:

![](https://image.ibb.co/byRTvJ/image.png)
![](https://image.ibb.co/nxA5aJ/image.png)

...to being the CIO of Bynary and having a "specialization" in blockchain within weeks despite the fact that there's nothing in his prior professional history to support that:

![](https://image.ibb.co/cBzLSy/image.png)
![](https://image.ibb.co/kHHiFJ/image.png)
![](https://image.ibb.co/eTWGZd/image.png)
![](https://image.ibb.co/jZP3Ed/image.png)

## Mario Suwandy (Head of Design) | [LinkedIn](https://www.linkedin.com/in/romariosuwandy/) ‼️
This one claims to have been working for Bynary, Inc. since 2015 even though the company didn't exist until 3 months ago:

![](https://image.ibb.co/h9UZny/image.png)
![](https://image.ibb.co/mJakud/image.png)

![](https://image.ibb.co/f5rmFJ/image.png)

# Advisors

## Rhys Parry | [LinkedIn](https://ca.linkedin.com/in/rhys-parry) - **Does not mention Bynary, Inc. or HAT.Exchange**

Recently, one of the HAT telegram members noticed that Rhys had taken up a job with a potentially competing project:
![](https://image.ibb.co/gw4Mpd/image.png)

Rhys has updated his profile to reflect this new job at VLabs but there is **still nothing** about Bynary:

![](https://image.ibb.co/jpVu9d/image.png)
![](https://image.ibb.co/fYNrpd/image.png)

Even more interestingly, he's now been silently removed from the Bynary site:

![](https://image.ibb.co/hZE1Zy/image.png)

~~Keep in mind that **neither Rhys nor Yash below has ever confirmed any relationship with this project.**~~ Rhys has been contacted to confirm if he ever knew about his position on Bynary's site but is yet to respond.

## Yash Rachakonda | [LinkedIn profile](https://www.linkedin.com/in/yashrachakonda) - **Does not mention Bynary, Inc. or HAT.Exchange**

Curiously, most of the identifiable faces on this page are or were employees of [TekSystems](https://www.teksystems.com/en) which is an IT staffing and services company.

### Updated by admin August 6th 2018: In a linkedin post dated 6th of August 2018 Yash Rachakonda confirmed that he has been involved as an advisor to HAT.EXCHANGE

![yash-rachakonda-confirms](https://user-images.githubusercontent.com/32852887/43747273-99d63714-999d-11e8-831e-3abb4705c83a.png)

>>I have been involved as an advisor on a very interesting product which will make crypto currencies accessible to virtually everyone.

## PR / Marketing Advisor (Telegram display name: Edward IV) is anonymous - His identity is unknwon. ‼️

# Company

Claimed to be a company since last year:

![](https://image.ibb.co/mE0Xpd/image.png) 
![](https://image.ibb.co/hLk2pd/image.png)
![](https://image.ibb.co/hb57Ny/image.png)

But actually incorporated, not their actual company, but a whole new holding company 3 months ago:

![](https://image.ibb.co/gpq7Ny/image.png)

**Bynary, Inc.**

**File Number:** 6805550
**Incorporation Date:** 3 March 2018
**Entity Kind:** Corporation
**Entity Type:** General
**Residency:** Domestic
**State:** Delaware

**Office Address:** N/A

**Registered Agent Information**

**Name:** Cogency Global Inc.
**Address:** 850 New Burton Road Suite 201
**City:** Dover
**County:** Kent
**State:** DE 19904
**Phone:** 302-734-1450

**Source:** [Delaware entity search](https://icis.corp.delaware.gov/ecorp/entitysearch/NameSearch.aspx)

# Smart contract

https://etherscan.io/address/0x9002d4485b7594e3e850f0a206713b305113f69e#code

# Github

Closed source with no intention of open-sourcing:

![](https://image.ibb.co/mpEyco/image.png)

## Update: August 2nd 2018 - PR / Marketing Advisor (Telegram display name: Edward IV - Anonymous - His identity is unknwon) shared the Hat exchange github link

- [adminhatexchange](https://github.com/adminhatexchange)

![github](https://user-images.githubusercontent.com/32852887/43688161-c9613f84-9898-11e8-9840-b9960c0db83d.png)

### [SellerEscrow](https://github.com/adminhatexchange/SellerEscrow)

![sellerescrow](https://user-images.githubusercontent.com/32852887/43688251-26a19404-989a-11e8-9603-b35721c9e292.png)

- Empty repository
- 1 contributor [adminhatexchange](https://github.com/adminhatexchange)

### HAT.Exchange_Windows_Build

![windows](https://user-images.githubusercontent.com/32852887/43688260-49ce96a2-989a-11e8-85e2-910a48ad8020.png)

- Last commit 9 May 2018
- 1 contributor [adminhatexchange](https://github.com/adminhatexchange)

### https://github.com/adminhatexchange/HAT.Exchange_Android_Build

![android](https://user-images.githubusercontent.com/32852887/43688265-55cc1a38-989a-11e8-8c5b-02079dd8df47.png)

- Last commit 9 May
- Repo has 2 APK files
- 1 contributor [adminhatexchange](https://github.com/adminhatexchange)

# Product

Actual exchange yet to be released in any form. Various beta clients of a **staking wallet** is available for [multiple platforms](https://hat.exchange/#appdownload).

# Vesting

They claimed tokens were locked under contract numerous times and even held a telegram poll to recalculate the then circulating supply based on that premise:

![](https://image.ibb.co/d6QDvJ/image.png)
![](https://image.ibb.co/gEGpiT/image.png)

But that turned out to be a **bold-faced lie** admitted to by the team after **[this document](http://s000.tinyupload.com/index.php?file_id=69634163807719777121) (pdf)** was released highlighting shady business going on behind the scenes. That forced them to seemingly become more "transparent" without actually being so. 

No tokens were or are locked under contract, the vast majority of the supply currently sits in team-controlled wallets subject to their whims:

![](https://image.ibb.co/fi46xo/image.png)
![](https://image.ibb.co/hWCWV8/image.png)
![](https://image.ibb.co/gycFq8/image.png)
![](https://image.ibb.co/e9qwxo/image.png)

_"bound to what we have stated in the whitepaper"_ while simultaneously admitting to breaking it (and of course calling the document that exposed it "FUD"). Impressive!

As if that wasn't bad enough, they continue to mislead naive token holders by claiming, in their new whitepaper, that tokens will be _"unlocked"_ at some future time even though they were never locked in the first place:

![](https://image.ibb.co/eRkkq8/image.png)

# Additional info

**Lying About Token Distribution**

Directly following their lie about locked tokens, they also lied about airdropping and paying bounties to the tune of 1M+ HAT tokens. Numerous times they claimed to have airdropped 1M HAT **and** extra for bounties:

![](https://image.ibb.co/nQZdA8/image.png)
![](https://image.ibb.co/c5GYA8/image.png)
![](https://image.ibb.co/dqKpHo/image.png)
![](https://image.ibb.co/cH8Yco/image.png)

But after that document came out, it turned out to be yet another **bold-faced lie** which they tried to excuse with silly accusations, handwaves and back-pedaling on earlier statements:

![](https://image.ibb.co/b6QX3T/image.png)

Clear contradiction pointed out when they attempted to rewrite history:
![](https://image.ibb.co/kjdPHo/image.png)
![](https://image.ibb.co/msY8co/image.png)

As should be clear by now, this project and its administrators/team have a penchant for back-pedaling on their earlier statements when trying to get out of a hard spot. This is just the beginning.

**Lying About Applying for an MSB License**

Prior to the release of the document and the events thereafter, they claimed they were anonymous because of their pending MSB License which was supposedly applied for in November, 2017:

![](https://image.ibb.co/bFmdco/image.png)
![](https://image.ibb.co/h7nvOT/image.png)

You guessed it, that was yet **another lie**. They never applied for an MSB license, how could they? There was no company up until 2 months ago (which coincidentally was the 6th month since they supposedly applied)! While you can easily find the MSB applications of somewhat similar exchanges like Coinbase, Gemini, Robinhood and even the obscure CryptocurrencyMarket at [FINCEN's MSB Registrant Search Database](https://www.fincen.gov/msb-registrant-search):

![](https://image.ibb.co/kSXYQy/image.png)
![](https://image.ibb.co/e9cNJJ/image.png)
![](https://image.ibb.co/e50EXd/image.png)
![](https://image.ibb.co/j51A5y/image.png)

There is absolutely **nothing** for Bynary, Hawala.Today or Hat.Exchange:

![](https://image.ibb.co/cFVpXd/image.png)
![](https://image.ibb.co/jWvHJJ/image.png)
![](https://image.ibb.co/fKTnJJ/image.png)

Searching by state in Texas (where they were supposedly based) and Delaware (where the "holding" company, Bynary, was incorporated) instead of company name also comes up empty. If you're thinking it's not showing up because they've not yet been granted the license then see [FINCEN's FAQ](https://www.fincen.gov/sites/default/files/shared/GeneralFAQ.pdf) (pdf) that suggests otherwise:

![](https://image.ibb.co/gA1dfJ/image.png)

The only reason there's nothing about Hawala.Today, Hat.Exchange or Bynary in FINCEN's MSB database is simple: they've not even bothered to file for an MSB license. They continue to mislead token holders and any request for information of said license and other info is met with pseudo-legalistic hand-waves, embarrassing vagueness, sidestepping of the question and even asking you to go through KYC (yes, you read that right) administered by a team whose identities are in question:

![](https://image.ibb.co/mSCtvJ/image.png)
![](https://image.ibb.co/d1Vk9d/image.png)
![](https://image.ibb.co/kn99iT/image.png)
![](https://image.ibb.co/nNy5q8/image.png)
![](https://image.ibb.co/mrBKHo/image.png)

---
_**Tangent:** Anyone who has followed this project long enough knows for a fact that the MSB was the de facto excuse as to why the devs were anonymous, for example:
![](https://image.ibb.co/hMwYSo/image.png)
Basically yet another attempt at rewriting history_

---
![](https://image.ibb.co/cXVUHo/image.png)

If that's not enough, then their recent backpedaling on the MSB requirement in [this newsletter](https://hat.exchange/announcement/newsletter_02_06052018/) should be enough: 

![](https://image.ibb.co/iJJGQ8/image.png)

The author of that newsletter would have us believe all references to an MSB license prior to this point were "unofficial", simply "sharing thinking" and misinterpreted as "set in stone" by the community. All the screenshots above show the disingenuity of such an embarrassing claim, it would take serious mental gymnastics to translate the above comments in the screenshots as anything but official or simply "sharing thinking". Here's more, by the **second in command**:

![](https://image.ibb.co/kPEEYT/image.png)
![](https://image.ibb.co/iOGuYT/image.png)
![](https://image.ibb.co/cFJf7o/image.png)
![](https://image.ibb.co/k4pHL8/image.png)
![](https://image.ibb.co/m4Zj08/image.png)
![](https://image.ibb.co/fKCRDT/image.png)

_"need", "needed", "require", "waiting for", "like Coinbase [which has an MSB]"..._ if such comments are to be interpreted as _"unofficial"_, "sharing thinking", "[not] set in stone", what on earth _is_ official?

The next paragraph in the newsletter says:

![](https://image.ibb.co/fHZLJT/image.png)

But not too long ago it was:
![](https://image.ibb.co/m4Zj08/image.png)

Their whitepaper and comments in the telegram channel advertise a "wallet" to store and link your bank account/credit cards to. The previous whitepaper even going as far as promising insurance for those funds (that has of course been magicked away in the latest version):

![](https://image.ibb.co/kgMHyT/image.png)

If the _"these funds do not belong to Hawala.Today"_ make you think _"aha! It's different"_, realize that's exactly the same lingo [Coinbase employs](https://support.coinbase.com/customer/portal/articles/1662379-how-is-coinbase-insured-):

![](https://image.ibb.co/dXkz08/image.png)

But there really is no shortage of complaints about Coinbase [blocking](https://news.bitcoin.com/coinbase-withdrawal-delays-leave-users-frustrated-crying-foul/) [people](https://www.reddit.com/r/CoinBase/comments/7jc2ji/how_much_of_your_money_is_coinbase_holding_hostage/) from [accessing](https://www.reddit.com/r/CoinBase/comments/8a399v/still_cant_withdraw_my_funds/) [those](https://www.reddit.com/r/CoinBase/comments/7kd4xy/coinbase_holding_my_funds/) [funds](https://www.reddit.com/r/CoinBase/comments/7hrvby/coinbase_holding_my_money_hostage/) they supposedly don't own, so much so that they're [being sued](https://mashable.com/2018/06/20/sec-coinbase-complaints-fraud/). But **at least they have an MSB license.** Does the **second in command** offer any explanation as to why this 180 degree change occured? Perhaps an admission that they've never actually bothered to apply for an MSB? Nope:

![](https://image.ibb.co/dTGmHy/image.png)

From _"we **need** the license [...] we're on schedule to get the MSB license"_ to _"we dont need license for [fiat] now"_. I am _sure_ the authorities are going to [take very kindly with an MSB claiming it's not](https://www.ccn.com/another-la-trader-faces-jail-term-for-trading-on-localbitcoins/) using vague arguments that don't particularly line up with reality.

**Lying About Holding Trademarks to Hawala.Today & Hawala Token, and the Company's Location**

![](https://image.ibb.co/nCnQLy/image.png)

That's what you would've been greeted with if you scrolled to the bottom of [their previous and now offline hawala.today site](http://web.archive.org/web/20180202233658/https://www.hawala.today/). Of course it was yet another lie exposed in the document mentioned earlier. Right off the bat there is and was never any _Hawala.Today_ company to which such trademark rights would've been granted. There's no trademarks for either of those brands in the [USPTO database](https://www.uspto.gov/trademarks-application-process/search-trademark-database). This was, at least one version, of the excuse the second in command gave when asked about it:

![](https://image.ibb.co/caFMV8/image.png)

Laced with three lies:

- there was a Hawala.Today company as at February 13th, a lie as has been established above
- said company was not in the US but actually in Estonia/Singapore/Switzerland, another lie
- the trademarks are actually held there, yet another lie

There's no trademark for either hawala.today or hawala token in the [Estonian database](http://andmebaas.epa.ee/avalik/#/trademarks), [general Swiss database](http://www.wipo.int/madrid/monitor/en/), [Singaporean database](https://www.ip2.sg/RPS/WP/CM/SearchSimpleP.aspx?SearchCategory=TM) or [the entirety of Europe for that matter](https://euipo.europa.eu/eSearch/).

**Other Fumbles**

- Banning People For Pointing Out Blatant Contradictions

Then:
![](https://image.ibb.co/dpKqaJ/image.png)
![](https://image.ibb.co/f6M3vJ/image.png)
Now:
![](https://image.ibb.co/m6YcNy/image.png)

---
_**Tangent:** There is not **a single shred of evidence of a VC backing this company, not one**. Following the document that was released (linked earlier), you can see the _"funds"_ actually came from people buying their tokens on EtherDelta and IDEX_

---
Pointing it out:
![](https://image.ibb.co/dmdasy/image.png)
![](https://image.ibb.co/hCqk9d/image.png)

Banned:
![](https://image.ibb.co/g191hy/image.png)

- Claiming to be fully compliant with all the laws

Then:
![](https://image.ibb.co/kPjOEd/image.png)
Now:
![](https://image.ibb.co/jm4jLJ/image.png)

Their reason for the change? FINRA
![](https://image.ibb.co/cXba5y/image.png)

This became particularly problematic when people had their tokens locked in their smart contract with no recourse for action while they were waiting for the beta staking wallet to be released which would then require KYC. Instructions to directly unlock them using the smart contract was discouraged by the team:

![](https://image.ibb.co/joooKd/image.png)
![](https://image.ibb.co/d0yNed/image.png)
![](https://image.ibb.co/k9miKd/image.png)
![](https://image.ibb.co/nuP9sy/image.png)

![](https://image.ibb.co/mMB3sd/image.png)
![](https://image.ibb.co/mzaUXd/image.png)

**They effectively banned** a user for trying to help one such individual out because it's apparently _"illegal"_ to interact directly with their smart contracts:

![](https://image.ibb.co/egu77J/image.png)

## Edited by admin on 26 Jul 2018: 3 private conversation screenshots of PR / Marketing Advisor (Telegram display name: Edward IV - Anonymous - His identity is unknwon) removed

A company that claims to be _"globally"_ compliant makes the absurd claim that PII is not _"valuable"_, processes people's very personal and [**valuable data**](https://medium.com/algebraix-data/how-much-is-your-data-worth-c28488a5812e) [**without a DPO**](https://digitalguardian.com/blog/what-data-protection-officer-dpo-learn-about-new-role-required-gdpr-compliance) data and expects to retain the data indefinitely. Their second in command didn't even realize a name was [PII](https://en.wikipedia.org/wiki/Personally_identifiable_information):

![](https://image.ibb.co/hs6RHJ/image.png)
![](https://image.ibb.co/jmv8Wd/image.png)

The GDPR regulators will surely [love that](https://www.gdpreu.org/compliance/fines-and-penalties/).

**The "Advisor"**

The _"yawn"_ above is by the advisor, whether of Bynary, HATE or both going he can't seem to get straight. He also doesn't seem sure if he's on or off the team but as earlier screenshots show, he sure loves to attack people in public and especially in PMs:

![](https://image.ibb.co/mH9tq8/image.png)
![](https://image.ibb.co/f2dsiT/image.png)
![](https://image.ibb.co/kj8siT/image.png)
![](https://image.ibb.co/cxodq8/image.png)

## Edited by admin on 26 Jul 2018: 5 private conversation screenshots of PR / Marketing Advisor (Telegram display name: Edward IV - Anonymous - His identity is unknwon) removed

# Flags

**Real Team:** ➖ More proof needed to verify all team members. Core team member / founder must be director of the company. Omer Masood - **No proof that he exists**. Navaid Yusuf - **No LinkedIn**. PR / Marketing Advisor (Telegram display name: Edward IV) is anonymous - His identity is unknwon. ‼️    
**Github:** ✅ Update August 2nd 2018 - PR / Marketing Advisor (Telegram display name: Edward IV - Anonymous - His identity is unknwon) shared the Hat exchange github link    
**Smart Contract:** ✅    
**Working Product:** ➖ Staking wallet only, actual exchange yet to launch     
**Vesting:** ❌ Lied about token lock and continue to mislead token holders     
**Have a Company:** ❌ No team member is listed as the director of Bynary, Inc.     
**Transparent:** ❌

**Comment by emdavis7** [comment]
thanks for this

**Comment by stonesy88** [comment]
@cryptocheckr @icochecker  Those screenshots are of my personal conversations, I gave permission for them to be posted pubically.

**Comment by hat-exchange** [comment]
@cryptochecker @icochecker @stonesy88

HAT.Exchange communicated with the page admin and admin agreed to remove private and personal communications w one of our team members. The private chats were conducted in confidence with the expectation of privacy, and we do not grant permission for them to be made public. Private chats do not necessarily reflect the views of HAT.Exchange. 

We continue to stand by our public statements (including in the screenshots of our public chat) and will be clarifying why certain statements were made in the past, with a detailed explanation about how and why certain things changed.

**Comment by stonesy88** [comment]
You expect privacy? Given that your company has leaked my personal data on your Telegram and other Telegrams on at least 5 occasions? You have no clue how to conduct business, no understanding or respect of Data Protection laws in jurisdictions which your users reside.

**Comment by hat-exchange** [comment]
Yash Rachakonda confirms advisorship with HAT.Exchange. @icochecker: Please edit the post accordingly:

https://www.linkedin.com/feed/update/urn:li:activity:6432267187032981504/

**Comment by hat-exchange** [comment]
Rhys Parry was kind of enough to upload a video confirming his relationship with HAT.Exchange. @icochecker - please update and remove all false and inaccurate claims:

https://www.youtube.com/watch?v=IttjnLRVudU

**Comment by icochecker** [comment]
@hat-exchange 

Regarding Rhys Parry the information was accurate at the time of posting.

I invite you to read the comment again:

> Keep in mind that neither Rhys nor Yash below has ever confirmed any relationship with this project. Rhys has been contacted to confirm if he ever knew about his position on Bynary's site but is yet to respond.

**Comment by hat-exchange** [comment]
@icochecker - sorry, but they both just confirmed either an ongoing relationship (Yash) and a past relationship before moving on (Rhys).  Yash’s LInkedIn now refers to Hat.Exchange, so the section of the review claiming he “does not mention the company” is now demonstrably inaccurate and proven to be false. We are expecting the false claim to be removed.

Secondly, Rhys was an early advisor but moved on to another project. He recorded a video confirming his earlier relationship with our company, which is the same as responding to the confirmation request the author of this review claims to have made.  He confirmed the relationship.  The claim made in the review is now shown to be false and we expect it to be removed.

Finally, if you’re going to use the weak argument that “the information was true at the time it was posted” to get around editing the post in the face of new and more accurate information, then HAT.Exchange can just as easily (and fully intends to) argue that the communications in regard to MSB licenses were “true at the time the posts were made” (because they were).  The company began the MSB application process for 10 separate U.S. States, and then modified their business model so that MSB licenses would no longer be required by law.  We have the documentation that the legal team began work on the MSB licenses for those 10 States. 

ICO Check seems perfectly comfortable allowing claims with no evidence whatsoever to remain. There is no evidence that the team “lied” about MSB licenses.  The information was accurate at the time it was communicated.

**Comment by hat-exchange** [comment]
@icocheck - let it also be noted, for the record, that one of ICO Check’s admins banned me for unspecified reasons with no warning or opportunity to respond (I am the representative of HAT.Exchange tasked with responding to this issue). We plan to write our own review of ICO Check in an official statement to our large community, and ICO Check will deservedly be receiving a large red tag for “CENSORSHIP.”

**Comment by cryptocheckr** [comment]
@hat-exchange 
>sorry, but they both **just confirmed** either an ongoing relationship (Yash) or a past relationship before moving on (Rhys). Yash’s LInkedIn now refers to Hat.Exchange, so the section of the review claiming he “does not mention the company” is **now demonstrably inaccurate and proven to be false. We are expecting the false claim to be removed**

Clearly English is not your first language or you're so incredibly daft you don't realize the obvious contradiction in that comment. It was **just** confirmed, the comment is a **demonstrable accurate piece of history**. 

>Finally, if you’re going to use the weak argument that “the information was true at the time it was posted” to get around editing the post in the face of new and more accurate information, **then HAT.Exchange can just as easily (and fully intends to) argue that the communications in regard to MSB licenses were “true at the time the posts were made” (because they were). The company began the MSB application process for 10 separate U.S. States, and then modified their business model so that MSB licenses would no longer be required by law. We have the documentation that the legal team began work on the MSB licenses for those 10 States.**

Provide said documentation dating back to November, 2017 ( the time the first claim about the MSB was made) and you'll be taken seriously. Until then this inane analogy holds no water.

>ICO Check seems perfectly comfortable allowing damaging and untrue claims with no evidence whatsoever to remain. There is no evidence that the team “lied” about MSB licenses. The information was accurate at the time it was communicated.

Your inability to comprehend the English language and desperate grasping at straws does not make historical truths _"untrue"_. It certainly make the demonstrable lies about your MSB license situation go away but hey, don't let that stop you from grasping at said straws.

**Comment by hat-exchange** [comment]
@icochecker - Your Telegram chat admins are perfectly fine with allowing your members to post private information, such as bank accounts, phone numbers, and names and addresses, if the targets are members of the crypto project teams your group has decided to “bash.” Edward IV (anonymous and staying that way!) posted the public LinkedIn profile of the member of your group who has harassed, cyber stalked, trolled, and threatened our team members and their past employers for months. This individual posted his full name and home address right into your Public Telegram chat.  No rules were broken. We’re done here.

**Comment by hat-exchange** [comment]
@cryptocheckr - we’re done responding and providing privileged information to this unprofessional, disreputable, hack of a project.

**Comment by cryptocheckr** [comment]
@hat-exchange 
>**This individual posted his full name and home address right into your Public Telegram chat.** No rules were broken. We’re done here.

_After_ you posted it, amirite? 

>we’re done responding and providing privileged information to this unprofessional, disreputable, hack of a project.

Lol, no more pithy word salads as a _"response"_? Or have you run out of words to string together hoping the shear size of it despite the meaningless of the content will convince onlookers? You did get one thing right although presented as a [projection](https://en.wikipedia.org/wiki/Psychological_projection) - HAT is a demonstrably unprofessional, disreputable, hack of a project. Watching you guys try to get rid of the evidence of such unprofessional treatment of people by your "advisor" has been nothing short of amusing.

**Comment by icochecker** [comment]
@hat-exchange information that breaks the rules gets deleted. Let me remind you that you doxxed a user in the icocheck group by publicly revealing his identity. I invite you to read the group chat rules once again and kindly ask you to behave properly.

**Comment by icochecker** [comment]
@hat-exchange Yash Rachakonda is using the past tense by saying that he has been involved as an advisor but is he still involved today? 🤔  [Bynaryinc.com](http://bynaryinc.com) still lists him as an advisor.

>I have been involved as an advisor

![yash-rachakonda-confirms-label](https://user-images.githubusercontent.com/32852887/43748843-7a50c540-99a6-11e8-849a-e5c91f84c130.png)

**Comment by icochecker** [comment]
Issue is locked until further notice to prevent spam and off topic conversations.

**Comment by alphonsoespinoza** [comment]
# Here are the images OP deleted from the first post

### **Images leaked on social networks and publicly available

>They effectively banned a user for trying to help one such individual out because it's apparently "illegal" to interact directly with their smart contracts:

>**Edited by admin on 26 Jul 2018: 3 private conversation screenshots of PR / Marketing Advisor (Telegram display name: Edward IV - Anonymous - His identity is unknwon) removed**

![screenshot](https://telegra.ph/file/1cb09f9a39ffa9972b7f2.png)

![screenshot](https://telegra.ph/file/4c01f55ece51ba74c7c65.png)

![screenshot](https://telegra.ph/file/ce14e1c086660e6c96988.png)

>#The "Advisor"

>The "yawn" above is by the advisor, whether of Bynary, HATE or both going he can't seem to get straight. He also doesn't seem sure if he's on or off the team but as earlier screenshots show, he sure loves to attack people in public and especially in PMs:

>**Edited by admin on 26 Jul 2018: 5 private conversation screenshots of PR / Marketing Advisor (Telegram display name: Edward IV - Anonymous - His identity is unknwon) removed**

![screenshot](https://telegra.ph/file/b4f53dd860e09812fc49c.png)

![screenshot](https://telegra.ph/file/d0082d68ebb2b7ad9f51d.png)

![screenshot](https://telegra.ph/file/aa60ba3aaacd4482f40e7.png)

![screenshot](https://telegra.ph/file/42014108d2db53f8cb176.png)

![screenshot](https://telegra.ph/file/efab1883470dde3b83e6f.png)

# Source (publicly available information): [https://telegra.ph/WARNING-HAT-EXCHANGE-LEAKED-10-03](https://telegra.ph/WARNING-HAT-EXCHANGE-LEAKED-10-03)

# ⚠️ To report Hat-Exchange to the SEC:
## [https://www.sec.gov/tcr](https://www.sec.gov/tcr)
