### ISSUE TITLE
Chia Network - Due diligence

### ISSUE THREAD

**Issue by goktugyil** [ico-check/ico-check#137]
Chia Network
https://chia.net/

**Comment by icochecker** [comment]
# [Chia Network](https://chia.net/)

# Discussion
>Discussion about this library and other Chia related development is on Keybase. [Install Keybase](https://keybase.io/download), and run the following to join the Chia public channels:

```
keybase team request-access chia_network
```

# Team
## Bram Cohen
### Chia Network (Founder & CEO) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/cohenbram/) | [Github](https://github.com/bramcohen) | [Twitter](https://twitter.com/bramcohen)
 - [BitTorrent](http://www.bittorrent.com) | Owner - Feb 2001 - Present

### Media reports that Tron acquired BitTorrent

Source: [Engadget](https://www.engadget.com/2018/07/25/blockchain-company-tron-buys-bittorrent/) | [TechCrunch](https://techcrunch.com/2018/07/24/blockchain-startup-tron-closes-bittorrent-acquisition/)

### [Acquisiton confirmed by BitTorrent Inc. on Twitter](https://twitter.com/BitTorrent/status/1021629735258841088)
![bitorrent-tron](https://user-images.githubusercontent.com/32852887/44312317-07c6bc00-a3ab-11e8-8b89-b66ad489638a.png)

### [Acquisiton confirmed by Tron Foundation on Twitter](https://twitter.com/Tronfoundation/status/1021815562140176385)
![justin-sun-bittorent](https://user-images.githubusercontent.com/32852887/44312322-1319e780-a3ab-11e8-9101-4c80e21f6ea7.png)

### Torrentfreak.com reached out to Bram Cohen:
>Cohen hasn’t said anything in public about the TRON deal, and isn’t very talkative, but when we reached out using an alternative email the response was clear.

> “I have no involvement with Tron,” Cohen noted.
 
> We followed up by asking whether this means that he no longer has an official role at BitTorrent Inc. The response was again short but clear.

> “That is correct,” he said.

[Source: TorrentFreak](https://torrentfreak.com/bittorrent-inventor-bram-cohen-leaves-bittorrent-behind-180819/)

## Ryan Singer
### Chia Network (Co-founder) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/ryans/)
 - [Neighborly](https://neighborly.com) | Managing Director - Mar 2017 - Jan 2018
 - [Blockchain Health Co](https://blockchainhealth.co/) | CEO - Feb 2016 - May 2017
 - [Blockchain Clearing Corporation](https://www.linkedin.com/company/blockchain-clearing-corporation/) | CEO - Jun 2015 - Mar 2017
 - [CryptoCorp](https://www.linkedin.com/company/cryptocorp/) | Co-Founder - Jan 2014 - Jul 2014
 - [Tradehill, Inc.](https://www.linkedin.com/company/tradehill/) | President & COO - Jul 2012 - Dec 2013

## Alexandra (Ali) Shadle
### Chia Network (Director Of Operations & Corporate Secretary) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/alishadle/)
 - [Honey](http://joinhoney.com) | Product Manager - Mar 2014 - Present

## Mariano Sorgente
### Chia Network (Software Engineer) - Apr 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/mariano-sorgente-a01aa547/)
 - [Token, Inc](https://token.io) | Engineering Lead - Jan 2018 - Apr 2018
 - [Token, Inc](https://token.io) | Software Engineer - Jan 2015 - Jan 2018

# Advisors
- Gene Hoffman | [Linkedin profile](https://www.linkedin.com/in/gehoffman/)

# Investor
- Dovey Wan | [Linkedin profile](https://www.linkedin.com/in/doveywan/)

# Funding Rounds
![chia-network-formd](https://user-images.githubusercontent.com/32852887/44313345-fcc85780-a3bb-11e8-8328-3f2102a3c227.png)

## Equity | [Reg D 506(b)](https://www.sec.gov/Archives/edgar/data/1730166/000173016618000001/xslFormDX01/primary_doc.xml) | $3,375,000 USD | April 18, 2018
### Minimum investment accepted from any outside investor: 32 USD

### Offering and Sales Amounts:
- Total Offering Amount	 $3,375,000 USD	
- Total Amount Sold	$3,375,000 USD
- Total Remaining to be Sold $0 USD

### Total number of investors who already have invested in the offering: 

- [Source Reg D 506(b)](https://www.sec.gov/Archives/edgar/data/1730166/000173016618000003/xslFormDX01/primary_doc.xml)

## Equity | [Reg D 506(b)](https://www.sec.gov/Archives/edgar/data/1730166/000173016618000001/xslFormDX01/primary_doc.xml) | $800,000 USD | April 6, 2018
### Minimum investment accepted from any outside investor: 1 USD

### Offering and Sales Amounts:
- Total Offering Amount	 $100,000,000 US	
- Total Amount Sold	$800,000 USD
- Total Remaining to be Sold $99,200,000 USD

### Total number of investors who already have invested in the offering: 1

- [Source Reg D 506(b)](https://www.sec.gov/Archives/edgar/data/1730166/000173016618000001/xslFormDX01/primary_doc.xml)

# Company 
## CHIA NETWORK INC.
**File Number:** 6498438          
**Incorporation Date / Formation Date:** 1st August 2017          
**Entity Kind:** Corporation           
**Entity Type:** General          
**Residency:** Domestic         
**State:** Delaware     

**New Office Address:**
[44 Montgomery](https://44montgomery.com/) Street 3 Rd Floor 
San Francisco     
CA 94104   
USA

**Old Office Address:**     
650 California St, 7th floor 
San Francisco   
CA 94108  
USA   
        
**Registered Agent Information:**        
THE COMPANY CORPORATION         
251 LITTLE FALLS DRIVE           
WILMINGTON         
New Castle County       
Delaware 19808    
USA     
 
#### Directors
- Bram Cohen | Director, Executive
- Ryan Singer | Director, Executive
        
### [Source: Delaware entity search](https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx)

![chia-delaware](https://user-images.githubusercontent.com/32852887/44312529-b3254000-a3ae-11e8-9c50-b72b7ecf0a2c.png)

![chia-network-california](https://user-images.githubusercontent.com/32852887/44312524-95f07180-a3ae-11e8-8b92-77c68e11a0ae.png)
![chia-network-delaware](https://user-images.githubusercontent.com/32852887/44312525-97ba3500-a3ae-11e8-8b29-11c4d3de7d4f.png)


[Source](https://businesssearch.sos.ca.gov/Document/RetrievePDF?Id=04085463-23271903)

# Smart contract
- N/A

# Github
- [Chia-Network](https://github.com/Chia-Network/)

![chia-network-github](https://user-images.githubusercontent.com/32852887/44312599-b79e2880-a3af-11e8-8efc-94713381c8bd.png)

## 2 repositories
### [bls-signatures](https://github.com/Chia-Network/bls-signatures)

![bls-signatures](https://user-images.githubusercontent.com/32852887/44312626-1c598300-a3b0-11e8-9444-17feb7e90946.png)

- 1 contributor [Mariano Sorgente](https://github.com/mariano54)
- 1 Branch | Master
- [16 Commits](https://github.com/Chia-Network/bls-signatures/graphs/commit-activity)

### [Website](https://github.com/Chia-Network/website)

- 5 Branch
- 31 contributors

# Product
- N/A

# Vesting
- N/A

# Additional info
### Token distribution
- N/A

### Token allocation
- N/A

# Chia Network Flags
**Real Team:** ✅      
**GitHub:** ✅          
**Smart Contract:** - N/A     
**Working Product:** -      
**+2 yr Vesting for team:** -        
**Have a company:** ✅ Co-founder Bram Cohen & Ryan Singer are director of CHIA NETWORK INC.                  
**Transparent:** -          

# IcoCheck.io
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)
- Follow us on [Twitter](https://twitter.com/icocheckio)
