### ISSUE TITLE
Jibrel Network - Due diligence

### ISSUE THREAD

**Issue by pwliwanow** [ico-check/ico-check#14]
Company's website: https://jibrel.network

**Comment by icochecker** [comment]
# [Jibrel Network](https://jibrel.network/) (JNT)

## Team
- Yazan Barghuthi (Co-founder & Project Lead) - 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yazanbarghuthi/)
- Victor Mezrin (Co-founder & Technical Lead) - 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/victor-mezrin-aa823634/)
- Talal Tabbaa (Co-founder & BizDev Lead) - 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/talaltabbaa/)
- Nick Marinin (UX/UI) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/nmarinin/)
- Hamzeh Kolaghassi (Operations Lead) - Sept 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/hamzeh-kolaghassi-61505131/)
- Aleksey Selikhov (Back-end Developer) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/alexey-selikhov-341473b6/) 
- Ivan Violentov (Front-end Developer) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/ivanviolentov/)
- Anna Bordunova (Public Relations) - Sept 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/anna-bordunova-54002467/)
- Rust Khusyainov (Illustrator) **No Linkedin profile**
- Evgeny Erohin (Front-end Developer) **No Linkedin profile**
- Yuriy Homyakov (Back-end Developer) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yuriy-khomyakov-5203a26a/)

### Advisors
- Don Tapscott (Strategy Advisor
CEO of Tapscott Group) | [Linkedin profile](https://www.linkedin.com/in/dontapscott/)
- Ruslan Gavrilyuk (CryptoFinance Advisor
CEO & Founder of TaaS Fund) | [Linkedin profile](https://www.linkedin.com/in/ruslan-gavrilyuk/)
- Abbas Zuaiter (Capital Markets Advisor
Former COO Soros Fund) | [Linkedin profile](https://www.linkedin.com/in/abbas-f-eddy-zuaiter-51832a9)
- Saul Hudson (Communications Advisor
GM at Thomson Reuters) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/saul-hudson-2ab9228/)
- Mohammad Al Sehli (MENA Advisor
CEO & Founder of Arabian Chain) | [Linkedin profile](https://www.linkedin.com/in/mohammed-alsehli-7520a626/)
- Dr. Moe Levin (Public Sector Advisor
CEO of Keynote) | [Linkedin profile](https://www.linkedin.com/in/moelevin)

## Company
### [Jibrel AG](https://www.shab.ch/shabforms/servlet/Search/3752115.pdf)
Baarerstrasse 10
Zug,  6302
Switzerland    
**VATIN:** CHE-339.807.676
**Registered on:** 14 Sept 2017
           
- [Swiss Official Gazette of Commerce](https://www.shab.ch/shabforms/COMMON/search/searchresult.jsf)

### Qubist Labs Inc (US)           
**File Number:** 6414448                   
**Incorporation Date / Formation Date:** 17 May 2017           
**Entity Kind:** Corporation            
**Entity Type:** General     
**Residency:** Domestic      
**State:** DELAWARE            

- [Delaware entity search](https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx)  
        
## Smart contract
- [Contract on github]()
- [Deployed - View on etherscan]()

## Github
- [Jibrel Network](https://github.com/jibrelnetwork/jwallet-web)

## Product
- [jWallet](https://jwallet.network/jwallet)

## Vesting
- **Team - 5 year Vesting (2 Year Cliff)** - Tokens will get locked with Jibrel DAO and vest
- Advisors - 2 Year Vesting (1 Year cliff)

## Other info
- **Founder has been completely transparent during the whole process**
