### ISSUE TITLE
Mochimo - Due diligence

### ISSUE THREAD

**Issue by angryolk** [ico-check/ico-check#144]
# [Mochimo](https://mochimo.org/)

## Team
*Here list team members with links to their LinkedIn accounts in here*
https://mochimo.org/meet-the-team/

### Advisors
`Jeff Levin-Professional ServicesDevelopment-Program ManageratJuniperNetwork, assists with defining service offerings.`

`Alexei Marchenkov-CEO of Bleximo-provides guidance on Fintech startups, emerging quantum computing technology.`

`Stephen Sammut-Venture Capitalist-Professor at the Wharton School of Business, provides guidance on VC funding.`

`Helen Smith -Copy Editor -responsible for final approval of all published content/materials.`

## Company
*The intellectual property (IP) behind the Mochimo Cryptocurrency Engine and Mochimo coin is owned by Adequate Systems, LLC, a blockchain-as-a-service company established by Matt Zweil, Mochimo’s Founder and Lead Architect. A quick google search shows trademarks regarding the propriety tech in Mochimo registered to the company*

## Smart contract
*Mochimo does not use smart contracts*

## Github
*https://github.com/mochimodev/mochimo*

## Product
*Here put link to the product if exists and attach screenshots.*

## Vesting
*Here put information where vesting information was found and attach screenshots.*

## Additional info
**Proof of Review**
*https://www.proofofreview.com/wp-content/uploads/2018/12/Mochimo-v1.1-3.pdf*

### Token distribution
*Here put token distribution screenshot or info, with links when possible*

### Token allocation
*Here put token allocation screenshot or info, with links when possible*

**Comment by AcroTiger** [comment]
*Advisors*
```JeffLevin-Professional ServicesDevelopment-Program ManageratJuniperNetwork, assistswithdefiningserviceofferings.
AlexeiMarchenkov-CEO ofBleximo-providesguidanceon Fintechstartups, emergingquantumcomputingtechnology.
StephenSammut-Venture Capitalist-ProfessorattheWhartonSchoolofBusiness, providesguidanceon VC funding.
Helen Smith -Copy Editor -responsibleforfinalapprovalofallpublishedcontent/materials.```

**Company**
```The intellectual property (IP) behind the Mochimo Cryptocurrency Engine and Mochimo coin is owned by Adequate Systems, LLC, a blockchain-as-a-service company established by Matt Zweil, Mochimo’s Founder and Lead Architect. A quick google search shows trademarks regarding the propriety tech in Mochimo registered to the company.```

*Smart Contract*
Mochimo does not use smart contracts

**Proof of Review**
https://www.proofofreview.com/wp-content/uploads/2018/12/Mochimo-v1.1-3.pdf
