### ISSUE TITLE
INS - Due diligence

### ISSUE THREAD

**Issue by pwliwanow** [ico-check/ico-check#15]
Company's website: https://ins.world/

**Comment by icochecker** [comment]
# [INS](https://ins.world/)

## Team
- Peter Fedchenkov (Co-founder) - May 2017 - Present | [LinkedIn profile](https://www.linkedin.com/in/pfedchenkov/)
- Dmitry Zhulin (Co-founder) - May 2017 - Present | [LinkedIn profile](https://www.linkedin.com/in/dmitryzhulin/)
- Dmitry Khovratovich (Blockchain & Smart Contracts) - Sep 2017 - Present | [LinkedIn profile](https://www.linkedin.com/in/khovratovich/)
- Prabhakar Reddy (Asia Expansion) - Aug 2017 - Present | [LinkedIn profile](https://www.linkedin.com/in/prabhakar2reddy/)
- Paul Yakshankin (Technology) - May 2017 - Present | [LinkedIn profile](https://www.linkedin.com/in/paulyakshankin/)
- Michael Schmidt (US Expansion) - (month unknow) 2017 - Present | [LinkedIn profile](https://www.linkedin.com/in/michaelfschmidt/)
- Fedor Lisitsyn (Manufacturer Relationships) - May 2017 - Present | [LinkedIn profile](https://www.linkedin.com/in/fedor-lisitsyn-83487767/)
- Frank van der Tol (Europe Expansion) - Nov 2017 - Present | [LinkedIn profile](https://www.linkedin.com/in/frankvandertol/)
- Maria Lapuk (PR) - Sep 2017 - Present | [LinkedIn profile](https://www.linkedin.com/in/mariya-lapuk-29508038/)
- Dmitry Gladkov (Legal) - Unknown (INS is not present on his LinkedIn) | [LinkedIn profile](https://www.linkedin.com/in/dmitry-gladkov-5a340b22/)

## INS - Headquarter
INS ECOSYSTEM LTD         
Trinity Chambers         
PO Box 4301           
Road Town         
Tortola           
British Virgin Islands     
**Registration Number** 1955751      

#### [BVI Certificate Verification](http://www.bvifsc.vg/en-gb/divisions/registryofcorporateaffairs/certificateverification.aspx)      
- Certificate ID missing to verify company.

## Smart contract
- [Contract on github](https://github.com/ins-ecosystem/ins_token_smart_contract/blob/0165fbcae4db2b14749c13807cc3241c9a02070c/src/sol/INSToken.sol)
- [Deployed - View on etherscan](https://etherscan.io/address/0x5b2e4a700dfbc560061e957edec8f6eeeb74a320#code)

## Github
- [INS](https://github.com/ins-ecosystem)

## Product
- [Early prototyope](https://beta.ins.world/)

## Vesting
15% of tokens will be distributed to the team. INS ​team's ​tokens ​are ​locked ​for ​2 ​years ​with ​four ​6-month ​vesting ​periods. (Page 36 of the [whitepaper](https://ins.world/INS-ICO-Whitepaper.pdf))

- Vesting not coded in deployed contract. 
- [See on Etherscan](https://etherscan.io/address/0x5b2e4a700dfbc560061e957edec8f6eeeb74a320#code)
