### ISSUE TITLE
Token Desk - Due diligence

### ISSUE THREAD

**Issue by hterrence** [ico-check/ico-check#2]
Company's website: https://www.tokendesk.io

**Comment by icochecker** [comment]
# TokenDesk

## Team
[Tomas Mickauskas](https://www.linkedin.com/in/tomas-mičkauskas-17238b7b/) - Tokendesk advisor was involved in a charity scam.          
#### Source:
- https://www.civilsociety.co.uk/news/high-court-closes-three-companies-involved-in-air-ambulance-collections-scam.html
- https://beta.companieshouse.gov.uk/company/07308919
- https://beta.companieshouse.gov.uk/company/07308919/officers
- [Lithuianian article Part 1](https://www.15min.lt/m/id/verslas/finansai/kriptovaliutos-pionierius-tokendesk-veidas-milijona-svaru-isviliojusio-sukciu-tinklo-dalis-662-871850)
- [Lithuianian article Part 2](https://www.15min.lt/verslas/naujiena/finansai/kriptovaliutu-revoliucija-lietuvoje-pakvipo-melu-arturo-zuoko-sypsenos-nebepakanka-662-869854)
- [Youtube translation of the Lithuanian article part 1](https://www.youtube.com/watch?v=ROspJHEEQPQ)
- [Youtube translation of the Lithuanian article part 2](https://www.youtube.com/watch?v=R6NwITfjQLw)

## Company
[Tokendesk LTD](https://beta.companieshouse.gov.uk/company/10984399)            
3rd Floor 207 Regent Street               
London W1B 3HH              
England             
            
**Incorporated on:** 27 September 2017        
#### Director:
- [Gintaras TAMOSIUNAS](https://beta.companieshouse.gov.uk/officers/kAX7oPPqQLMNTIJi5m90g378hvc/appointments) appointed on 1 November 2017.
- [Stuart Ralph POPPLETON](https://beta.companieshouse.gov.uk/officers/lrUZPitEQMdiU0oB1Nlt76IxQeE/appointments) appointed on 24 October 2017.
- [Renatas MORKUNAS](https://beta.companieshouse.gov.uk/officers/_t_nZjFMHzkHeP1tjdD2vV6GVZM/appointments) appointed on 27 September 2017, resigned on 24 October 2017.

#### Addtional info 
- [Stuart Ralph POPPLETON](https://beta.companieshouse.gov.uk/officers/lrUZPitEQMdiU0oB1Nlt76IxQeE/appointments): Is a current/former director of 318 companies.

## Github
- [Github account](https://github.com/TokenDesk) - Joined October 30

## MVP
- [Alpha added november 14th](https://icos.tokendesk.io)

## Smart contract
- [Contract on Github](https://github.com/TokenDesk/TDS/tree/master/contracts)
- Contract not deployed at start of crowdsale.
- Contract still not deployed as of 15 November 2017.

## Vesting
- No vesting information
