### ISSUE TITLE
Bounty0x - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#20]
# [Bounty0x](https://bounty0x.io/) (STX)

## Team
- Angelo Adam | [Linkedin profile](https://www.linkedin.com/in/angelo-adam-8999045a/) **does not mention bounty0x** | [Github](https://github.com/angeloadam)
- Pascal Thellmann (Co-founder) - Jun 2017 - Present [Linkedin profile](https://www.linkedin.com/in/pascalthellmann/) | [Github](https://github.com/pascalthellmann)
- Deniz Dalkilic (Co-founder) - Oct 2017 - Present [Linkedin profile](https://www.linkedin.com/in/denizdalkilic/) | [Github](https://github.com/dnzdlklc)

### Advisors
- Uwe Thellmann [Linkedin profile](https://www.linkedin.com/in/uwethellmann)
- Cathy Tao [Linkedin profile](https://www.linkedin.com/in/cathy-tao-31411419/)
- Shahaf Bar-Geffen [Linkedin profile](https://www.linkedin.com/in/shahafbg/)
- Sean Hoge [Linkedin profile](https://www.linkedin.com/in/sean-hoge-08b95393/)

#### Bounty0x Ltd.              
5th Floor Genesis Building          
Genesis Close            
Grand Cayman KY1-1106                

**Authorisation Code:** B99855005245        
**Entity File Number:** AD-327205   

![cert-validate](https://user-images.githubusercontent.com/32852887/33948880-5b28d528-e028-11e7-8a4a-a0566e4aa8f3.png)

- [Cayman Islands Online General Registry](https://www.registry.gov.ky/verify/)

## Github
- [bounty0x](https://github.com/bounty0x/)

## Product
- [Alpha](https://alpha.bounty0x.io/)

## Smart contract
- [Crowdsale on github](https://github.com/bounty0x/Bounty0xCrowdsale/tree/master/contracts)
- [Presale contract on github](https://github.com/bounty0x/PreSale/blob/master/contracts/Bounty0xPreSale.sol)
- [PreSale contract deployed - View on etherscan](https://etherscan.io/address/0x998c31dbad9567df0ddda990c0df620b79f559ea#code)

## Vesting
- **30% of tokens for founding team, vested over 18 month**
- **3% of tokens for advisors, vested over 6 month**

![vesting-chat](https://user-images.githubusercontent.com/32852887/33948895-65f2d8a0-e028-11e7-8836-054189a075ba.png)

![advisor-token](https://user-images.githubusercontent.com/32852887/33948901-69d2183c-e028-11e7-9a46-bf8c27dd35e5.png)

![vesting-pie](https://user-images.githubusercontent.com/32852887/33948905-6ebe64ea-e028-11e7-97d4-8f893fd479ac.png)

**Comment by agentbutlr** [comment]
Why is there a warning label for this one. Just trying to understand the labelling system.

**Comment by icochecker** [comment]
> Why is there a warning label for this one. Just trying to understand the labelling system.
It does not meet [icocheck.io](https://icocheck.io) requirements.

![icocheck-checkmark](https://user-images.githubusercontent.com/32852887/34085743-22f7d18e-e395-11e7-9ed4-21dac344f367.png)
![icocheck-fields](https://user-images.githubusercontent.com/32852887/34085745-24e27f44-e395-11e7-8487-d30a7679dfc0.png)


If one field has an "x mark", issue will have a warning label 

Team tokens vesting schedule is 18month. [icocheck.io](https://icocheck.io) requires a min of 24 month.

**Comment by alexanderisora** [comment]
Hello.

What is "vesting" and "cliff" and what are the most common/best practices for making it? 

Thanks.

**Comment by icochecker** [comment]
@alexanderisora 
**Vesting schedule = Token lock**
Example team tokens locked for X years. Team can't sell all their tokens before X years.
- This prevents Teams from dumping their tokens.
- It's the incentive for them to work

1 year cliff. Means that tokens won't vest during the 1st year. If a team member leaves before the 1st year he gets nothing

If you have more questions you can also find us on Telegram https://t.me/checkico
🙂

**Comment by alexanderisora** [comment]
Thanks for the great explanation @icochecker 👍
