### ISSUE TITLE
Bread - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#21]
# [Bread](https://token.breadapp.com/en/) (BRD)

### Executive Team
- Adam Traidman (Co-founder & CEO) - Oct 2014 - Present | [Linkedin profile](https://www.linkedin.com/in/adamtraidman/)
- Aaron Voisine (Co-founder & President) - 2013 - Present [Linkedin profile](https://www.linkedin.com/in/aaronvoisine/) | [Github](https://github.com/voisine)
- Aaron Lasher (Co-founder & CMO) - Apr 2017 - Present [Linkedin profile](https://www.linkedin.com/in/aaronlasher/)
- James MacWhyte (Chief Product Officer) - Sept 2015 - Present [Linkedin profile](https://www.linkedin.com/in/james-macwhyte-657a2897/)
- Samuel Sutch (Chief Technology Officer) - Sept 2015 - Present [Linkedin profile](https://www.linkedin.com/in/ssutch/) | [Github](https://github.com/samuraisam)
- Brent Traidman (Chief Revenue Officer) - Sept 2017 - Present [Linkedin profile](https://www.linkedin.com/in/btraidman/)
- Scott​ ​Wiebe​ ​(CFO) - Sept 2017 - Present [Linkedin profile](https://www.linkedin.com/in/scott-wiebe-aaa74426/)

### Advisors
- Charlie Lee [Linkedin profile](https://www.linkedin.com/in/chocobo/)
- Ben Davenport [Linkedin profile](https://www.linkedin.com/in/bpdavenport/)
- David Johnston [Linkedin profile](https://www.linkedin.com/in/davidajohnston/)
- Batara Eto [Linkedin profile](https://www.linkedin.com/in/bataraeto/)
- Shinji Kimura [Linkedin profile](https://www.linkedin.com/in/shinzizm/)
- Mai Fujimoto [Linkedin profile](https://www.linkedin.com/in/mai-fujimoto-5b9893102/)

### Engineering and development
- Adrian Corscadden (iOS Developer) - Nov 2016 - Present [Linkedin profile](https://www.linkedin.com/in/acorscadden/)
- Matt Davids (DevOps Architect) - Jan 2016 - Present [Linkedin profile](https://www.linkedin.com/in/matthew-davids-88aba314/)
- Mihail Gutan (Android Architect) - Jul 2015 - Present  [Linkedin profile](https://www.linkedin.com/in/mihail-gutan/)
- Daniel Moore
- Pieter Parker
- Kevin Ponto
- Daniel Staudigel (Sr. Software Engineer) - Jul 2017 - Present [Linkedin profile](https://www.linkedin.com/in/daniel-staudigel-69974311/)

### Headquarter
**Breadwinner AG**          
Schindellegistrasse 3         
8808 Pfäffikon SZ            
Switzerland       

- [UID Register](https://www.uid.admin.ch/Search.aspx?lang=en)         
- [Swiss Official Gazette of Commerce](https://www.shab.ch/shabforms/COMMON/application/applicationGrid.jsp)

**Entry in the commercial register** 03.05.2017    
**Legal form:** Company limited by shares (AG)      
**UID:** CHE-357.612.662     
**Commercial register number:** CH-130.4.024.180-3        

#### Management
- **Jan Happel** **|** Board of directors-Member **|** Since 29.09.2017
- **Christopher Aaron Lasher** **|** Board of directors-Member **|** Since 29.09.2017
- **Aaron Voisine** **|** Board of directors-President **|** Since 29.09.2017
- **Adam Traidman** **|** Board of directors-Delegate, Board of directors-Vice-president **|** Since 29.09.2017

#### Past and translated company names:
- readstar Sàrl
- Breadwinner SA
- Breadstar GmbH
- Breadwinner Ltd
- Breadstar LLC

#### SOGC notifications
**SOGC 189/2017 - 29.09.2017**         
Categories: Changes of business name, Changes of legal status, Changes in the activity, Changes in the capital, Address changes, Personal changes.

![sogc189-2017 -29 09 2017-a](https://user-images.githubusercontent.com/32852887/34025952-1857974e-e153-11e7-8de8-9c058504a19e.png)
![sogc189-2017 -29 09 2017-b](https://user-images.githubusercontent.com/32852887/34025961-270f432c-e153-11e7-878e-f36a92b22327.png)

### Breadwallet LLC (US)
**File Number:** 5717431     
**Incorporation Date / Formation Date:** 26 Mar 2015   
**Entity Kind:** Limited Liability Company     
**Entity Type:** General         
**Residency:** Domestic          
**State:** DELAWARE          

![bread-delaware](https://user-images.githubusercontent.com/32852887/34026386-f98acd60-e155-11e7-9ae3-16a8ee753b9a.png)

- [Delaware entity search](https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx)  

## Github
- [bread](https://github.com/breadwallet)

## Product
- [Bread - iOS](https://itunes.apple.com/app/breadwallet/id885251393/)
- [Bread - iOS beta with ethereum support](https://token.breadapp.com/en/crowdsale/beta/)
- [Bread - Android](https://play.google.com/store/apps/details?id=com.breadwallet)

## Smart contract
- [Crowdsale on github](https://github.com/breadwallet/smart-contracts/tree/master/contracts)
- [Crowdsale - View on etherscan](https://etherscan.io/address/0x214a6e8a4510828dab101afc4e0a5859c62c44e1#code)
- [Bread Token - View on etherscan](https://etherscan.io/address/0xd8a83ae49d655821b67ec278693f20e9d69e3350#code)

## Vesting
- No vesting schedule for team and advisor tokens.
- Team and advisors tokens are not vested in the smart contract.
- Ceo says that vesting will be added after the ICO.

![bread-token-vesting-8](https://user-images.githubusercontent.com/32852887/34027073-a3a6b04e-e15a-11e7-94da-6b0a36bb8b75.png)

![bread-token-vesting-12-b](https://user-images.githubusercontent.com/32852887/34027086-ad8f172c-e15a-11e7-8f9d-ca5b7ada971d.png)

- Co-founder Aaron Lasher has no idea about the Team vesting schedule.

### Questions not answered by the company:
![bread-token-vesting-1](https://user-images.githubusercontent.com/32852887/34027057-8e49b5ac-e15a-11e7-9b74-de4b76f3ef2b.png)
![bread-token-vesting-2](https://user-images.githubusercontent.com/32852887/34027060-91537e9a-e15a-11e7-951e-721f13c8f48f.png)
![bread-token-vesting-3](https://user-images.githubusercontent.com/32852887/34027062-937c3e14-e15a-11e7-9a9f-3ef6f7587ee4.png)
![bread-token-vesting-4](https://user-images.githubusercontent.com/32852887/34027064-9a0386f2-e15a-11e7-8bf7-79f03cafb85a.png)
![bread-token-vesting-5](https://user-images.githubusercontent.com/32852887/34027065-9c236664-e15a-11e7-9e3a-05b30a56b52d.png)
![bread-token-vesting-6](https://user-images.githubusercontent.com/32852887/34027067-9ed6aff6-e15a-11e7-9d65-38d1693e5377.png)
![bread-token-vesting-7](https://user-images.githubusercontent.com/32852887/34027069-a0fa84ce-e15a-11e7-83cf-1f375d21d4ed.png)
![bread-token-vesting-9](https://user-images.githubusercontent.com/32852887/34027075-a59bd7e4-e15a-11e7-97b5-f7a9ac15828a.png)
![bread-token-vesting-10](https://user-images.githubusercontent.com/32852887/34027079-a755905c-e15a-11e7-8470-f11150326f00.png)
![bread-token-vesting-11](https://user-images.githubusercontent.com/32852887/34027080-a93bd584-e15a-11e7-84d6-a532db2ea9d3.png)
![bread-token-vesting-12](https://user-images.githubusercontent.com/32852887/34027084-ab56c0a4-e15a-11e7-88a8-88143fbdb72f.png)
![bread-token-vesting-13](https://user-images.githubusercontent.com/32852887/34027087-af7cf928-e15a-11e7-8c7b-16e76b1b595a.png)
![bread-token-vesting-14](https://user-images.githubusercontent.com/32852887/34027088-b1595be2-e15a-11e7-9766-54357fba810e.png)
![bread-token-vesting-15](https://user-images.githubusercontent.com/32852887/34027091-b37e83ac-e15a-11e7-8262-a33db7f0d166.png)
![bread-token-vesting-16](https://user-images.githubusercontent.com/32852887/34027092-b54248fe-e15a-11e7-93ea-ce85794f1757.png)
![bread-token-vesting-17](https://user-images.githubusercontent.com/32852887/34027094-b726d694-e15a-11e7-964d-c5c61e9b0e11.png)

### Live Youtube AMA with Bread CEO (click to view)

[![Bread Live AMA](http://img.youtube.com/vi/1IbGFsjdtxg/0.jpg)](https://www.youtube.com/watch?v=1IbGFsjdtxg&feature=youtu.be&t=5832 "Bread Live AMA")

#### CEO Adam Traidman, when asked about vesting schedule for team and advisors tokens:
- "The final vesting plan has not been ratified by the board of directors."
- "Generally these types of affairs are considered confidential"
- "2 to 3 year vesting terms"
- "final details will be ratified by the end of the crowd sale"

## Conclusion
- The founders never answered the questions asked by investors, showing disregard for their concerns.

**Comment by agentbutlr** [comment]
Another money grab!
