### ISSUE TITLE
Liminality - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#26]
# [Liminality](https://liminality.network) (LMN)

## Team
- Sidney Sissaoui (Founder and CEO) - Dec 2017 - Present | [Linkedin profile](https://fr.linkedin.com/in/sidneysissaoui) **blockchain experience??**
- Cyril Kato (Core Developer) - Jun 2017 - Dec 2017 | [Linkedin profile](https://fr.linkedin.com/in/cyrilllllll) **blockchain experience??**
- Christian Peka (Community Manager) | **No Linkedin**
- Diana A. (Graphic designer) | **No Last name**
- Ralf Nöppert (Creative Director) | [Linkedin profile](https://www.linkedin.com/in/ralf-noeppert) **does not mention Liminality**
- Benchi Chen (Mobile Developer) | [Linkedin profile](https://fr.linkedin.com/in/benchi-chen-b495626b) **does not mention Liminality**
- Axi (Marketer) | **No Name**

### Advisors
- Stefan Kahlert | [Linkedin profile](https://www.linkedin.com/in/stefan-kahlert-a4473656)
- Angelo Melis | [Linkedin profile](https://www.linkedin.com/in/angel0z/)

## Company 
- No company
![liminality-ceo-info](https://user-images.githubusercontent.com/32852887/34429145-74758368-ec54-11e7-9030-e2657cc0e06b.png)

![liminality-chat-1](https://user-images.githubusercontent.com/32852887/34429211-4e834ebe-ec55-11e7-8935-2367ae1c1126.png)
![liminality-chat-2](https://user-images.githubusercontent.com/32852887/34429214-51127574-ec55-11e7-9c51-6dbf2d084282.png)
![liminality-chat-3](https://user-images.githubusercontent.com/32852887/34429215-532121bc-ec55-11e7-8be5-4c378dfd41fc.png)

## Smart contract
- Not available

## Github
- [LiminalityNetwork](https://github.com/liminalitynetwork)
- No public repositories

![liminality-github](https://user-images.githubusercontent.com/32852887/34429137-5c46d224-ec54-11e7-8c35-34a592965ecc.png)

## Product
- No product

## Vesting
- No vesting schedule for Team and advisors tokens

![liminality-chat-vesting](https://user-images.githubusercontent.com/32852887/34429185-073855cc-ec55-11e7-9b55-15d5bfa22d06.png)
![liminality-chat-vesting-2](https://user-images.githubusercontent.com/32852887/34429186-0a068526-ec55-11e7-9363-57b4cd0102aa.png)

### Token distribution
![liminality-token-distribution](https://user-images.githubusercontent.com/32852887/34429127-4ebcafc0-ec54-11e7-951e-1ba39916bdb4.png)

### Token allocation
![liminality-token-allocation](https://user-images.githubusercontent.com/32852887/34429129-5323acd0-ec54-11e7-9fef-d6c50a771b34.png)

#### Funds collected as of 30 Dec 2017
![liminilaty-pre-ico](https://user-images.githubusercontent.com/32852887/34451370-82857cb8-ed23-11e7-9caa-e8e21b020cbc.png)

### [Whitepaper](https://liminality.network/download/liminality.pdf)

# Update as of 30 Dec 2017 - Founder cancels project
- [Source](https://medium.com/liminalitynetwork/the-end-of-a-story-711a5514c99e)

**Comment by shideneyu** [comment]
Hello @icochecker . You can check by yourself that we refunded everyone who invested in the project. It has been fully cancelled, and we have not even touched to the funds.

Would it be possible that you remove the first image of this ticket ? It shows my personal address that I gave to give more insurance to my investors, and I am now trying to regain my privacy now that I fulfilled my duties.

Best
