### ISSUE TITLE
Pundi X - Due diligence

### ISSUE THREAD

**Issue by nithyaasworld** [ico-check/ico-check#28]
# [Pundi X](https://pundix.com/) (PXS)

## Team
- Zi Bin (Zac) Cheah (Co-founder & CEO) - Oct 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/zibin/)
- Pitt Huang (Co-founder & CTO/COO) - Dec 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/pitt-huang-086591b/)
- Danny Lim (Co-founder & CFO) - Oct 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/wei-xiang-lim-danny-49b9199b/)
- Constantin Papadimitriou (President Advisor) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/constantin-papadimitriou-447436/)

### Advisors
- Miko Matsumura | [Linkedin profile](https://www.linkedin.com/in/mikomatsumura/)
- David Ben Kay | [Linkedin profile](https://www.linkedin.com/in/davidbenkay/)
- Manan Mehta | [Linkedin profile](https://www.linkedin.com/in/manan-mehta-5746ab23)
- Michael Kapilkov | [Linkedin profile](https://www.linkedin.com/in/michael-kapilkov)
- Wilson Lee | [Linkedin profile](https://www.linkedin.com/in/lee-willson-778413113/)
- Danny Baskara | [Linkedin profile](https://www.linkedin.com/in/dannybaskara/)
- Atsushi Hisatsumi | [Linkedin profile](https://www.linkedin.com/in/atsushi-hisatsumi/)
- Koji Miura | [Linkedin profile](https://www.linkedin.com/in/koji-miura-0a7275152/)
- Terry Shiraishi | [Linkedin profile](https://www.linkedin.com/in/tshiraishi/)
- Stephen DeMeulenaere | [Linkedin profile](https://www.linkedin.com/in/stephendemeulenaere/)
- Ashton Addison | [Linkedin profile](https://www.linkedin.com/in/ashtonaddison/)
- Jay Addison | [Linkedin profile](https://www.linkedin.com/in/jay-addison-16525832/)
- Rudy Danandjaja | [Linkedin profile](https://www.linkedin.com/in/rudy-danandjaja-0bb318/)
- Gede (Buwana) Mahartapa | [Linkedin profile](https://www.linkedin.com/in/mahartapa/)
- Alex Tan | [Linkedin profile](https://www.linkedin.com/in/myalextan/)
- Brata Rafly | [Linkedin profile](https://www.linkedin.com/in/bratarafly/)
- Haruumi Shiode | [Linkedin profile](https://www.linkedin.com/in/haruumi-shiode-ab17a83/)
- Vincent Teo | [Linkedin profile](https://www.linkedin.com/in/teovincent/)
- Christian Angga | [Linkedin profile](https://www.linkedin.com/in/christianangga/)

### PUNDI X LABS PRIVATE LIMITED
**Number:**	015398V      
**Registry Type:** 2006 Act Company       
**Company Type:** Limited by shares         
**Registered Office Address:**	        
First Floor        
Millennium House         
Victoria Road       
Douglas IM2 4RW        
Isle of Man  
       
**Date of Incorporation:**	13 Nov 2017     
**Presence of Charges:** No     
**Is in Liquidation?:** 	No     
**Receiver(s) Appointed?:** No      
**Status:**	Live     

## Smart contract
- [Contract on github](https://github.com/pundix/ico/tree/master/contracts)
- [Pre-sale deployed on etherscan (Solidity source code not published)](https://etherscan.io/address/0x358D12436080a01A16f711014610F8a4c2C2d233)

## Github
- [Pundix](https://github.com/pundix)

## Product
- [PundiX POS](https://medium.com/pundix/pundi-x-2017-reviews-and-2018-outlooks-c8d9f9b0edc0)
- [PundiX POS in coffee shop in Indonesia](https://www.youtube.com/watch?v=PWESI8--Lcc&feature=youtu.be)

[![Working product in coffee shop](http://img.youtube.com/vi/PWESI8--Lcc/0.jpg)](https://www.youtube.com/watch?v=PWESI8--Lcc "PundiX Working product")

## Vesting
- 10 month vesting schedule for Team and Advsiors tokens (See chat screenshot below)

### Token distribution
![pundix-distribution](https://user-images.githubusercontent.com/32852887/34593546-d0f69fd8-f1cb-11e7-8daf-cef9826a0632.png)

### Token allocation
![pundix-allocation](https://user-images.githubusercontent.com/32852887/34593548-d5ab8ed0-f1cb-11e7-8f23-a1562c1f7316.png)
 
### Questions
![pundix-questions](https://user-images.githubusercontent.com/32852887/34596500-82a346c8-f1e0-11e7-9ea4-e4177e93c9f0.png)

![pundix-reg-d](https://user-images.githubusercontent.com/32852887/34598325-508d2580-f1ec-11e7-829f-f61e0cc70f83.png)

**Comment by bk20192018** [comment]
why red flag?

**Comment by icochecker** [comment]
@bk20192018 Vesting schedule (Token lock) for Team and Advisors tokens is less than 2 years.
ICO check requires +2 years

**Comment by virtari** [comment]
Why did they need more money because according to news they already raised 266k ETH in October. Or sid i miss something here? https://medium.com/pundix/blockchain-retail-startup-pundi-x-raises-over-usd-4-million-to-successfully-complete-pre-sale-ico-5389d93ccb16
