### ISSUE TITLE
Loomia - Due diligence

### ISSUE THREAD

**Issue by mhingston** [ico-check/ico-check#29]
# [Loomia](https://loomia.com/token) (TILE)

## Team
- Janett Liriano (CEO) - Mar 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/janett-liriano-39241a56/)
- Ezgi Ucar (Director of Product Development) - Mar 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/ezgi-ucar/)
- Marco Paúl (VP of Operations & Supply Chain) - Avr 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/marco-pa%C3%BAl-b237043/)
- Solomon Lederer (Blockchain Director) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/sollederer/)
- Madison Maxey (Founder & Technical Lead) - Aug 2013 - Present | [Linkedin profile](https://www.linkedin.com/in/madisonmaxey/)
- Paul Raffin (Brand Advisor) | [Linkedin profile](https://www.linkedin.com/in/paul-raffin-6102243)
- Angelo Saraceno (Blockchain Advisor) | [Linkedin profile](https://www.linkedin.com/in/paul-raffin-6102243) **Student, Blockchain experience?**
- Kedar Iyer (Blockchain Engineer) | [Linkedin profile](https://www.linkedin.com/in/kedar-iyer-47552649/)
- Nicholas Napp (Technical Advisor) | [Linkedin profile](https://www.linkedin.com/in/nicholasnapp/)
- Kenya Wiley (Legislative Advisor) | [Linkedin profile](https://www.linkedin.com/in/kenya-wiley-558601b6/)
- Chris Hare (Advisor)
- Sabri Sansoy (Advisor)

### LOOMIA TECHNOLOGIES, INC
**File Number:** 5471686         
**Incorporation Date / Formation Date:** 27 Jan 2014        
**Entity Kind:** Corporation           
**Entity Type:** General          
**Residency:** Domestic         
**State:** DELAWARE       

![loomia-delaware](https://user-images.githubusercontent.com/32852887/34660200-d52a9da8-f440-11e7-82f5-1310f6dbe23e.png)

## Smart contract
- N/A

## Github
* [LOOMIA](https://github.com/LOOMIA)

## Product
- [Product](https://www.youtube.com/watch?v=vBy3Sch_bDU)
### Product not connect to blockchain, the tile platform.

![loomia-roadmap](https://user-images.githubusercontent.com/32852887/36651689-6df55d04-1aaa-11e8-8e54-2e2f666c7560.png)

## Vesting
- Team and Advisors get access to half of their tokens once the ICO start. The other half vests over 12 month.
- Vesting won't be coded in the smart contract. Legal contract instead.

![loomia-legal](https://user-images.githubusercontent.com/32852887/36126894-f24683da-105a-11e8-86f0-8c0b51c0059c.png)

![loomia-vesting](https://user-images.githubusercontent.com/32852887/35424267-b5562748-0252-11e8-834b-f7e8424222fa.png)

### Public sale cancelled and replaced with Airdrop
![tile-airdrop](https://user-images.githubusercontent.com/32852887/37529824-618a3728-2938-11e8-98f0-0e1fa8044d7e.png)

### Token distribution
50% in connection with initial token sale            
15% to presale, including purchasers of SAFTs           
15% to development team        
10% to brand partners         
5% to advisors   
5%, after a one-year lock-up, to third parties, as determined by LOOMIA, to grow and expand the utilization of TILE Tokens   

#### Allocation of Funds:        
**Uses (4 year summary)**         
**Personnel/OPS:** 4,660,000         
**Marketing, Advertising, Promotional:** 2,000,000      
**TILE Development:** 2,180,000       
**LEL Development:** 2,420,000       
**Software Development:** 2,320,000        
**Contractors:** 2,580,000       
**Legal:** 1,700,000          
**Testing/Certifications:** 2,000,000       
**Raw Materials/MFG:** 3,800,000      
**TOTAL:** 23,660,000     

### Q&A
![loomia-qa-1](https://user-images.githubusercontent.com/32852887/35254381-3a9430b4-ffea-11e7-8321-06be09569a6c.png)
![loomia-qa-2](https://user-images.githubusercontent.com/32852887/35254384-3e25c8c8-ffea-11e7-99b6-62c8cacd2382.png)

![loomia-qa-product](https://user-images.githubusercontent.com/32852887/36651509-8b16df9e-1aa9-11e8-94b4-5a58a7f3d960.png)

## Flags
**Real Team:**  ✅     
**GitHub:** ✅  
**Smart Contract:** (N/A yet)    
**Working Product:** ❌ Product not connected to blockchain, the tile platform. 
**+2 yr Vesting for team:** ❌  - 12 month Vesting schedule for Team and Advisors which won't be coded in the smart contract. Half of Tokens available the date of the TGE.
**Have a company:** ✅             
**Transparent:** -   

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by Aza1** [comment]
Love your work guys!
