### ISSUE TITLE
NapoleonX - Due diligence

### ISSUE THREAD

**Issue by hterrence** [ico-check/ico-check#3]
Company's website: https://www.napoleonx.ai/

**Comment by icochecker** [comment]
# Napoleon (NPX)

## Company
[Napoleon Capital](https://www.infogreffe.com/entreprise-societe/824566814-napoleon-capital-780117B030350000.html)   
73 Rue Léon Bourgeois
91120 Palaiseau                     
                      
**Incorporated on:** 27 July 2017        
#### Director:
- Stephane IFRAH
- Arnaud DARTOIS

## Github
- [Repository](https://github.com/ProjectNapoleonX)

## Smart contract
- [Contract on github](https://github.com/ProjectNapoleonX/SmartContract-ICO)

## Vesting
- 6 month

**Comment by loul42** [comment]
Hi,

What are the multiple red flags ?

Thanks

**Comment by icochecker** [comment]
@loul42 I just updated the issue. (Last update 16 Nov 2017).
Red flags:
- 6 month Vesting schedule for Founders tokens. (Founders could sell their tokens 6 month after the ICO)
- No working product but a demo
- Team members listed on their website but Linkedin says otherwise. (See screenshots above)

**Comment by coinbala** [comment]
I put 0.5 ETH should I take it out?

**Comment by KazanGi** [comment]
IMHO avoid completely this ICO

**Comment by gaia** [comment]
Partnerships being established: https://medium.com/@napoleonx.ai/napoleonx-update-16-02-18-bloomberg-will-list-our-strategies-6c3d72acc582

**Comment by pabx06** [comment]
LOL. it is like paying a gambler to lose all your money
