### ISSUE TITLE
Thekey - Due diligence

### ISSUE THREAD

**Issue by aericom** [ico-check/ico-check#30]
# [Thekey](https://www.thekey.vip) (TKY)

## Team
- Catherine Xueli Li (CEO) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/catherine-xueli-li-a50801150) **only has 12 connections**
- Ken Huang (President, Identity Verification & Blockchain) | [Linkedin profile](https://www.linkedin.com/chatin/wnc/in/kenhuang8) **does not mention TheKey** 
- Jian Wang (CBO) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/jian-wang-710467153/) **only has 1 connection**
- Guochun XU (CTO) | [Linkedin profile](https://cn.linkedin.com/in/guochun-xu-9101657a) **does not mention TheKey and only has 8 connections**
- Hening Zhang (CPO) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/hening-zhang-822460153) **only has 1 connection**
- Yuli Huang (CDO) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yuli-huang-36497514b/) **only has 4 connections**
- Kun Chen (CMO) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/kun-chen-112a3b37/)
- Lin Zuo (COO) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/lin-zuo-7a885314b) **only has 12 connections**
- Yiming Ding (R&D Manager) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yiming-ding-139465153/) **only has 1 connection**
- Dawei Ding (Implementation Manager) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/dawei-ding-525466153/) **only has 1 connection**

### Advisors
- Roger Lim - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/limroger/)
- Qingyue Chen | [Linkedin profile](https://www.linkedin.com/in/tom-qingyue-chen-95893130/)

**Observation:** Besides Ken Huang, team members and advisors does not seem to have any cybersecurity experience to build an identity solution

#### THEKEY BDMI INTERNATIONAL FOUNDATION LTD.  
**Registered Address:**    
9 TEMASEK BOULEVARD        
04-02         
SUNTEC TOWER TWO         
SINGAPORE 038989     

**Incorporation Date:** 2 Nov 2017   
**Registration Type:** EXEMPT PRIVATE COMPANY LIMITED BY SHARES   
**UEN	:** 201731436C        
**Status:** LIVE COMPANY         
**Industry:** COMPUTER PROGRAMMING, CONSULTANCY AND RELATED ACTIVITIES        

![theykey-singapore](https://user-images.githubusercontent.com/32852887/34815213-dc81a05c-f6b0-11e7-9042-acbf2f4521db.png)

[Directory of Registered Entities](https://www.tis.bizfile.gov.sg/ngbtisinternet/faces/oracle/webcenter/portalapp/pages/TransactionMain.jspx?selectedETransId=dirSearch)

### THEKEY INC. LIMITED (To verify)
**Company Registration No.** 2574729        
**Company Name** THEKEY INC. LIMITED           
**Company Type** Private Company Limited By Shares          
**Date of Incorporation** 5 September 2017         

[ICRIS - Companies Registry](https://www.icris.cr.gov.hk/csci/)

## Smart contract
- Neo smart contract not on Github.

## Github
- [THEKEY](https://github.com/thekeygithub)

### Commits
![thekey-commits](https://user-images.githubusercontent.com/32852887/34925493-f4a5813e-f9a9-11e7-925e-a4b1da61807c.png)

- [Commits activity](https://github.com/thekeygithub/DMI/graphs/commit-activity)

## Product
- No working product

## Vesting
![thekey-vesting](https://user-images.githubusercontent.com/32852887/34927835-7806d050-f9b9-11e7-860e-2a89414984f4.png)

- Vesting schedule not specified

### Token distribution
![tky-distribution](https://user-images.githubusercontent.com/32852887/34822819-7d984074-f6c8-11e7-8cbc-15ecb2abca6a.png)

### Token allocation
![tky-allocation](https://user-images.githubusercontent.com/32852887/34822822-844c5248-f6c8-11e7-8b26-6a0447c30241.png)

# Questions not answered by the company:

# 1
![thekey-questions-1](https://user-images.githubusercontent.com/32852887/34925531-29345f06-f9aa-11e7-97ba-60b7b5ce20b4.png)

### Questions asked on **24 Dec 2017**

![theykey-questions-2](https://user-images.githubusercontent.com/32852887/34926288-9521bd22-f9ae-11e7-9564-7e38550ad0b6.png)

![theykey-questions-3](https://user-images.githubusercontent.com/32852887/34926302-ae6750a8-f9ae-11e7-925a-d56fbddfab6f.png)

# 2
![theykey-email-1](https://user-images.githubusercontent.com/32852887/34926501-1b526044-f9b0-11e7-93e6-3c1eceb3ed4f.png)

### Email sent on Dec 24 2017

# 3
![theykey-email-2](https://user-images.githubusercontent.com/32852887/34926502-1d7e74ac-f9b0-11e7-9487-31aae7658b7c.png)
![theykey-email-3](https://user-images.githubusercontent.com/32852887/34926893-c66c4f92-f9b2-11e7-9434-6b3ec7eefd88.png)

### Questions remain unanswered .....

# 4
![theykey-questions-4](https://user-images.githubusercontent.com/32852887/34926920-fb2a950e-f9b2-11e7-8ea1-f381a026def1.png)
![theykey-questions-5](https://user-images.githubusercontent.com/32852887/34926924-02a5cf60-f9b3-11e7-9f8e-94e541a5568c.png)

## The team never answered the questions asked by investors, showing disregard for their concerns. #

**Comment by aericom** [comment]
Company website : https://www.thekey.vip/

**Comment by MrNicodemuz** [comment]
Many (if not all) of the team members still seem to be also working ("present") for their previous companies according to their LinkedIn profiles. Some do not even indicate to be working at TheKey. This could be seen as a slight red flag.

**Comment by wolvesland** [comment]
SSL certificate of the webpage is for the domains `app.gotrips.net` and `www.app.gotrips.net` hours before the ICO thus throwing `SSL_ERROR_BAD_CERT_DOMAIN` erros.
