### ISSUE TITLE
Colu - Due diligence

### ISSUE THREAD

**Issue by MrNicodemuz** [ico-check/ico-check#31]
# [Colu](https://cln.network/) (CLN)

## Team
- Amos Meiri (Co-founder & CEO) - Dec 2014 - Present | [Linkedin profile](https://www.linkedin.com/in/amos-meiri-23002945/)
- Mark Smargon (Co-founder & VP of Blockchain) - 2014 - Present | [Linkedin profile](https://www.linkedin.com/in/marksmargon/)
- David Ring (Co-founder & VP Finance) - Oct 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/davidring1/)
- Dan Ariely (CBE - Advisor) - Sep 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/danariely/) 
- Elad Shabi (Director of Business Operations) - Feb 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/elad-shabi-3b330b19/)
- Maya Grossman (Director of Marketing) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/mayasagigrossman/)
- Leora Bachrach (Head of HR) - May 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/leora-bachrach-6461876/)
- Rotem Lev (CTO) - Jan 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/rotemlev/)
- Dana Heller (Chief Economics and Regulation Office) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/dana-heller-6b278461/)
- Jeremy Stein (VP Operations) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/jeremy-stein-30900a6/)
- Valery Zhurbenko (DevOps Lead) - May 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/valery-zhurbenko)
- Tal Beja (Blockchain Infrastructure Lead) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/tal-beja-34654337/)
- Dotan Hershkovitz (TLV Marketing Lead) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/dotanh)
- Elin Gersin (Full Stack Developer) - Jul 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/elin-gersin-8ab2b991/)
- Omri Aloni (Product Marketing Manager) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/omri-aloni-5625b493/)
- Omer Freiman (Full Stack Developer) - Nov 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/omer-frieman-a5484931/)
- Leon Rossiter (Liverpool City Manager) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/leon-rossiter-05493834/)
- Orit Cohen (Graphic Designer) - Jun 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/orit-cohen-7124739a/)
- Olivier Desloges (E. London City Launcher) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/olivier-desloges-82951026/)
- Ido Davidovitch (Haifa City Launcher) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/ido-davidovitch-629092130/)
- Anna Rosenberg (Head of Customer Support) - Avr 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/anna-rosenberg15)
- Talia Soen (Product Manager) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/taliasoen/)
- Daniel Kovachi (Android Developer) - Jun 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/kochavidaniel/)
- Elik Rozenboim (Consumer PM and BI Lead) - Dec 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/elikrozenboim/)
- Eyal Alsheich (Full Stack Lead) - Feb 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/eyalalsheich/)
- Noa Aharon (Head of design) - Jan 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/noa-aharon-872b653a/)
- Renata Blum-Hamias (QA Engineer) - Jul 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/renata-blum-177849119)
- Verity Hall (Liverpool City Launcher) | **No Linkedin**
- Vala Vaintraub (TLV City Manager) - Nov 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/vala-vaintraub-02b2138b/)
- Igor Grebenakha (Noc Engineer) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/igor-grebenaha-5943a05b/)
- Gal Barel (Finance Controller) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/galbarel)
- Lior Rabin (Backend and Blockchain Developer) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/lior-rabin-36b28126/)
- Dolev Goldenberg (TLV City Launcher) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/dolev-goldenberg-2b906984/)
- Yossi Segev (Android Developer) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yossi-segev-07492316/)
- Yarden Finkelshtein (TLV City Launcher) - Sep 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/yarden-finkelshtein-9966a2154/) **blank, does not mention Colu**
- Noa Ohayon-Bab (Content & Communities Manager) - Aug 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/noaohayon/)
- Shani Shomroni (Office Manager) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/shani-shomroni-125638154/)
- Jacopo magni (E. London City Manager) - Avr 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/jmagni/)
- Roi Sagiv (Mobile Lead) - Jul 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/roisagiv/)
- Yehuda Cohen (iOS Developer) - Avr 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yehudaorencohen/)
- Shani Frankel (Graphci Designer) - Feb 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/shanifrankel)
- Gilad Fisher (Haifa City Manager) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/gilad-fisher-57631361/)
- Sharon Ben Sason (Senior Bookeeper) | **No Linkedin**
- Bella Shakhnovich (TLV City Launcher) - Jun 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/bella-shakhnovich-123074106/)
- Maxim GOS (Full Stack Developer) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/max-goz-30204337/)
- Yaron Glikerman (Project & QA Lead) - May 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/yaron-glikerman-040b453/)
- Yasmin Yusuf (E. London City Launcher) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yasmin-birring-yusuf-8b856134/)
- Ivo Gavin (E. London City Launcher) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/ivo-gavin-8062aab2/)
- Rebecca Moy (Liverpool City Launcher) - Jun 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/rebecca-moy-289992b0/)
- Daniel Girling-Jones (Liverpool City Launcher) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/daniel-girling-jones-7ab75b112/)
- Shani Korman (QA Engineer) - Feb 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/shani-korman)
- Yaron Klainer (Head of Expansion) - Mar 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/yaronklainer/)

### Board Members
- Eden Shochat (Equal Partner at Aleph VC) | [Linkedin profile](https://www.linkedin.com/in/edens/)
- Santo Politi (Co-founder and General Partner at Spark Capital) | [Linkedin profile](https://www.linkedin.com/in/santopoliti/)
- Yoni Assia (Founder and CEO at eToro) | [Linkedin profile](https://www.linkedin.com/in/yassia/)

### Colu Technologies Ltd.
**Registered office address:**      
Har Sinai 5        
Tel Aviv, 65133        
Israel     

### Colu Technologies DLT LTD
**Registered office address:**
57/63 Line Wall Road     
GX11 1AA    
Gibraltar      

Private company limited by shares      
Incorporated and registered in Gibraltar      
**Company Number:** 116312

- Colu Technologies DLT LTD is a fully owned subsidiary of Colu Technologies LTD Har Sinai 5, Tel Aviv, Israel.

![colu-company](https://user-images.githubusercontent.com/32852887/35950649-e425f380-0c77-11e8-883f-080b10a0c640.png)

## Smart contract
- [Contract on github](https://github.com/colucom/CLN-solidity/tree/master/contracts)
- [Deployed contract - View on etherscan](https://etherscan.io/address/0x12321Fb3e2548b03eaD42F09cAb239cff377b4e2#code)

## Github
- [Colucom](https://github.com/colucom)

## Product
![colu-product](https://user-images.githubusercontent.com/32852887/34995385-9e46070e-fad6-11e7-85e5-d1624ce4fbbc.png)

![colu-prototype](https://user-images.githubusercontent.com/32852887/36130011-713bef9a-106a-11e8-8335-39941fe867a5.png)

- [Colu Digital Wallet - Android Play store](https://play.google.com/store/apps/details?id=com.colu.localeconomies&hl=en)
- [Colu - iTunes Store](https://itunes.apple.com/us/app/colu/id1105816764?mt=8)

## Vesting
- [Codified vesting on github](https://github.com/colucom/CLN-solidity/blob/master/contracts/VestingTrustee.sol)

![colu-vesting](https://user-images.githubusercontent.com/32852887/35996096-c759756c-0d15-11e8-8378-6769618d401a.png)

- 6 percent of all tokens will be allocated to CLN team members, future members, board members, advisors and other initial contributors to the network, with a 36 month vesting
schedule and a six-month cliff.

![colu-vesting](https://user-images.githubusercontent.com/32852887/35950479-13687b6e-0c77-11e8-95cc-e7bd3c94a795.png)

- source: [Token sale summary - Page 2](https://cln.network/pdf/token_sale_summary.pdf)

## Additional info
- American, Canadian and Israeli citizens are not eligible to participate in the crowdsale.

### Token distribution
![colu-distribution](https://user-images.githubusercontent.com/32852887/35602333-101e662a-0638-11e8-8936-3d3e78696d95.png)

#### Use of proceeds not available ❗️❗️❗️

![colu-use-of-proceeds](https://user-images.githubusercontent.com/32852887/36003537-ceb423ac-0d2e-11e8-87c2-5cac2948a2fd.png)

#### Roadmap incomplete ❗️❗️❗️

![roadmap](https://user-images.githubusercontent.com/32852887/36003633-2ea14c4a-0d2f-11e8-92fc-e81bfa71d463.png)

![colu-roadmap-incomplete](https://user-images.githubusercontent.com/32852887/36003552-de682866-0d2e-11e8-8f2a-098de4e9a885.png)

### Bonus for presale investors
![colu-bonus](https://user-images.githubusercontent.com/32852887/35950357-698fff54-0c76-11e8-9eb3-dd45c0fc519f.png)

# Flags
**Real Team:** ✅  
**GitHub:** ✅   
**Smart Contract:** ✅  
**Working Product:** ❌ Product not connected to the CLN (Blockchain)            
**+2 yr Vesting for team:** ✅          
**Have a company:** ✅              
**Transparent:** -    

# IcoCheck
- Issue added to [icocheck.io](https://icocheck.io/)
- Discuss this upcoming ICO and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by MrNicodemuz** [comment]
Token sale website: https://cln.colu.com/

**Comment by Formani4** [comment]
Have been BANNED out of telegram chat when asking writing "No dates on roadmap, no working product (money locked in unworking system), no comments on any exchange by admins". No questions, no explanations, just BAN. For me this action says its  ALL.
