### ISSUE TITLE
Republic Protocol - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#34]
# [Republic Protocol](https://republicprotocol.com) (REN)

## Team
- Taiyang Zhang (CEO) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/taiyangzhang/)
- Loong Wang (CTO) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/loong-wang-543855150/)
- Noah Ingham (Blockchain Dev) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/noahingham/)
- Susruth Nadimpalli (Blockchain Dev) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/susruth-nadimpalli/)
- Yunshi Sun (software engineer) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yunshi-sun-746b44123/)
- Jaz Gulati (Software Developer) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/jaz-gulati-55406382/)
- Hugh Greethead (Community Manager) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/hugh-greethead/)
- Darren Toh (Legal, Communications & Admin Manager) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/darren-toh-2a29885/)
- Ross Pure (Mathematics)
- Achinta Varna (Data Scientist) - Dappbase (PHD Student) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/achintav/)
- Ajay Prakash (Community)
- Alexandra Pukhova (Community)

### Advisors
- Dorjee Sun (COO, Santiment) | [Linkedin profile](https://www.linkedin.com/in/dorjee)
- Loi Luu (CEO, KyberNetwork) | [Linkedin profile](https://www.linkedin.com/in/loiluu)
- John Ng Pangilinan (Partner, Signum Capital) | [Linkedin profile](https://www.linkedin.com/in/johnngp)
- Anup Malani (Economics, University Chicago) | [Linkedin profile](https://www.linkedin.com/in/anup-malani-a1551b2)
- Prabhakar Reddy (Investor, Accel Partners - Bangalore) | [Linkedin profile](https://www.linkedin.com/in/prabhakar2reddy/) | [Twitter @prabhakar2reddy](https://twitter.com/prabhakar2reddy) | [Accel - Bangalore office](https://www.accel.com/team/prabhakar-reddy) | **deleted legitimate questions and banned users that asked them on the Nucleus Vision telegram chat.**

### DAPPBASE PTE. LTD. (Development company)
**Registered Address:**    
10 ANSON ROAD        
26-04         
INTERNATIONAL PLAZA         
SINGAPORE 079903       

**Company Type Description:** EXEMPT PRIVATE COMPANY LIMITED BY SHARES
**Incorporation Date:** 11 September 2017     
**Primary SSIC Code:** 62019  
**UEN	:** 201725823C        
**Status:** LIVE COMPANY         
**Industry:** COMPUTER PROGRAMMING, CONSULTANCY AND RELATED ACTIVITIES        

![dappbase-pte](https://user-images.githubusercontent.com/32852887/34827873-e01ed664-f6db-11e7-9f93-23d16bd12519.png)

- [Directory of Registered Entities](https://www.tis.bizfile.gov.sg/ngbtisinternet/faces/oracle/webcenter/portalapp/pages/TransactionMain.jspx?selectedETransId=dirSearch)

### Dappbase Ventures Limited (ICO Company) 
**Registered Address:**:      
Wickhams Cay II        
Road Town, Tortola,           
VG1110 British Virgin Islands          

**Registered on:** 31 October 2017         
**Registration No:** 1959524

- [BVI Registry](http://www.bvifsc.vg/en-gb/divisions/registryofcorporateaffairs.aspx)

## Smart contract
- [View on etherscan](https://etherscan.io/address/republicprotocol.eth#code)

## Github
- [Republic Protocol](https://github.com/republicprotocol)

## Product
- No working product available to test

![republic-product](https://user-images.githubusercontent.com/32852887/35742637-57d1aafe-083b-11e8-9806-00cde5d17abd.png)

## Vesting
![republic-vesting](https://user-images.githubusercontent.com/32852887/35545004-541e011c-056d-11e8-8115-50bbadf7df3d.png)

- [Source](https://medium.com/republicprotocol/whitelist-ico-faq-a877b3d8d264)

## Additional info
- **Citizens of U.S, China, Korea & Canada will not be able to participate**
- Private pre-sale participants received between 0–15% bonus. This bonus is not locked.

### Token distribution
![republic-distribution](https://user-images.githubusercontent.com/32852887/35544993-4b1acd66-056d-11e8-8458-a0409aea73bb.jpeg)

### [White paper](https://github.com/republicprotocol/whitepaper/blob/master/republic-whitepaper.pdf)

**Comment by yboz** [comment]
I'm not 100% sure about the details but it looks like RP did part ways with some early investors (I would really like to know why). This does not necessarily have to be a bad thing but the investors transfered ETH to RP when ETH was ~1300$ and should have gotten a certain amount of RP's tokens for it. Now they just got ETH back @1000$. It does not seem like RP is really the guilty party here but I did not like how they handled the situation in their telegram channel. I saw a lot of deleted messages and some people where talking about blocked users. This needs further investigation...

**Comment by angryolk** [comment]
![tim 20180123133906](https://user-images.githubusercontent.com/2903242/35278773-ea393ebc-0042-11e8-8eee-d3af2717f67d.png)
![tim 20180123133916](https://user-images.githubusercontent.com/2903242/35278775-ea68817c-0042-11e8-8eb8-d793c4f2d2bf.png)

**Comment by angryolk** [comment]
really active telegram community and admin quick response. their ico is in Feb so still has plenty of time to investigate with

**Comment by yboz** [comment]
> above answer sounds legit.... any one is thinking different about them?
I think so too. It is quite normal to pivot in the startup/kickstart scene.

**Comment by yboz** [comment]
They have a vesting schedule (specified in the [ICO FAQ](https://medium.com/republicprotocol/whitelist-ico-faq-a877b3d8d264) but when I asked about vesting being coded into the smart contract:
![no](https://user-images.githubusercontent.com/30636054/35476503-5907a600-03b1-11e8-9831-af0560ecbd16.png)

So there is no smart contract yet and this question needs a follow up.
