### ISSUE TITLE
Storiqa - Due Diligence

### ISSUE THREAD

**Issue by nithyaasworld** [ico-check/ico-check#35]
# [Storiqa](https://crowdsale.storiqa.com/)

## Team
*Here list team members with links to their LinkedIn accounts in here*

## Company
*Here put company information if company exsits. Also provide links (and possibly screenshots) where it can be verified that company exists*

## Smart contract
*Here put e.g. link to contract address on etherscan*

## Github
*Here put link to company's GitHub*

## Product
https://storiqa.com/start

## Vesting
*Here put information where vesting information was found and attach screenshots.*

## Additional info
*Here put additional comments about the company, with links when possible*

**Comment by nithyaasworld** [comment]
Not interested after looking at the below message from Storiqa's admin.

Thanks Peter for all your work! They are all very helpful.

![image](https://user-images.githubusercontent.com/5114190/34838654-f7a4c282-f724-11e7-91ff-fa2d2ad233f5.png)

**Comment by icochecker** [comment]
@nithyaasworld I closed the issue by mistake. I will add all info soon 🙂
