### ISSUE TITLE
Giza Device - Due diligence | EXIT SCAM

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#38]
# [Giza Device](https://web.archive.org/web/20180130165054/https://gizadevice.com/) (GIZA)

## Team
- Marco Fike (COO) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/marcofike/) | **No proof that he exist**
- Ivan Larionov (Senior Project Manager) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/ioanlarionov/)
- Aleksandar Rajic (Software developer) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/rajicaleksandar/)
- Dmitry Shishov (Engineer) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/dmitriy-shishov-61a748b0/)
- Ilya Stolyarov (Software Engineer) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/%D0%B8%D0%BB%D1%8C%D1%8F-%D1%81%D1%82%D0%BE%D0%BB%D1%8F%D1%80%D0%BE%D0%B2-87a37282/)
- Pavel Larionov (Lead Software Developer) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/pavel-larionov-996744b0/)
- Faisal Rahman (Software Application Engineer) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/faisal-rahman-m/)
- Anastasiya Shishova (Software Developer) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/anastasiia-lazareva-76534096/)
- Dmitry Lisin (Software developer) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/mrlisdim/)
- Pavel Vorobyov (Design Engineer) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/pvorobyov/)
- Yahya Mukhtar (Web Developer) - Sep 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/yahya-mukhtar-94a3b255/) **does not mention Giza Device**
- Karina Dovgalo (Community manager) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/%D0%B4%D0%BE%D0%B2%D0%B3%D0%B0%D0%BB%D0%BE-%D0%BA%D0%B0%D1%80%D0%B8%D0%BD%D0%B0-7908a076/)
- Esthelle Ness (HR Assistant) - Jun 2017 - Present  | [Linkedin profile](https://www.linkedin.com/in/esthelleness/)

![giza-team-1](https://user-images.githubusercontent.com/32852887/34873477-88e5b664-f795-11e7-9cc1-108d258988f8.png)
![giza-team-2](https://user-images.githubusercontent.com/32852887/34873492-8b70da58-f795-11e7-8060-ec6bf7736b28.png)
![giza-team-3](https://user-images.githubusercontent.com/32852887/34873496-8ce87012-f795-11e7-8458-37d745c77957.png)

### Advisors
- Cal Evans (Legal Advisor) | [Linkedin profile](https://www.linkedin.com/in/calevans1/)
- Jason Hung (Smart Contract Advisor) | [Linkedin profile](https://www.linkedin.com/in/jason-hung-471714/)

![jason-hung-linkedin](https://user-images.githubusercontent.com/32852887/36347840-603b8ede-1462-11e8-9b29-dc53b17b7f79.jpg)

- Nikolay Zvezdin (Business Strategy Advisor) | [Linkedin profile](https://www.linkedin.com/in/nikolayzvezdin/)

![giza-advisor](https://user-images.githubusercontent.com/32852887/34873502-91324b8e-f795-11e7-9168-5b16a122fada.png)

### [GIZA DEVICE LTD](https://beta.companieshouse.gov.uk/company/11111128) 
**Company number:** 11111128        
**Registered office address:**            
Suite 1        
5 Percy Street         
Fitzrovia          
London W1T 1DG          
England           
**Incorporated on:** 14 December 2017         
**Nature of business (SIC)**        
96090 - Other service activities not elsewhere classified

### Director: LAFORTUNE, Elna Paulette        
**Nationality:** Citizen Of Seychelles         
**Country of residence** Seychelles          
**Occupation:** Director       
Active director of 19 companies with the same registered office address as Giza Device.  

### Individual Person with Significant control: Mr Andrey Pashin
**Country resident:** Russian Federation   
**Date of Birth:** Jan 1967
**Nationality:** Russian
**Service Address:**    
96 Rossiyskaya STR.BLDG.1     
UFA     
RUSSIAN FEDERATION     
BASHKORSTOSTAN    

- [UK registrar of companies](https://beta.companieshouse.gov.uk/company/11111128)

## Smart contract
- [Deployed contract view on etherscan](https://etherscan.io/address/0xC4575B61286053c0ac362f70CdaA17BecD90aAcB#code)

## Github
- [Giza Device](https://github.com/GizaDevice)
No public repositories.

![giza-github](https://user-images.githubusercontent.com/32852887/34888112-31e79aa6-f7c9-11e7-9edb-e5cd810432c4.png)

## Product
- No working product for Gizza device
- [Pastildia](https://www.pastilda.com/) (Open source password manager), used to build the device.
- [Pastilda on crowd Supply](https://www.crowdsupply.com/third-pin/pastilda)

## Vesting
- Tokens for team and founders will be locked for 8 months

### Token Allocation and distribution
![giza-distribution](https://user-images.githubusercontent.com/32852887/37546756-ae3b39ce-296e-11e8-806e-a1c809cf671c.png)

## Q&A - 7 Jan 2018
![giza-chat-1](https://user-images.githubusercontent.com/32852887/34874386-17155748-f799-11e7-8286-dab8d9ab7f21.png)
![giza-chat-2](https://user-images.githubusercontent.com/32852887/34874393-195b00f2-f799-11e7-9302-bb1db222ca49.png)
![giza-chat-3](https://user-images.githubusercontent.com/32852887/34874397-1b62de42-f799-11e7-98e9-482f901a5030.png)
![giza-chat-4](https://user-images.githubusercontent.com/32852887/34874400-1e492562-f799-11e7-99ef-c00d21df30cd.png)
![giza-chat-5](https://user-images.githubusercontent.com/32852887/34874405-203e791c-f799-11e7-9f7c-afb0a535ee66.png)

# Flags
**Real Team:** ❌ Marco Fike does not exist
**GitHub:** ✅   
**Smart Contract:** ✅   
**Working Product:** ❌   
**+2 yr Vesting for team:** ❌  Tokens for team and founders will be locked for 8 months  
**Have a company:** ❌ Not a single team member is listed as director of GIZA DEVICE LTD. Director Lafortune Elna Paulette and Majority shareholder Andrey Pashin are nowhere to be seen on the website or white paper.             
**Transparent:** ❌  Directors of GIZA DEVICE LTD are unknown

# IcoCheck
- Issue added to [icocheck.io](http://icocheck.io/)
- Discuss this upcoming ICO and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by KazanGi** [comment]
Big red flags
Im pre-sale investor. 
I was banned from Giza telegram because I was pointing out huge issue about “Third Pin LTD” tech/Dev team being totally removed from the project ;  as Ivan Ioan Larionov (CEO Third Pin LTD) said without any reason except NOT given them the raised money to start working on development.
Investors were never informed about this important change till the end of the pre-sale. Even teleg. community was not informed. 
This project does totally depend on the first tech/dev team  because of their previous work and background, and it was the ONLY reason that made this project a potential success. 
So this presale have raised money on a false informations and they are now trying to convince investors by saying they are looking to hire the best devs people.

Cheers

look here : post #539
https://bitcointalk.org/index.php?topic=2567602.520

**Comment by icochecker** [comment]
# Investors concern in the Gizza telegram chat
![gizza-investor-telegram](https://user-images.githubusercontent.com/32852887/36009429-6728d2a0-0d4c-11e8-8818-989e698677a3.png)

**Comment by KazanGi** [comment]
Hi guys, 
If you look at CompaniesHouse registration about Ms Elna Paulette Lafortune, you can see
that in less than TWO months, SIX companies were established.....
Questions : 
- Are these very new companies related in any way with Giza Device LTD ?
- Do they need so many differents companies to play with fund raised in Giza Device Pre-ICO and coming ICO?
These are some questions im asking myself now :-(

**Comment by KazanGi** [comment]
Gathered many info and can say that the only REAL TEAM in this project was the Tech team from
Third Pin LTD.

**Comment by dalim927** [comment]
From Mark Fike Giza Device on Telegram Chat Group.
Hello guys. Karina pulled me out of my day off :) I worked a lot time before and I want to have a rest, but now I have to look for new developers. We have 2 company offers:
1. German 
2. Malaysian
Most likely, we will choose the first, as these guys inspire confidence in us. The final result you will learn on Monday. Our programmer will add their names and contacts to our site.
I do not give my contact phone, because I do not see the point. I now work a lot and at night too, why do I need calls from all investors? I can agree on a personal meeting with large investors.
About the Third Pin…. I can say next: I regretted contacting them. They demanded an advance of $ 1,500,000 to create MVP! This despite the fact that the rate fell! Moreover, they did not provide adequate information on where and how the device will be manufactured. No details. By the way, the ETH did not suit them either , they wanted to receive a bank transfer from me. I invited them to meet in London, but they refused.
I want to add one more important thing: I worked on this project for a long time, do you really think I'll leave everything now? I love Giza and will do everything to make it the best hard wallet in the world. Thank you for believing in me and supporting me!👍
Hope I have dispelled your doubts. You can ask me any questions in the chat now, pm or write to my official email 
gizadevicecoo@gmail.com

**Comment by KazanGi** [comment]
Investors join this channel. At least we will have a place for all us to look for any possibility all together. 

Here is a rescue group in case the worse happened if the main Giza channel disappears. 
Feel free to join

https://t.me/joinchat/EfZurBHRk2Cz9Sg6-5pb2w

**Comment by KazanGi** [comment]
WANT TO HIGHTLIGHT that ThirdPin LTD is helping the investors on Giza-rescue telg group.
I till now they have proved that they are not implicated in this scam.

**Comment by KazanGi** [comment]
Hi everyone, 

Guys, can we have your help to get awareness on twitter Exchanges about Giza Device? 
Could you please take a little time to retweet. Many thanks for your help and support

This is my tweet : 
URGENT SCAM ALERT GIZA Device PLS Help investors and stop them from withdrawal with your Exchange. Thank you. Wallet Address  0x5505b8415A83f8C190c02458bd8Ec0eFeD15642e
Contract  Address  0x1A836128518533C4aA1a21E178cDEadbA30Addb8

https://twitter.com/FiatLucs/status/965237584845791232

https://twitter.com/FiatLucs/status/965237355937452032

https://twitter.com/FiatLucs/status/965237273829789696

**Comment by KazanGi** [comment]
plse upvote reddit post, many thanks 👍 

https://www.reddit.com/r/icocrypto/comments/7w7x6c/giza_device_red_flags_beware_of_scam/

**Comment by KazanGi** [comment]
last update about Giza scam : Today 3 mars 2018

For 2 days now, from the telegram Giza official,  : 
- Giza logo has been removed, 
- Group name Giza removed (new name is NAME) 
- AND all admins vanished. 
- Wallet being drained off

**Comment by KazanGi** [comment]
📍First of all many THANKS 👏🙏to Nicolas (Giza investor) for taking from his time to produce 
this complete synthesis report about Giza Device scam. 

📍People don’t hesitate to post this report everywhere over the net to bring into light this scam and Help crypto investors not to fall into this scam, as Giza might continue with their plan to implement the main ICO in few months. 

📌Full report : 👇

❎ https://drive.google.com/open?id=1EpGo0dS3nZbyutL3fN-m1dqZl768Y8Ix

**Comment by KazanGi** [comment]
Hey people here the last new on Giza SCAM investigation : 

Cryptocurrency scammers run off with more than $2 million after ditching their investors journalist Arjun Kharpal from CNBC

https://www.cnbc.com/2018/03/09/cryptocurrency-scammers-of-giza-make-off-with-2-million-after-ico.html

Other articles : 

https://www.pymnts.com/news/security-and-risk/2018/scammers-launch-fake-ico-steal-2m-investors-giza/
https://walletinvestor.com/magazine/early-investors-lost-2-million-usd-to-scammers-running-a-fake-ico/


https://hype.codes/another-scam-ico-robbed-2-mln-worth-cryptocurrency

https://cryptonews.com/news/another-ico-makes-off-with-more-than-usd-2-million-1388.htm

https://www.digitaltrends.com/computing/startup-steals-millions-from-initial-coin-offering/

https://steemit.com/busy/@xplosive/the-newest-cryptocurrency-scam-burned-2-4-million-dollars

https://bitrazzi.com/scammers-at-it-again-cryptocurrency-investors-scammed-of-2-million-in-a-fake-ico/

https://www.pymnts.com/news/security-and-risk/2018/scammers-launch-fake-ico-steal-2m-investors-giza/

https://cryptocoremedia.com/cryptocurrency-scammers-get-away-2-million-booty/

https://coindoo.com/scammers-steal-2m-worth-of-ether-in-fake-ico/?ref=coinwisdom.org

http://coinwisdom.org/79722-scammers-steal-2m-worth-of-ether-in-fake-ico/

http://f-g-c.com/cryptocurrency-scammers-of-giza-make-off-with-2-million-after-ico/
