### ISSUE TITLE
WePower - Due diligence

### ISSUE THREAD

**Issue by edxz** [ico-check/ico-check#39]
# [WePower](https://wepower.network/) (WPR)

## Team
- Nikolaj Martyniuk (Co-Founder, Energy) - 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/nikolaj-martyniuk-7b007a9/)
- Artūras Asakavičius (Co-Founder, Investments) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/arturasasakavicius/)
- Kaspar Kaarlep (CTO, Energy) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/kaspar-kaarlep-76268b28/)
- Heikki Kolk (Energy IOT Expert) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/heikki-kolk-580291136/)
- Mantas Aleksiejevas (Marketing and sales) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/mantasaleks/)
- Lukas Kairys (Smart contracts consultant) - Jun 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/lkairys/)
- Aukse Siaudzionyte (Content and social media manager) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/aukse/)
- Asta Kybartaitė (Community & social media manager) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/asta-kybartaite-69686b101/)

## Team members with no mention of WePower in their Linkedin profiles:
- Liraz Siri (Security expert) | [Linkedin profile](https://www.linkedin.com/in/liraz/) **does not mention WePower**
- Steven Meersman (Energy markets) | [Linkedin profile](https://www.linkedin.com/in/stevencgmeersman/) **does not mention WePower**
- Dr. Tadas Jucikas (Data Scientist) - Sep 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/tjucikas/) **does not mention WePower**
- Vytautas Alkimavičius (Senior software engineer) | [Linkedin profile](https://www.linkedin.com/in/vytautas-alkimavicius/) **does not mention WePower**

### Advisors
- Rene Fischer (Advisor - Brand Strategy) | [Linkedin profile](https://www.linkedin.com/in/fischerrene/)
- Gytis Labasauskas (Advisor, growth and user acquisition) | [Linkedin profile](https://www.linkedin.com/in/gytislabasauskas/)
- Nimrod Lehavi (Payments advisor) | [Linkedin profile](https://www.linkedin.com/in/nimrodlehavi/)
- Jon Matonis (Blockchain advisor) | [Linkedin profile](https://www.linkedin.com/in/jonmatonis/)
- Eyal Hertzog (Blockchain advisor) | [Linkedin profile](https://www.linkedin.com/in/hertzog/)
- David Cohen (Energy Advisor)
- Trevor Townsend (Energy Advisor) | [Linkedin profile](https://www.linkedin.com/in/trevortownsend/)
- Geoffrey Riggs (Marketing & Communications Advisor) | [Linkedin profile]()

### Investor
- Darius Rugevicius (Investments) | [Linkedin profile](https://www.linkedin.com/in/dariusrugevicius/)
- Henri Laupmaa (Investments) | [Linkedin profile](https://www.linkedin.com/in/henrilaupmaa/)
- Aaron Bichler (Investments) | [Linkedin profile](https://www.linkedin.com/in/aaronbichler/)
- Saber Aria (Investments) | [Linkedin profile](https://www.linkedin.com/in/saaria/)
- David Drake (Investments) | [Linkedin profile](https://www.linkedin.com/in/ldjcapital/)

### WePower Limited  
**Company address:**
Holo Limited          
Suite 23            
Portland House         
Glacis Road          
Gibraltar GX11 1AA          

**Company Number:** 115971    

## Smart contract
- [Contract on Github](https://github.com/WePowerNetwork/wepower-contracts)

## Github
- [WePower](https://github.com/WePowerNetwork)

### Commits
- [Commit activity](https://github.com/WePowerNetwork/wepower-mvp/graphs/commit-activity)

## Product
- [MVP prototype](http://platform.wepower.network/landing)

## Vesting
- Team tokens are vested for 3 years
- Vesting schedule for advisors tokens ??
- [Contract on Github](https://github.com/WePowerNetwork/wepower-contracts) - To check advisors tokens in the smart contract

### Token distribution
![wepower-distribution](https://user-images.githubusercontent.com/32852887/35545354-0b43e5b8-056f-11e8-88ad-a81a523d76c4.png)

### Token allocation
![wepower-allocation](https://user-images.githubusercontent.com/32852887/35545358-0f60765c-056f-11e8-80ae-cf159c2e2aed.png)

## Flags
**Real Team:** ✅ 
**GitHub:** ✅   
**Smart Contract:** ✅    
**Working Product:** ❌  a demo
**+2 yr Vesting for team:** ✅
**Vesting for Advisors:** To check in the smart contract
**Have a company:** ✅           
**Transparent:** -   

# IcoCheck
- Discuss this ICO and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by larin92** [comment]
any news? it's coming pretty soon

**Comment by icochecker** [comment]
@larin92 i will update the issue today 🙂
