### ISSUE TITLE
Spectre - Due diligence

### ISSUE THREAD

**Issue by hterrence** [ico-check/ico-check#4]
Company's website: https://spectre.ai/

**Comment by icochecker** [comment]
# Spectre (SXD)

## Company
[SPECTRE DEVELOPMENT LIMITED](https://brainbot.li/)            
19 Waterfront Drive                 
Road Town VG1110               
Tortolla       
BVI     
**Registration Number:** 1952564             
            
### Linked to: 
- [Neuchâtel Partners](http://www.neuchatelpartners.com/contact), Akropoleos, 66 Akropoleos Tower,Flat/Office 10 Strovolos,2012, Nicosia, Cyprus

- [NEUCHATEL LTD](https://beta.companieshouse.gov.uk/company/08245873), St Georges House, 6th Floor, 15 Hanover Square, London W1S 1HS, England         

## Smart contract
- [Contract on github](https://github.com/spectre-ai/spectre-tokensale)

> **SpectreSubscriberToken:** This is the token issued during the contribution period.      
**SpectreUtilityToken:** This is the Spectre Utility Token.      
**SpectreDividendToken:** This is the Spectre Dividend Token

## Github
- [Repository](https://github.com/spectre-ai)

## MVP
- [Spectre Trading Platform](https://dapp.spectre.ai/login.php)

## Vesting
- Management (15%) - 6 month vesting

**Comment by biggandalf** [comment]
This company does not seem to be legally compliant. They are likely considered an ATS an Alternative Trading System and need a license for it. The dividend token is also problematic

**Comment by biggandalf** [comment]
They also blocked me after inquiring about these issues. Doesn't reflect way.

**Comment by biggandalf** [comment]
They also blocked me after inquiring about these issues. Doesn't reflect well.
