### ISSUE TITLE
Digitex - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#40]
# [Digitex](https://digitexfutures.com/) (DGTX)

## Team
- Adam Todd (Founder & CEO) | [Linkedin profile](https://www.linkedin.com/in/adam-todd-digitex/)
- Mickael Salabi (CFO) | [Linkedin profile](https://www.linkedin.com/in/mickaelsalabi/) **does not mention Digitex** | **No CFO experience** | **Dev to CFO?**
- Yuri Hideaki (Ethereum Developer) | [Linkedin profile](https://www.linkedin.com/in/yuri-hideaki-549b32147/) **does not mention Digitex** | Freelancer
- Justin Mc Bride (Business Development)
- Jackie Losey (Marketing & Outreach) | [Linkedin profile](https://www.linkedin.com/in/jackie-losey-62697a144/) **does not mention Digitex**
- Lee Mayne (Design/UI) | [Linkedin profile](https://uk.linkedin.com/in/leemayne) **does not mention Digitex**

### Advisors
- John Preddy (Technical Advisor) | [Linkedin profile](https://www.linkedin.com/in/WhyLose)

### Contractor
[Plataformatec](http://plataformatec.com.br/) (Software company)      
Rua Marília, 40          
São Paulo - SP, Brazil        
+55 11 2339-0708             

## Company
Digitex, Ltd.      
Global Gateway 8         
Rue de la Perle        
Providence        
Mahe          
Seychelles        

## Smart contract
- [Contract on Github](https://github.com/DigitexFutures/DigitexTokens)

## Github
![digitex-joined-github](https://user-images.githubusercontent.com/32852887/34955339-3a42f5a8-fa24-11e7-8148-1af856d32302.png)

- Joined GitHub on January 15, 2018
- [Digitex](https://github.com/DigitexFutures)

## Product
- No working product
- [Video demo](https://vimeo.com/digitex)

## Vesting
*Here put information where vesting information was found and attach screenshots.*

## Additional info
*Here put additional comments about the company, with links when possible*

**Comment by adrianhara** [comment]
Fyi: I wrote platformatec to ask about their relationship with digitex. No answer whatsoever.
