### ISSUE TITLE
Dadi - Background check

### ISSUE THREAD

**Issue by royalgarter** [ico-check/ico-check#43]
# [Dadi](dadi.tech)

## Team
[Joseph Denne](https://www.linkedin.com/in/josephdenne/)
The visionary behind DADI’s decentralized architecture and web services.
He is an expert in multi-agent and blockchain technologies as well as big data and machine learning. He was responsible for Symphony CMS and has 20+ years experience developing data and content platforms.
Joseph was previously Group Technical Director for the Leo Burnett Group, the Founder of Airlock (a multi-award winning technology company), the Technical Director at Chime Communications and a member of the technology board at the BBC. His work is known across the industry and has been recognised with multiple Webby, Lovie, Emmy, Sony and Bafta awards.

[Chris Mair](https://www.linkedin.com/in/chrismair/)
Chris is a strategist and an early blockchain enthusiast, having first invested in Bitcoin in 2011.
He is a founder of DADI and is the key architect behind the decentralized business strategy. Prior to DADI he was a partner at London based technology company Airlock, where he headed the strategy division.
Before joining Airlock, Chris was the Global Head of Digital Technology for fashion brand Diesel where he was responsible for the development and implementation of the brand’s digital strategy across 33 markets worldwide.

## Company
*Here put company information if company exsits. Also provide links (and possibly screenshots) where it can be verified that company exists*

## Smart contract
https://github.com/dadi/contracts
https://etherscan.io/address/0xfb2f26f266fb2805a387230f2aa0a331b4d96fba#code

## Github
https://github.com/dadi

## Product
*Here put link to the product if exists and attach screenshots.*

## Vesting
*Here put information where vesting information was found and attach screenshots.*

## Additional info
*Here put additional comments about the company, with links when possible*

**Comment by vmiroshnik** [comment]
![image](https://user-images.githubusercontent.com/12794805/35188439-fcc3db2a-fe3d-11e7-9860-0831990d55e1.png)

**Comment by HomeY** [comment]
The following DADI companies will be Token Issuing Entities for the Private sale and Crowdsale:
DADI Tech Limited (a company limited by shares registered in England and Wales [Company No: 11159551])
DADI Cloud Limited (a company limited by guarantee registered in England and Wales [Company No: 11159550])

![image](https://user-images.githubusercontent.com/1996332/35237521-382bf22e-ffab-11e7-97b3-26ee0d15824e.png)
https://beta.companieshouse.gov.uk/company/11159551

![image](https://user-images.githubusercontent.com/1996332/35237556-4bf92f42-ffab-11e7-8445-43e2fc335937.png)
https://beta.companieshouse.gov.uk/company/11159550

**Comment by HomeY** [comment]
![image](https://user-images.githubusercontent.com/1996332/35237615-7f9f13f2-ffab-11e7-9bfb-a289684c119b.png)

**Comment by coinbala** [comment]
This seems to be a proves scam?

**Comment by angryolk** [comment]
why scam?

**Comment by coinbala** [comment]
https://www.reddit.com/r/CryptoMarkets/comments/7ojbaf/warning_dadi_ico_is_a_proven_scam_they/
![ux1zcmk](https://user-images.githubusercontent.com/35730440/35280618-9fd6523c-0048-11e8-8ef4-a612e485b9f6.png)

**Comment by JayICO** [comment]
Scam then?

**Comment by JayICO** [comment]
What is the status of this ICO? Are they worth it?

**Comment by angryolk** [comment]
@coinbala  their announcement about plagiarised here:
https://medium.com/@daditech/community-update-c3df86acb1e0
and here:
https://eduardoboucas.com/blog/2018/01/07/dadi-crowdsale.html
