### ISSUE TITLE
FundRequest - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#45]
# [FundRequest](https://register.fundrequest.io/) (FND)

## Team
- Karel Striegel (Founder & CEO) - Sep 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/karelstriegel/) | [Twitter](https://twitter.com/TheCharliez) | [Github](https://github.com/karelstriegel)
- Davy Van roy (Co-founder & CTO) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/davyvanroy/) | [Twitter](https://twitter.com/DavyVanRoy) | [Github](https://github.com/davyvanroy)
- Gerbet Vandenberghe (Co-founder & COO) - Jun 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/gerbertvandenberghe/) | [Twitter](https://twitter.com/gillepils) | [Github](https://github.com/gerbert-vandenberghe)
- Tim Dierckxsens (Co-founder & CSO) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/timdierckxsens/) | [Twitter](https://twitter.com/TimDierckxsens) |
- Steve Maris (Core Developer) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/steve-maris-7b26b652/) | [Github](https://github.com/Simsteve7)
- Quinten De Swaef (Core Developer) - Oct 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/quinten-de-swaef-562a8826/) | [Twitter](https://twitter.com/QuintenDes) | [Github](https://github.com/Qkyrie)

### Advisors
- Lasse Clausen (Token launch and token economics) | [Linkedin profile](https://www.linkedin.com/in/lasseclausen/) | [Twitter](https://twitter.com/lalleclausen)
- Christopher Heymann (Technology and token economics) | [Linkedin profile](https://www.linkedin.com/in/christopher-heymann-baa51828/)
- Nico Haelterman (Technical Analyst) | [Linkedin profile](https://www.linkedin.com/in/nico-haelterman-2b60121/)
- Thomas Matthys (Financial Advisor) | [Linkedin profile](https://www.linkedin.com/in/thomasmatthys/) | [Twitter](https://twitter.com/t_matthys)
- Thomas Graham (Marketing Advisor) | [Linkedin profile](https://www.linkedin.com/in/tomgtgraham/) | [Twitter](https://twitter.com/tomgtgraham)

### FundRequest OÜ
**Registered Address:**    
Pärnu mnt 141-59      
Tallinn city, Harju county, 11314        
Estonia       
**Registry code:** 14354397       
**VAT number:** EE102034783  
**E-mail address:**  info@fundrequest.io

#### Right of representation
**Management board member:** Tim Dierckxsens        
**Management board member:** Gerbert Luc E Vandenberghe      
**Management board member:** Karel Gerard A Striegel      
**Management board member:** Davy Van Roy      

#### Legal status
**Entry 1:**	Legal form is osaühing [private limited company]      
**Entry 1:**	Articles of association have been approved on 16.10.2017      
**Entry 1:**	Financial year begins on 01.01 and ends on 31.12        

- [E-Business Register ](https://ariregister.rik.ee/index?lang=eng)    

## Smart contract
- [Contract on github](https://github.com/FundRequest/contracts/tree/master/contracts)
- [Security audit report](ob/master/2018-02-06%20-%20Least%20Authority%20-%20ICO%20Contracts%20Audit%20Report.pdf)

## Github
- [FundRequest](https://github.com/FundRequest)

## Product
- [Alpha on testnet](https://alpha.fundrequest.io/)

## Vesting
- Team tokens vest over 2 years with a 6 month cliff
- Advisors tokens vest over 6 month with a 3 month cliff
- [Codified vesting on Github](https://github.com/FundRequest/vesting-wallets)

## Additional info
- **The Founder was completely transparent during the due diligence process**

### Token distribution
![fundrequest-distribution](https://user-images.githubusercontent.com/32852887/35313923-46c1efb4-00c3-11e8-865b-ee12d64ecdd9.png)

### Token allocation
![fundrequest-allocation](https://user-images.githubusercontent.com/32852887/35313931-4ace0f66-00c3-11e8-85d6-0d961c4cf9eb.png)

## Q&A
![fundrequest-qa-1](https://user-images.githubusercontent.com/32852887/35189527-5e5b4ad6-fe4c-11e7-8e8a-114f291bb395.png)
![fundrequest-qa-2](https://user-images.githubusercontent.com/32852887/35189528-607654fa-fe4c-11e7-8731-c0e582804ed4.png)
![fundrequest-qa-3](https://user-images.githubusercontent.com/32852887/35189530-61ff298c-fe4c-11e7-818f-376d48980447.png)

# Flags
**Real Team:** ✅   
**GitHub:** ✅   
**Smart Contract:** ✅    
**Working Product:** ✅    
**+2 yr Vesting for team:** ✅   
**Have a company:** ✅             
**Transparent:** ✅    

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by karelstriegel** [comment]
My team made me aware of your review, thanks a lot for taking the time to really go into the details, much appreciated.

**Comment by MrNicodemuz** [comment]
@karelstriegel any chance to still register for the token sale?

**Comment by karelstriegel** [comment]
Hi @MrNicodemuz , I'm afraid that will be hard, we had to close our whitelist at 6K. Presale is 100% allocated and we have a presale waitlist of more then $6M, which is what we are looking to raise in  the public sale. I'm afraid you will have to wait until after the token sale to get your hands on a couple of FND's.

**Comment by karelstriegel** [comment]
Small update, in the meantime the audit of the smart contracts is done.
You can find a summary in our blog post here : https://blog.fundrequest.io/security-audit-report-1-17b76d8edc3b
or the full report here : https://github.com/FundRequest/audit-reports/blob/master/2018-02-06%20-%20Least%20Authority%20-%20ICO%20Contracts%20Audit%20Report.pdf
