### ISSUE TITLE
REMME - Due diligence

### ISSUE THREAD

**Issue by larin92** [ico-check/ico-check#50]
# [Remme](https://remme.io/) (REM)

## Team
- Alex Momot (CEO & Founder) - 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/alex-momot-93596b32)
- Kate Pospelova (CMO & Co-founder) - 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/kate-pospelova-6153a536)
- Taras Emelyanenko (System Architect) - Mar 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/taras-emelyanenko-97055047)
- Jan Keil (Business Development Adviser) - Sep 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/jan-keil-2011a61)
- Anatolii Padenko (Smart Contract Engineer) - Jun 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/anatolii-padenko-60322b83)
- Iryna Slobodianiuk (Legal) - 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/iryna-slobodianiuk-75542689/)
- Zoya Danilina (Social Media Specialist) - 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/zoya-danilina-b40bbb85/)

## Team members that recently joined Remme
- Roman Kravchenko (CTO) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/romankrav4)
- Oleksii Baranovskyi, PhD (Chief Cybersecurity Scientist) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/oleksiibaranovskyi/)
- Eugene Babichenko (DApp Engineer) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/eugenebabichenko)

## Team members with no Linkedin profiles:
- Yevhenii Turanov (Legal) **No linkedin Profile**
- Sergii Androsiuk (Community Support) **No linkedin Profile**

### Advisors
- Nick Bilogorskiy (Security Advisor) | [Linkedin profile](https://www.linkedin.com/in/bilogorskiy/)
- Prof. Roman Oliynykov (Cryptography Advisor) | [Linkedin profile](https://www.linkedin.com/in/oliynykov/)
- Andrey Zamovskiy (Advisor, Ethereum Guru)
- Stepan Gershuni (Technical Advisor) | [Linkedin profile](https://www.linkedin.com/in/sgershuni/)
- Vitaliy Bulychov (Investments Advisor) | [Linkedin profile](https://www.linkedin.com/in/vitaliy-bulychov-839aa543/)
- Gordon Einstein (Legal Advisor) | [Linkedin profile](https://www.linkedin.com/in/gordoneinstein/)
- Artem Afian (Legal Advisor) | [Linkedin profile](https://www.linkedin.com/in/afian/)
- Nestor Dubnevych (Legal Advisor) | [Linkedin profile](https://www.linkedin.com/in/nestor-dubnevych/)

### REMME CAPITAL LTD
**Registered Address:**              
QUIJANO & ASSOCIATES (BVI) LIMITED               
Quijano Chambers      
P.O. Box 3159       
Road Town       
Tortola      
British Virgin Islands      

**Registration Number:** 1957950            
                 
#### [BVI Certificate Verification](http://www.bvifsc.vg/en-gb/divisions/registryofcorporateaffairs/certificateverification.aspx)      
- Certificate ID missing

## Smart contract
- [Deployed - View on etherscan](https://etherscan.io/address/0x83984d6142934bb535793a82adb0a46ef0f66b6d#code)

## Github
- [Remmeauth](https://github.com/Remmeauth)

## Product
- [Demo](https://demo.remme.io/)

![image](https://user-images.githubusercontent.com/17257638/35312732-a3995734-00c5-11e8-99b1-a9add3cc813d.png)

![remme-p1](https://user-images.githubusercontent.com/32852887/36128476-db4b4866-1062-11e8-84c9-6d9fdb2ce39e.png)

![remme-p2](https://user-images.githubusercontent.com/32852887/36128479-ddfe8208-1062-11e8-84db-c4bdc2696d35.png)

## Vesting
- Team and founders tokens vest over 2 years with a 6 month cliff
- 10 % of Partners and advisors tokens will vest over 6 month with 3 month cliff
- [Vesting contract on Github](https://github.com/Remmeauth/Vesting) but not deployed. - **Added on 12 Feb 2018**
- No vesting for team tokens in the deployed contract

![remme-vesting](https://user-images.githubusercontent.com/32852887/35478608-d00db3f4-03e1-11e8-9134-779b0af4c727.png)

![remme-vesting-codified](https://user-images.githubusercontent.com/32852887/35478800-22bc62f8-03e7-11e8-971b-c03f81cda85b.png)

#### Public sale: Feb 13 20:00 UTC until Mar 13 20:00 UTC or the hard cap is reached.

- [Infopulse partners with Remme for Blockchain Innovations](https://www.infopulse.com/news/infopulse-partners-with-remme-for-blockchain-innovations/)
- [Strategic partnership: REMME and SSFTIF](https://medium.com/remme/strategic-partnership-remme-and-ssftif-ukrinmash-d44327f818ac)

### Token distribution
![image](https://user-images.githubusercontent.com/17257638/35312801-fd6bf4ce-00c5-11e8-8c89-b27f246b8c08.png)

### Token allocation
**Research and Development:** 35%      
**Business development:** 25%      
**Operations:** 20 %     
**Marketing:** 15%    
**Legal:** 5%     

## Q&A
![remme-qa-1](https://user-images.githubusercontent.com/32852887/35478605-c809de1c-03e1-11e8-8838-f0f2fa066e4a.png)
![remme-qa-2](https://user-images.githubusercontent.com/32852887/35478606-cbb748ba-03e1-11e8-84c6-6578b6d34d01.png)

# Flags
**Real Team:** ✅  
**GitHub:** ✅   
**Smart Contract:**  ✅  
**Working Product:** ❌    
**+2 yr Vesting for team:** ❌  Team tokens vest over 2 years. Not coded in the deployed smart contract.
**Have a company:** ✅             
**Transparent:** -    

# IcoCheck
- Issue added to [https://icocheck.io/in-review](https://icocheck.io/in-review)
- Discuss this upcoming ICO and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by coinbala** [comment]
Im interested in this one too, need more research

**Comment by coinbala** [comment]
My rating is complete and had great feedback from their CMO

[remme.pdf](https://github.com/ico-check/ico-check/files/1662308/remme.pdf)

**Comment by nistic** [comment]
As of right now their prototype is broken and they have no estimated fix date.

<img width="978" alt="1" src="https://user-images.githubusercontent.com/7002432/35475818-d622deae-03a5-11e8-90fa-673b389d09a9.png">
<img width="977" alt="2" src="https://user-images.githubusercontent.com/7002432/35475817-d60a0f00-03a5-11e8-9e80-5e7634496934.png">

**Comment by larin92** [comment]
When I've tested it 4 days ago it seemed working. What exactly happened when you tested it?

**Comment by nistic** [comment]
A password was required to add it to the OSX system keychain. They said the password was sent with the email but the email did not contain a password. I then asked them about the password and got the above response.

**Comment by larin92** [comment]
presale starts tomorrow. would be nice to get a github review. at least github, please.

**Comment by icochecker** [comment]
@larin92 i will add more info to the issue in few hours, and push it to icocheck.io 🙂

**Comment by larin92** [comment]
[https://cdn.discordapp.com/attachments/406546689386872832/407546581173403649/image.png](url)

**Comment by nistic** [comment]
Ironwood Research Group AMA with the CEO of Remme - https://www.youtube.com/watch?v=sDHbTFPExhs

**Comment by shumail92** [comment]
@icochecker I think they have now deployed smart contract. But not sure about the vesting schedule implementation in contract.
https://etherscan.io/address/0x83984d6142934bb535793a82adb0a46ef0f66b6d#code
