### ISSUE TITLE
Gimmer - Background check

### ISSUE THREAD

**Issue by ryanprice** [ico-check/ico-check#51]
# [Gimmer](https://token.gimmer.net/) (GMR)
Automated Crypto-trading bot platform

## Team
- Philipe Comini (Co-founder & CEO) - Dec 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/pcomini/)
- Pérsio Flexa (Co-founder & CTO) - Dec 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/persio-flexa/)
- Paul Lindsell (COO) - Jun 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/paullindsell/)
- Arrykrishna Mootoovaloo (Data scientist) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/arrykrishna/) **shows that he currently is a PhD Student at Imperial College London**
- Lucas Assis (Full stack Developer & Crypto Trader) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/distrolucas/)
- William Xavier (Full stack Developer & Crypto Trader) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/william-xavier-sousa-79580431/)
- Joao Mascarin (Commercial Director Europe) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/jmascarin/)
- Masaichi Hasegawa (Commercial Director Asia ) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/masaichi-hasegawa-67056633/)
- Michel Comini (Marketing Director ) - 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/mcomini/)
- Olga Rusakova (Head of PR - Russia) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/olga-rusakova-7b515214/)
- Rok Gorjan (Bounty & Community Manager) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/rok-gorjan-69451563/)
- Evgheny Turvinenko (Head of ICO Strategy - Russia) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/eturvinenko)
- Benjamin Vitáris (Journalist) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/benjamin-vit%C3%A1ris-0b7389124/)
- Joao Guilherme Mascarin (UX Researcher) - Mar 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/joao-guilherme-mascarin-950812144/)
- Beatriz Marques (Community Manager) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/biarox/)

### Advisors
- Margaux Avedisian (PR Strategy ) | [Linkedin profile](https://www.linkedin.com/in/margauxwithanx/)
- Alexander Kravets (Advanced Trading Platform Technologies) | [Linkedin profile](https://www.linkedin.com/in/alexander-kravets-8075179/)
- Claudio Lima, Ph.D. (Blockchain, Machine Learning/AI) | [Linkedin profile](https://www.linkedin.com/in/crlima10/)
- Justin Jovanovic (ICO and Crypto-Strategy Adviser) | [Linkedin profile](https://www.linkedin.com/in/justin-jovanovic-7a48b8b6/)
- Lex Sokolin (Fintech, Futurism and Autonomous research) | [Linkedin profile](https://www.linkedin.com/in/alexeysokolin/)
- Marcus Killick (DLT Regulations and Legal Adviser) | [Linkedin profile](https://www.linkedin.com/in/marcus-killick-obe-85b8376/)
- Jitendra Chittoda (Smart Contract Security Adviser) | [Linkedin profile](https://www.linkedin.com/in/jchittoda/)
- Eleanor Barlow (Fintech, Business Strategy and Operational innovation) | [Linkedin profile](https://www.linkedin.com/in/eleanor-barlow-9b209b3/)
- Aman Sanduja (Crypto Trader and Blockchain speaker) | [Linkedin profile](https://www.linkedin.com/in/aman-sanduja-62982a81/)
- Harsh Jani (Blockchain Growth Hacking and ICO Marketing) | [Linkedin profile](https://www.linkedin.com/in/janiharsh/)

### P3 Limited  
**Company address:**          
Suite 23            
Portland House         
Glacis Road          
Gibraltar GX11 1AA       

**Company Number:** 116362      
**REID Number:** GICO.116362-6  

#### Directors
- Philipe Comini
- Persio Flexa
- Paul Lindesell

## Smart contract
- [Contract on Github](https://github.com/GimmerBot/gmr-token/tree/master/contracts)
- [Deployed - View on etherscan](https://etherscan.io/address/0xdf35a8572e8c107e17803f7af2fc48b6c226c6a4)

## Github
- [GimmerBot](https://github.com/GimmerBot)

## Product
- Demo available on [Windows, Mac, Linux](https://token.gimmer.net/#demo)

![gimmer-demo](https://user-images.githubusercontent.com/32852887/35939500-9a1d9872-0c4c-11e8-97fd-a31aa3c723cc.png)

![gimmer-live-performance](https://user-images.githubusercontent.com/32852887/35944649-6feeb14c-0c5d-11e8-89be-6f0b66ead4e5.png)

### Product question
![gimmer-code](https://user-images.githubusercontent.com/32852887/35773875-f414f46a-095e-11e8-9fdf-970098477676.png)

## Vesting
- Team and advisors tokens not coded in the smart contract.
- Team tokens vest over 3.5 years
- Vesting schedule for advisors tokens depends on their role. 

## Additional info
- US investors can't participate

### Token distribution
- 45% Gimmer’s Advisers
- 45% Business reserves
- 10% Core Team

[Source: WP page 18](https://token.gimmer.net/assets/docs/gimmer-wp-en.pdf)

### Token allocation
- 45% Development & Operations
- 35% Marketing & Acquistion
- 15% Founders & Team
- 5% Legal & Compliance

[Source: WP page 20](https://token.gimmer.net/assets/docs/gimmer-wp-en.pdf)

## Q&A
![gimmer-question-2](https://user-images.githubusercontent.com/32852887/35773742-c93b6dcc-095a-11e8-96b3-6bf576c369f7.png)
![gimmer-question-1](https://user-images.githubusercontent.com/32852887/35773740-c6a201a2-095a-11e8-9b86-3c15e12b58b0.png)
![gimmer-question-3](https://user-images.githubusercontent.com/32852887/35773745-e00ced14-095a-11e8-81b6-5a22662988c6.png)
![gimmer-q a](https://user-images.githubusercontent.com/32852887/35773712-234fecf8-095a-11e8-9989-49731769278f.png)

## Flags
**Real Team:** ✅ 
**GitHub:** ✅   
**Smart Contract:** ✅       
**Working Product:** ❌ Demo available   
**+2 yr Vesting for team:** ❌ Vesting not codified    
**Vesting for Advisors:** ❌ Vesting not codified
**Have a company:** ✅             
**Transparent:** ✅    

# IcoCheck
- Discuss this upcoming ICO and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by Formani4** [comment]
Q.....
Morning Friends. Admin I wanna ask some question. 
1, GMR tokens inside the Bot will be used as a main currency (i need to change Alt to GMR to trade, or I can trade alts directly?)?  
2. Will GMR be used as a platform token to reduce Fees (like in Binance for example)? 
3. Are there any bonuses for vesting (holding) GMR tokens (for example monthly +%?)
A.....
With the GMR tokens you can rent trading bots (or using a free bot is an option too). The bots will use your funds (You have to have funds/currency on your exchange. Gimmer doesn't touch your funds directly or hold your funds) across  the exchanges using API keys. Fees for bots can be changed from time to time (if the price per GMR will change a lot), but GMR will be the only paying method, so not really like BNB is used on Binance. There is no vesting bonus, but in my opinion, holding GMR would turn out to be rewardinf nevertheless.

**Comment by Formani4** [comment]
Q....
Do you plan to allocate GMR on Exchanges? Can you provide a list of Exchanges you plan to use?
A...
So far Gimmer bots can cover Bitfinex, Bittrex and Poloniex. There are more to come
GMR itself will be tradeable on exchanges too. From March 1st GMR will be on EtherDelta and IDEX, also more to come eventually
