### ISSUE TITLE
Play2Live - Due diligence

### ISSUE THREAD

**Issue by martin1551** [ico-check/ico-check#52]
# [Play2Live](https://play2live.io/en/) (LUC)

## Team
- Alexey Burdyko (Founder & CEO) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/alexey-burdyko-33a29316/)
- Dimitry Kochnev (COO) - Aug 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/kochnev/)
- Inna Moroz (CBDO) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/innamoroz/)
- Orhan Zeynalli (Blockchain CTO) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/orkhan-zeynally-0840a314a/)
- Alexey Kuznetsov (Lead developer streaming core) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/alexey-kuznetsov-7b75385a/)
- Maria Mavrekh (CMO) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/maria-mavrekhma/)
- Denis Shepetov (Lead developer streaming core) - 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/dshchepetov/)
- Alexey Galizdra (SMM lead) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/galizdra/)

## Team members with no Linkedin profiles:
- Pedy Hung (BDD Asia) | [Facebook](https://www.facebook.com/peidy.hung) | **No Linkedin Profile**
- Vladislav Arbatov (Head of data analysis department) | [Facebook](https://www.facebook.com/vladzima) | **No Linkedin Profile**
- Arseny Strizhenok (Marketing manager) | [Facebook](https://www.facebook.com/arseniy.strizh) | **No Linkedin Profile**
- Siarhei Medvedev (Head of legal) | [Facebook](https://www.facebook.com/profile.php?id=100011989845927) | **No Linkedin Profile**

### Advisors
- Can Yang | [Linkedin profile](https://www.linkedin.com/in/frandia/)
- Parker Fairfield | [Linkedin profile](https://www.linkedin.com/in/parkerfairfield/)
- David Drake | [Linkedin profile](https://www.linkedin.com/in/ldjcapital)
- Anton Agranovskiy | [Linkedin profile](https://www.linkedin.com/in/anton-agranovsky-b1183024/)
- Richard Kastelein | [Linkedin profile](https://www.linkedin.com/in/expathos/)
- Victor Martyn | [Linkedin profile](https://www.linkedin.com/in/victormartyn)
- Reuben Godfrey | [Linkedin profile](https://www.linkedin.com/in/reuben-godfrey-1a18055/)
- Pavel Pogodin | [Linkedin profile](https://www.linkedin.com/in/ppogodin/)
- Greg Limon | [Linkedin profile](https://www.linkedin.com/in/greg-limon-835a23b9/)
- Stan Milc | [Linkedin profile](https://www.linkedin.com/in/stan-milc-077962105/)

### Game Connect Ltd
**Registered Address:**     
19 Suite No. ADR    
4462 Giovanni Curmi Street    
Iklin IKL1071    
Malta    

- [Source - Malta company seach](https://rocsupport.mfsa.com.mt/pages/SearchCompanyInformation.aspx)
- [Source - Kompany global company intelligence](https://www.kompany.com/p/mt/c%2067439)

## Smart contract
- Will be released after the end of sale period

![screen shot 2018-01-27 at 01 06 18](https://user-images.githubusercontent.com/32852887/35465768-b4935aae-02fe-11e8-9533-5af21a7eb987.png)

## Github
- link is not officially published yet - after release of Alpha version (April 2018)

![screen shot 2018-01-27 at 01 05 09](https://user-images.githubusercontent.com/32852887/35465764-adbf868a-02fe-11e8-8679-1697f8d17016.png)
![play2live-github-2](https://user-images.githubusercontent.com/32852887/37018012-08582d68-2113-11e8-83d1-5e66c0f621a2.png)

## Product
- [MVP](https://p2l.tv/)

## Vesting
* information is provided in official whitepaper
* The funds stored in the Operations funds will be locked up for two years since the
beta version public release. The funds of the project team and the founders will be
vested during 2 years. The funds of the project partners will be vested during 3 years.

### Token distribution
![play2live-distribution](https://user-images.githubusercontent.com/32852887/35464440-35c49b14-02f6-11e8-975d-7bcec28b6cf8.png)

### Token allocation
![play2live-allocation](https://user-images.githubusercontent.com/32852887/35464443-3e250f82-02f6-11e8-9b05-23ae8322591d.png)

# Flags
**Real Team:** To verify   
**GitHub:** ❌   
**Smart Contract:** ❌ After pre-sale...   
**Working Product:** ❌    
**+2 yr Vesting for team:** ❌ 2 years vesting but no way to verify as smart contract is not deployed   
**Have a company:** To verify             
**Transparent:** -

**Comment by lopezm94** [comment]
They also publicly revealed future exchanges in telegram channel.
