### ISSUE TITLE
SP8DE - Due diligence

### ISSUE THREAD

**Issue by martin1551** [ico-check/ico-check#54]
# [SP8DE](https://sp8de.com/) (SPX)

## Team
- Alexey Kashirsky (CEO & Co-Founder) - Jun 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/alexey-kashirsky-166997b2/)
- Mikhail Krapivnoi (CIO & Co-Founder) | [Linkedin profile](https://www.linkedin.com/in/mikhail-krapivnoi-1601a1142/) **does not mention SPD8**
- Evgeny Borchers (CVO & Co-Founder) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/evgeny-borchers-53906168/)
- Alexander Baykiev (CMO & Co-founder) - Jun 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/alexander-baykiev-12654814b/)

### Advisors
- Artemy Zorin | [Linkedin profile](https://www.linkedin.com/in/temazorin/)
- Alexander Uglov | [Linkedin profile](https://www.linkedin.com/in/uglovs/)
- Norman Chou | [Linkedin profile](https://www.linkedin.com/in/normchou/)
- Lyubomir Serafimov | [Linkedin profile](https://www.linkedin.com/in/lserafimov/)

## Company 
- Team refused to give company info

![sp8de-company-1](https://user-images.githubusercontent.com/32852887/36135460-968729d8-108b-11e8-8431-68341baa55ad.png)
![sp8de-company-2](https://user-images.githubusercontent.com/32852887/36135461-98a14604-108b-11e8-9de4-97ea302645e6.png)
![sp8de-company-3](https://user-images.githubusercontent.com/32852887/36135462-9a1670cc-108b-11e8-9391-6c3a578a6471.png)

## Smart contract
- [Presale contract on github](https://github.com/SP8DE/smartly_smart)
- [Contract on github](https://github.com/SP8DE/smartly_smart/blob/master/smart_contract.txt)
- [Deployed contract](https://etherscan.io/token/0x30dda19c0b94a88ed8784868ec1e9375d9f0e27c?a=0xb25b0c093c1b9c2b44a2217da17756ff5dd1b81d#readContract)

## Github
- [SP8DE](https://github.com/SP8DE)
- 2 smart contract repository

![sp8de-github](https://user-images.githubusercontent.com/32852887/36135479-b07ce846-108b-11e8-8064-9de89d5e4871.png)

## Product
- No working product

![sp8de-roadmap](https://user-images.githubusercontent.com/32852887/36135615-a3ec30e0-108c-11e8-8e48-21e02234495f.png)

## Vesting
- Team claims that team tokens will vest over 1 year.

![sp8de-vesting](https://user-images.githubusercontent.com/32852887/36135441-6e77286c-108b-11e8-9cfb-15248b25a435.png)

### Iohk has no relationship with Sp8de
![sp8de-twitter](https://user-images.githubusercontent.com/32852887/36357367-521ae156-14fd-11e8-8b02-91a3aceae7c6.png)

- [Source on twitter](https://twitter.com/IOHK_Charles/status/951945340931883008)

### Token distribution
The entire token distribution will be 8,888,888,888 of which **3,655,555,558.4 (41.125%)** will be in the form of token sale and **3,455,555,552 (38.875%)** will be given as a jackpot to those who have participated in the “token sale” rounds. 

The rest of the tokens **1,777,777,778 (20%)** will remain with the team for the purposes of marketing,
advisory, and further development of the project (see the Token Proceeds Utilization section for further detailson the use of the proceeds from the token distribution).

### Token allocation
![sp8de-allocation](https://user-images.githubusercontent.com/32852887/36135715-2a725a9a-108d-11e8-99a9-a70ffb564a59.png)

# Flags
**Real Team:** - To verify       
**GitHub:** ✅          
**Smart Contract:** ✅       
**Working Product:** ❌        
**+2 yr Vesting for team:** ❌         
**Have a company:** ❌ Refused to give info                 
**Transparent:** ❌          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by psijmons** [comment]
Sp8de has released a new whitepaper (v4) and website that answers several of the above questions. 
It is a BVI (British Virgin Islands)-incorporated entity, MVP is expected in Q2 2018, the team has been expanded considerably with 1st class entrepreneurs. The jackpot assignments is a prime example of transparency. In my opinion, the warning sign on this ICO is way over the top and should be removed.
