### ISSUE TITLE
Refereum - Due diligence

### ISSUE THREAD

**Issue by 1897** [ico-check/ico-check#55]
# [Refereum](https://token.refereum.com/)

## Team
Dylan Jones https://www.linkedin.com/in/thedylanjones/
Alistair Doulin https://www.linkedin.com/in/doolwind/
Sloane Earl https://www.linkedin.com/in/sloane-earl-44810739/
Nick Klingsmith https://www.linkedin.com/in/nickklingensmith/
Brad Johnson https://www.linkedin.com/in/bradley-johnson
Mark Maratea https://www.linkedin.com/in/mark-maratea-73b9653/
Katie Williams https://www.linkedin.com/in/katielloydwilliams

## Company
*Here put company information if company exsits. Also provide links (and possibly screenshots) where it can be verified that company exists*

## Smart contract
- [Contract on etherscan](https://etherscan.io/address/0xd0929d411954c47438dc1d871dd6081F5C5e149c)

## Github
*Here put link to company's GitHub*
https://bitbucket.org/hfio/hfio

## Product
*Here put link to the product if exists and attach screenshots.*
https://refereum.com/Games
http://hyperfleet.io

## Vesting
*Here put information where vesting information was found and attach screenshots.*

## Additional info
*Here put additional comments about the company, with links when possible*

**Comment by bripto** [comment]
Smart Contract:
https://help.refereum.com/token-sale/where-can-i-get-info-about-your-smart-contract
