### ISSUE TITLE
Savedroid - Due diligence

### ISSUE THREAD

**Issue by martin1551** [ico-check/ico-check#57]
# [Savedroid](https://ico.savedroid.com/)

## 🔥🔥 UPDATE: 18 April 2018 - Website shows the following 🔥🔥
![savedroid-gone](https://user-images.githubusercontent.com/32852887/38931413-6114db00-4313-11e8-8c08-784ec040866c.jpg)

## 🔥🔥 UPDATE: 18 April 2018 - Twitter post from founders account 🔥
![savedroid-twitter](https://user-images.githubusercontent.com/32852887/38943914-d7204432-4332-11e8-9162-db8dc29123c4.png)

## 🔥🔥 UPDATE: 18 April 2018 - Empty Office 🔥
![savedroids-office-empty](https://user-images.githubusercontent.com/32852887/38950118-cd9aeb9e-4344-11e8-8f10-9a6088223700.jpg)

## Team
- Dr Yassin Hankir (Founder & CEO)
- Marco Trautmann (Founder & COO)
- Tobias Zander (Founder & CTO)
- Alla Brodski-Guerniero (Data Scientist)
- Lennart Czienskowski (UX Designer)
- Michael Fehse (CDO)
- Patrick Gotta (UX Designer)
- Sebastian Hoffmann (External Auditor)
- Alexandra Hoffmann (Head of Business Development & HR)
- Matthew Kirschnick (Senior Product Owner)
- Gautam Kuram Paramanik (Data Scientist)
- Jan Pleser (CMO)
- Sina Reubelt (Blockchain Partner Management)
- Michael Ryvlin (Lead Backend Architect)
- Patrick Taufer (Mobile Developer)
- Lucien Tavano (VP Internationalization)
- Stefan Telin (Customer Service)
- Ela Wenner (Head of Design)
- Lydia Witzmann (Digital Marketing Manager)
- Parna “Pari” Youssufzay (Customer Service)
- Bianca Duhrssen (Virtual Design Intern)
- Laura Schmidt (Social Media Intern)

-
## Company
**Registered address:**
savedroid AG
Eschersheimer Landstraße 121
60322 Frankfurt am Main

**Responsible staff (according to § 55 Abs. 2 RStV)**
- Dr. Yassin Hankir
- Marco Trautmann
- Tobias Zander 

Vorstandsvorsitzender: 
- Dr. Yassin Hankir 
Aufsichtsratsvorsitzender: 
- Debjit Datta Chaudhuri 

Registergericht: Frankfurt am Main / HRB 103480 USt-IdNr.: DE305382839 Kontaktdaten Besucheradresse: Deutsche Börse FinTech Hub, Hanauer Landstraße 121, 60316 Frankfurt am Main Telefon : 069 34 875 882 
[Full registration imprint](https://ico.savedroid.com/imprint/)

## Smart contract
*Here put e.g. link to contract address on etherscan*

## Github
[official github](https://github.com/savedroid)

## Product
Mobile Application
[iOS](https://itunes.apple.com/de/app/savedroid/id1155426185?mt=8)
[Android](https://play.google.com/store/apps/details?id=de.savedroid&hl=sk)

## Vesting
Vesting schedule is 5 years, linear over 20 quarters - coded in the smart contract. (Telegram)

## Additional info
- security audit by TUV Saarland
- additional penetration tests performed
- not avaiable for US investors

*Here put additional comments about the company, with links when possible*

## Q&A
![savedroid-qa-1](https://user-images.githubusercontent.com/32852887/36035566-8d9cce4e-0db7-11e8-8c7b-c20d529b1e15.png)
![savedroid-qa-2](https://user-images.githubusercontent.com/32852887/36035571-902086b0-0db7-11e8-97c3-c91f5e31905e.png)

# Flags
**Real Team:** - To check. Full background check to do.
**GitHub:** - Only 1 repo for the smart contract          
**Smart Contract:** -       
**Working Product:** - No testnet    
**+2 yr Vesting for team:** - To check
**Have a company:** - Check if directors are team members.                
**Transparent:** -

**Comment by easymonth** [comment]
why ico check didnt detect the scam earlier?

**Comment by icochecker** [comment]
@easymonth Checks were not fully done due to the shortage of time. To complete tag was still on. 😞 :disappointed:
