### ISSUE TITLE
Endor - Due diligence

### ISSUE THREAD

**Issue by rogersmarin** [ico-check/ico-check#64]
# [Endor](https://www.endor.com/) (EDR)

### Founding Members
- **Doron Alter** (Co-Founder & Chairman) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/doronalter) | [Twitter](https://twitter.com/doronalter)            
 Endor | Co-Founder & CEO - Mar 2014 - Dec 2017           
 Innovation Endeavors | Partner - 2011 - Mar 2014
 
- **Yaniv Altshuler** (Co-Founder & CEO) - Jan 2018 - Present  | [Linkedin profile](https://www.linkedin.com/in/yaniv-altshuler-73a31a/)      
 Endor | Co-Founder & CTO - Mar 2014 - Dec 2017 

- **Stav Grinshpon** (Co-Founder & CPO) - Nov 2017 - Present   | [Linkedin profile](https://www.linkedin.com/in/stavg/) | [Github](https://github.com/stavgrinshpon)        
Endor | Co-Founder & VP Engineering - Jun 2014 - Nov 2017

![endor-crunchbase-team](https://user-images.githubusercontent.com/32852887/36961748-03226834-204d-11e8-8565-bbf18b38a485.png)

![endor-crunchbase](https://user-images.githubusercontent.com/32852887/36959777-1f59c988-2044-11e8-886e-d984bebc8f66.png)
**Screenshot date:** 21 Feb 2018    
#### Source: [Crunchbase](https://www.crunchbase.com/organization/endor)

**Update - 5 Mar 2018:** Alex Petland was Recently added to the Founders list on [Crunchbase](https://www.crunchbase.com/organization/endor)
 
### Doron Alter's linkedin profile show that he is Chairman of Endor but is nowhere to be seen on [Endor.com](https://www.endor.com/) 

![endor-doron-chairman](https://user-images.githubusercontent.com/32852887/36512582-5c2f59d6-176b-11e8-9145-5f4c4415fe39.png)

### Team on [Endor.com](https://www.endor.com/)
![endor-team](https://user-images.githubusercontent.com/32852887/36512586-5fb844c8-176b-11e8-8395-eecc6e333978.png)

### Investors question
![endor-doron-question](https://user-images.githubusercontent.com/32852887/36513085-1aebe23e-176e-11e8-882b-c86a7ce33965.png)

### Reply from CEO Yaniv Altshuler
![endor-doron-statement](https://user-images.githubusercontent.com/32852887/36513001-9d52469c-176d-11e8-832d-09c7bba4681e.png)

### Team
- **Inbal Tirosh** (Co-Founder & COO) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/inbal-tirosh-9916927/)   
 Endor | VP Product Management - Mar 2017 - Nov 2017 

- **Dr. Arie Matsliah** - 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/arie-matsliah-5938374a/)
- **Shahar Somin** (Machine Learning Research Lead) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/shahar-somin-5522a98a/)    
Endor | Machine Learning & Algorithims Developer - Feb 2015 - Dec 2017

- **Lior Regev** (Big Data Developer) - Jan 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/lior-regev-22a256a2/) | [Github](https://github.com/liorregev)
- **Liat Yitshaki** (Operations Manager) - Feb 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/liat-yitshaki-a0950918/)

## Team members that recently joined Endor
- **Dr. Mihaela Ulieru** (Chief Alchemist) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/mihaelaulieru/)
- **Edo Eisenberg** (Customer Success Lead) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/edoeisenberg/)
- **David Shrier** (Vice Chairman) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/david-shrier/)

## Team members with no mention of Endor in their Linkedin profiles:
- **Prof. Alex Pentland** (Co-Founder) | [Linkedin profile](https://www.linkedin.com/in/alexsandypentland/) **does not mention Endor**
- **Dr. Goren Gordon** (Deep Learning Research Lead) | [Linkedin profile](https://www.linkedin.com/in/goren-gordon-5b2530/) **does not mention Endor**

### Advisors
- Ron Gross | [Linkedin profile](https://www.linkedin.com/in/ripper234/)
- Prof. Alexander Lipton | [Linkedin profile](https://www.linkedin.com/in/alexander-lipton-aa2256bb/)
- Dr. Daniel Tunkeland | [Linkedin profile](https://www.linkedin.com/in/dtunkelang/)
- Prof. Michael Bronstein | [Linkedin profile](https://www.linkedin.com/in/mbronstein/)
- Thomas Hardjono | [Linkedin profile](https://www.linkedin.com/in/hardjono/)
- Dr. Nuria Oliver | [Linkedin profile](https://www.linkedin.com/in/nuriaoliver/)
- Igor Gonta | [Linkedin profile](https://www.linkedin.com/in/igorgonta/)
- Guy Zyskind | [Linkedin profile](https://www.linkedin.com/in/gguyz/)

### Seed Round | USD 5M | Sep 16, 2014

- [Innovation Endeavors](http://www.innovationendeavors.com/)
- [Marker (Now part of Innovation Endeavors)](http://www.marker-llc.com/)

## Endor joins [MasterCard Start Path Accelerator](https://www.startpath.com/) - Apr 10 2017
- [Source](https://newsroom.mastercard.com/press-releases/mastercard-start-path-global-startups-forecast-a-fintech-future/)

### Endor Software Ltd.
**Registered office address:**      
Rehov Yosef Caro 30        
Tel Aviv, 6701434       
Israel     

**Corporation number:** 515070597       
**Incorporation Date:** 13 Apr 2014   

![endor-software-1](https://user-images.githubusercontent.com/32852887/36494005-31e3e834-1731-11e8-9360-812865a1d3df.png)
![endor-software-2](https://user-images.githubusercontent.com/32852887/36494007-33f264ac-1731-11e8-8151-0b5161f4bed9.png)

- [Company search Israel](https://ica.justice.gov.il/GenericCorporarionInfo/SearchCorporation?unit=8)

### Netz (International) Limited
**Registered office address:**     
GX11 1AA    
Gibraltar      

Private company limited by shares      
Incorporated and registered in Gibraltar      
**Company Number:** 116938         
**REID Number:** GICO.116938-24   
**Incorporation Date:** 15 Feb 2018
**Company Type:** Private Company Limited By Shares
**Status:** Active

#### Filings
- Feb 15, 2018 - Articles of association
- Feb 15, 2018 - Duplicate of certificate of incorporation
- Feb 15, 2018 - Memorandum of association
- Feb 15, 2018 - Application for registration (private company limited by shares)     

#### Netz (International) Limited is a fully owned subsidiary of Netz Forecasts Ltd., Israel.

![endor-gibraltar](https://user-images.githubusercontent.com/32852887/36486145-1cec19a0-171e-11e8-8524-e9b0e70db4c5.png)

- [Source](https://portal.kyckr.com/companySearch.aspx)

### Netz Forecasts Ltd.
**Registered office address:**      
Ha-Yakinton St 11
Ramat Yishay 3009500
Israel

**Corporation number:** 515778389       
**Incorporation Date:** 16 Jan 2018    
**Director:** Yaniv Altshuler

![netz-israel-1](https://user-images.githubusercontent.com/32852887/36493244-708f84be-172f-11e8-9119-9f5c87773ec6.png)
![netz-israel-2](https://user-images.githubusercontent.com/32852887/36493274-80f88206-172f-11e8-86b5-dfba3f9c9029.png)

- [Company search Israel](https://ica.justice.gov.il/GenericCorporarionInfo/SearchCorporation?unit=8)

### To audit
- [Deployed - View on etherscan](https://etherscan.io/address/0x0cefa429f7779ae137aa1976e416f2648f6f87b8#code)
- [Contract on github](https://github.com/EndorCoin/endor-crowdsale/tree/master/contracts)

> #### Was your smart contract audited by an independent cybersecurity company?
- Yes. Openzeppelin.

## Github
- [EndorCoin](https://github.com/EndorCoin)

## Endor protocol not connected to blockchain. Testnet not available.

![endor-roadmap](https://user-images.githubusercontent.com/32852887/36652892-fd337daa-1ab1-11e8-9577-761b0c4106af.jpg)

![endor-blockchain-1](https://user-images.githubusercontent.com/32852887/36647553-a8dd364e-1a87-11e8-9a7e-05cc063807aa.png)

![endor-blockchain-2](https://user-images.githubusercontent.com/32852887/36647555-ac8975fa-1a87-11e8-83e5-d28f5e893d40.png)

### N/A yet | Check smart contract for codified vesting

> ### What is the vesting schedule for Team and Advisors token?
- Token economy and terms will be published soon

> ### Is vesting for Team and Advisors coded in the smart contract?
- Smart contract details will be disclosed upon crowdsale

## Update 25 Feb 2018: 🔥🔥 Token economy was published but Vesting schedule for Team and Advisors tokens was omitted. 🔥🔥
![endor-vesting-1](https://user-images.githubusercontent.com/32852887/36652416-00d12dc0-1aaf-11e8-97ed-917312cdda24.png)
![endor-vesting-2](https://user-images.githubusercontent.com/32852887/36652418-02ca5822-1aaf-11e8-9445-86fa795ff9e6.png)
![endor-vesting-3](https://user-images.githubusercontent.com/32852887/36652421-046cb170-1aaf-11e8-9c02-44c57ecf8b0b.png)
![endor-vesting-4](https://user-images.githubusercontent.com/32852887/36652423-062c7842-1aaf-11e8-8e5e-4712e38df616.png)
![endor-vesting-5](https://user-images.githubusercontent.com/32852887/36652424-08298c7a-1aaf-11e8-8ab5-7c36a0f7e5e7.png)
![endor-vesting-6](https://user-images.githubusercontent.com/32852887/36652429-0984ba86-1aaf-11e8-9903-eddbefa9b6a4.png)
![endor-vesting-7](https://user-images.githubusercontent.com/32852887/36652431-0ae8d02e-1aaf-11e8-9352-2c27a1f5d113.png)
![endor-vesting-8](https://user-images.githubusercontent.com/32852887/36652433-0c5ce77e-1aaf-11e8-8739-7df1424c25a7.png)
![endor-vesting-9](https://user-images.githubusercontent.com/32852887/36652438-0f68fce6-1aaf-11e8-96c8-b53ccb5894fc.png)
![endor-vesting-10](https://user-images.githubusercontent.com/32852887/36652440-11410e46-1aaf-11e8-82c9-2e78a0a6b1af.png)
![endor-vesting-11](https://user-images.githubusercontent.com/32852887/36652445-13079ac4-1aaf-11e8-9920-b2386b1b144a.png)
![endor-vesting-12](https://user-images.githubusercontent.com/32852887/36652447-1499b016-1aaf-11e8-83d7-68a1095d6b0a.png)
![endor-vesting-13](https://user-images.githubusercontent.com/32852887/36652449-16ce8dde-1aaf-11e8-891c-aa13dcfbe7bf.png)
![endor-vesting-14](https://user-images.githubusercontent.com/32852887/36652450-194866c0-1aaf-11e8-9f4e-864a209b9c19.png)

### Token distribution scheduled for Q2 (Late May)
![endor-token-distribution](https://user-images.githubusercontent.com/32852887/38477144-7d4f4da0-3bb1-11e8-92b1-a851811d9d14.png)
 
### Intellectual Property
 
> #### Can i have details of any intellectual property which the company has created, registered or applied to register?
- [https://www.endor.com/social-physics](https://www.endor.com/social-physics)
- See the links of Google Scholar & Wikipedia of Prof Pentland and Dr Altshuler attached to our [Social Physics page on the website](https://www.endor.com/social-physics)

### Token distribution
![endor-token-economy](https://user-images.githubusercontent.com/32852887/36959485-9a31360c-2042-11e8-9e7a-ca45576aa245.png)

- 40% Endor.coin long term reserves for development, ecosystem, and partnerships
- 20% Team
- **20% Token Private Sale \ Crowd-Sale**
- 20% Partners and Advisors

### Token allocation
> Funds will primarily be used for R&D and core technology development. Up to 30% will be used for the possibility of purchasing relevant proprietary technologies such as prediction engines and ETL connectors. Additionally, funds will be allocated for ecosystem expansion, business development and marketing, strategic partnerships, and supporting the academia.

## Q&A

![endorqa-01](https://user-images.githubusercontent.com/32852887/36486412-b9b6764a-171e-11e8-95c9-629a36a8a2d8.png)

> ### Are you using a reputable 3rd party for KYC verification? How safe is it to upload my Identity Document on your site?
- We are using a proprietary KYC system
- We are ISO 27001 compliant (enabling us to work with large retaliers and banks)
- We did an external APT with MedSec

> ### Can US investors participate in the sale? If yes did you secure Reg-D?
- This is still under legal evaluation. More details soon.

> ### Where is my money going and what will it be used for? Is my money going to be used to "cash out" others?
- All contributions will be used to develop the open protocol, create the eco system, and enable scale in democratizing predictive AI to Individuals and the long tail of businesses

> ### What specific rights come with my investment?
- EDR is a utility token, enabling to buy predictions

> ### Are there financial statements? If so, are they audited, and by whom?
- Yes. Endor has financial statements, audited by Ernst & Young

> ### How, when, and at what cost can I sell my investment? For example, do I have a right to give the token or coin back to the company or to receive a refund? Can I resell the coin or token, and if so, are there any limitations on my ability to resell?
- Liquidity for Endor's EDR tokens is fundamental to the success of the Endor ecosystem. Data providers who contribute high quality data stream, as well as "catalysts" who help form valuable types of predictions - will need to be able to understand the tokens they are receiving, and will naturally want to exchange the tokens they received in order to fund their operations. We are working towards establishing this liquidity for the EDR tokens

> ### If a digital wallet is involved, what happens if I lose the key? Will I still have access to my investment?
- Your wallet is your responsibility

> ### Has the offering been structured to comply with the securities laws and, if not, what implications will that have for the stability of the enterprise and the value of my contribution?
- EDR is a utility token, enabling to buy predictions

> ### What legal protections may or may not be available in the event of fraud, a hack, malware, or a downturn in business prospects? Who will be responsible for refunding my investment if something goes wrong?
- We are using a proprietary KYC system
- We are ISO 27001 compliant (enabling us to work with large retaliers and banks)
- We did an external APT with MedSec

#  ❗️ Crowdsale cancelled ❗️ 
![endor-cancelled](https://user-images.githubusercontent.com/32852887/37103930-b1e718d0-222b-11e8-91ab-384be1560f39.png)

# Flags
**Real Team:** ✅       
**GitHub:** ✅          
**Smart Contract:** - Not deployed yet      
**Working Product:** - ❌ Product not yet connected to blockchain.
**+2 yr Vesting for team:** - ❌ Token economy was published but Vesting schedule for Team and Advisors tokens was omitted | N/A in [smart contract](https://github.com/EndorCoin/endor-crowdsale)         
**Have a company:** ✅                  
**Transparent:** -          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by gaia** [comment]
Might be of help: https://www.youtube.com/watch?v=meuCcBkKLBU

**Comment by dshrier** [comment]
This post is wildly inaccurate.  I have Endor listed on my LinkedIn, as well as on my personal consulting website VisionaryFuture.com and in several other places.  Sorry, guys, but when you are doing “due diligence” and “fact checking”, please try to actually get the facts right.

**Comment by icochecker** [comment]
@dshrier Your profile was updated. 
Please point out what is **Widely inaccurate**.
Thanks

**Comment by dshrier** [comment]
*wildly not widely - apple autocorrect made its own contribution


______________________________
David L. Shrier
E: david@VisionaryFuture.com<mailto:david@VisionaryFuture.com>
M: +1 203 832 4215
www.VisionaryFuture.com<http://www.VisionaryFuture.com>

On Mar 5, 2018, at 1:16 AM, icochecker <notifications@github.com<mailto:notifications@github.com>> wrote:


@dshrier<https://github.com/dshrier> Your profile was updated.
Please point out what is Widely inaccurate.
Thanks

**Comment by dshrier** [comment]
Now it is more accurate.  Thanks.

**Comment by Empresaria** [comment]
Thank you for the update.  Please accept our apologies.  Simply making your
ICO better and set up for success.

With all due respect,

Cynthia Michele Lara

**Comment by sammy007** [comment]
Great review, it's a total scam and could be used as a blueprint for future generations.
