### ISSUE TITLE
OILSC - Due diligence

### ISSUE THREAD

**Issue by Empresaria** [ico-check/ico-check#67]
# [OILSC](http://oilsc.io/)

## Team
![oilsc-team-1](https://user-images.githubusercontent.com/32852887/36068127-c8c39702-0ecd-11e8-84bb-ce0bee10da2f.png)
![oilsc-team-2](https://user-images.githubusercontent.com/32852887/36068128-cb0b6e72-0ecd-11e8-8985-7613515f49b0.png)

- David Clark (Head of Development) - 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/david-clark-1483861a/)

## Team members with no mention of OILSC / Oil and Gas Supply Chain in their Linkedin profiles: 
- Jignesh Solanki (Concept Development) | [Linkedin profile](https://www.linkedin.com/in/solankijignesh/) **does not mention OILSC / Oil and Gas Supply Chain**
- Purvak Pathak (Blockchain Developer) | [Linkedin profile](https://www.linkedin.com/in/purvak-pathak-a29310126/) **does not mention OILSC / Oil and Gas Supply Chain**
- Parikshit Joshi (Blockchain Developer) | [Linkedin profile](https://www.linkedin.com/in/parikshitjoshi1/) **does not mention OILSC / Oil and Gas Supply Chain**
- Neil Watson (Risk Management) | [Linkedin profile](https://www.linkedin.com/in/neil-russell-slagger-watson-14096098/) **does not mention OILSC / Oil and Gas Supply Chain**
- Simon Yearron (Business Development) | [Linkedin profile](https://www.linkedin.com/in/syearron/) **does not mention OILSC / Oil and Gas Supply Chain**
- Nova Dien (Communications) - Sep 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/novadien/) **does not mention OILSC / Oil and Gas Supply Chain**

## Team members with no linkedin profile:
- Peter Nuttall (Oil & Gas Compliance)
- Ron Hessler (Oil & Gas)
- Bryan Thompson (Engineering)
- David Henderson (Head of Marketing)
- Richard Clark (Accountant)

### [Linkedin Company page](https://www.linkedin.com/company/oilsc/)
- [Company on Linkedin](https://www.linkedin.com/company/oilsc)
- [Website](http://oil-and-gas-supply-chain.com)
- [Website on web archive](https://web.archive.org/web/20180211030011/http://oil-and-gas-supply-chain.com/)

## Company
**Address**        
Suite 9, Ansuya Estate       
Revolution Avenue, Victoria        
Republic of Seychelles     

## Smart contract
- N/A
- [Wallet address on etherscan](https://etherscan.io/address/0x1F7DC776c46a709Cf698efe2F63219CC6c505334)

## Github
- N/A

## Product
- No working product

## Vesting
- N/A

### Token allocation
![oilsc-allocation](https://user-images.githubusercontent.com/32852887/36068132-e54457fe-0ecd-11e8-98b4-7a5215d4f052.png)

# Web archive
- [Website](https://web.archive.org/web/20180211005108/http://oilsc.io/)
- [Terms & Conditions](https://web.archive.org/web/20180211005555/http://oilsc.io/docs/OILSC%20Terms%20&%20Conditions.pdf)
- [White paper](https://web.archive.org/web/20180211005213/http://oilsc.io/docs/OILSC-whitepaper-2017-v18.pdf)

# Flags
**Real Team:** ❌  Possibility of identity theft.       
**GitHub:** ❌          
**Smart Contract:** ❌ Wallet address used       
**Working Product:** ❌        
**+2 yr Vesting for team:** ❌ No vesting schedule for Team         
**Have a company:** ❌ Cannot verify. No company info.                 
**Transparent:** ❌          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by Empresaria** [comment]
Does not require KYC . White pages claim non compliance

**Comment by MrNicodemuz** [comment]
The website seems to no longer function
<img width="854" alt="screen shot 2018-02-11 at 10 55 58 am" src="https://user-images.githubusercontent.com/1620454/36068858-0ea193e0-0f1a-11e8-8d73-33712c8c9a1b.png">
