### ISSUE TITLE
Sharder Protocol - Due diligence

### ISSUE THREAD

**Issue by coinbala** [ico-check/ico-check#68]
# [Sharder Protocol](https://sharder.org/) (SS)

![sharder-full-team](https://user-images.githubusercontent.com/32852887/36574381-dc1e9816-1845-11e8-9792-9fc6651c0192.png)

## Team members with no mention of Sharder Foundation in their Linkedin profiles:
- Youwei Shao - Wayne (COO) - Sep 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/wayneshao/)

## Team members with no Linkedin profiles:
- Yu Xiong - Ben (CEO/CTO)
- Bing Wang - Rick (CMO)

### R&D Team
- Yuetong Xiong - Vitty (Architect)
- Xiangyu Liu - Patrick (Lead Programmer)
- Qianglin Fan - Jonny (Lead Programmer)
- Xincheng Wang - Chandler (Product Manager)
- Tao Huang - Thomas (Programmer)
- Xuewen Lei - Vincent (Programmer)
- Quyan Zhang - Quincy (Programmer)
- Lian Yu - Lynn (Programmer)

### Marketing & operation team
- Xinrong Zuo - Kaka (Channel Director)
- Shengguo Gao - Greg (Marketing Director)
- Yue Qiu - Moon (Operating Specialist)
- Xia Zhang - Sam (Marketing Specialist)

## Advisor
- Cameron Nelson (Blockchain Expert) | [Linkedin profile](https://www.linkedin.com/in/cameronrnelson/)
- Yuen Wong (Marketing Lead) | [Linkedin profile](https://www.linkedin.com/in/yuen-wong-073bb541/)
- Erik Hohmann (Marketing) | [Linkedin profile](https://www.linkedin.com/in/erikhohmann/)
- Joe Chan (R&D (Network Layer)
- Pranav Burnwal | [Linkedin Profile](https://www.linkedin.com/in/pranavburnwal/)
- Chris Wong
- Cheng Chao 程超

![sharderteam](https://user-images.githubusercontent.com/35730440/36164761-48836666-10e5-11e8-9e52-ff165484677c.png)

### SHARDER FOUNDATION PTE. LTD.
**Registered Address:**    
152 BEACH ROAD           
14-02        
GATEWAY EAST    
SINGAPORE 189721                    

**UEN:** 201803857W         
**Company Type Description:** EXEMPT PRIVATE COMPANY LIMITED BY SHARES           
**Incorporation Date:** 31 January 2018                     
**Status:** LIVE COMPANY                

![sharder-foundation](https://user-images.githubusercontent.com/32852887/36571841-187de210-1839-11e8-9d80-d56bfa22044d.png)

- [Source: SG UEN Search](https://www.uen.gov.sg/)

## Smart contract
- [Contract on Github](https://github.com/Sharders/sharder-token/blob/master/SharderToken.sol)
- [Deployed contract - View on etherscan](https://etherscan.io/address/0xB15fE5a123e647ba594CEa7A1E648646f95EB4AA#code)

## Github
- [Sharders](https://github.com/Sharders)

### Commits
- [Commit activity](https://github.com/Sharders/sharder-chain/graphs/commit-activity)

## Product
- No working product

## Vesting
- Team Reserve tokens vest over 3 years. 
- Vesting for team tokens not coded in the smart contract

![sharder-vesting-1](https://user-images.githubusercontent.com/32852887/36575475-74842f9e-184b-11e8-9aab-d8fa7820ccfc.png)
![sharder-vesting-2](https://user-images.githubusercontent.com/32852887/36575477-7658e288-184b-11e8-895f-172e788b5da9.png)

## Additional info
- Smart Contract address: 0xB15fE5a123e647ba594CEa7A1E648646f95EB4AA
- Hard cap: 1500 ETHER
- Soft cap: 1000 ETHER
- Maximum contribution: 5.0 ETHER
- Minimum contribution: 0.1 ETHER
- Gas limit: 300,000

### White Paper not available in English
![sharder-whitepaper](https://user-images.githubusercontent.com/32852887/36625526-606ab178-1921-11e8-8632-a03407d9177c.png)

### Token distribution
![sharder-distribution](https://user-images.githubusercontent.com/32852887/36574729-598f75a8-1847-11e8-994e-7bc9ed0d8e12.png)

### Token allocation
![sharder-allocation](https://user-images.githubusercontent.com/32852887/36574723-56f2ec58-1847-11e8-899e-820c154cfc5c.png)

# Flags
**Real Team:** ✅    
**GitHub:** ✅          
**Smart Contract:** ✅   
**Working Product:** ❌
**+2 yr Vesting for team:** ❌ Vesting for team tokens not coded in the smart contract       
**Have a company:** ✅                  
**Transparent:** -          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by djskinner** [comment]
Struggling to find the github repo for Qianglin Fan's bitcoin light wallet. Has anyone located it?
