### ISSUE TITLE
Atonomi - Due diligence

### ISSUE THREAD

**Issue by yboz** [ico-check/ico-check#70]
# [Atonomi](https://atonomi.io) (ATMI)

## Core Team
- Vaughan Emery (Founder & CEO) - Jan 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/vaughanemery/) | [Twitter](https://twitter.com/vaughanemery)
- David Fragale (Co-Founder and VP of Product) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/davidfragale/)
- Michael Mackey (CTO and VP of Engineering) - No mention of Atonomi on LinkedIn | [Linkedin profile](https://www.linkedin.com/in/michael-mackey-9851b52/)
- Luis Paris (Chief Data Scientist) - No mention of Atonomi on LinkedIn  | [Linkedin profile](https://www.linkedin.com/in/luisparis/)
- Andrii Zamovsky (Strategic Development Partner) - No mention of Atonomi on LinkedIn  | [Linkedin profile](https://www.linkedin.com/in/nixoid/)

## Advisors
- Dr. John Clippinger | [Linkedin profile](https://www.linkedin.com/in/john-henry-clippinger-5ab1b/)
- Peter Kinnaird | [Linkedin profile](https://www.linkedin.com/in/peter-kinnaird-7657487/)
- David Kravitz | [Linkedin profile](https://www.linkedin.com/in/dkravitz/)
- Ulf Lindqvist | [Linkedin profile](https://www.linkedin.com/in/ulflindqvist/)
- Rob May | [Linkedin profile](https://www.linkedin.com/in/robmay/)
- David Jevans | [Linkedin profile](https://www.linkedin.com/in/davejevanssssss/)

# Funding Rounds
## Token Private Presale | SAFT | $16,664,962 | March 21, 2018
- [Launch Capital Partners](https://launchcapital.com) ?
- [M37 Ventures](https://www.m37ventures.com) ?

![atonomi-formd](https://user-images.githubusercontent.com/32852887/38224804-ee220a1e-36f1-11e8-9ed7-94e521adb5b0.png)

## [Source: Form D](https://www.sec.gov/Archives/edgar/data/1725812/000172581218000002/xslFormDX01/primary_doc.xml)

# Company

## ATONOMI, LLC
**File Number:** 6645194         
**Incorporation Date / Formation Date:** 04 December 2017       
**Entity Kind:** Corporation           
**Entity Type:** General          
**Residency:** Domestic         
**State:** Delaware

**Registered address**     
701 5TH Avenue    
Suite 550         
Seattle    
WA, 98104      
Phone: (206) 858-8702       
        
**Registered Agent Information:**        
CORPORATION SERVICE COMPANY         
251 LITTLE FALLS DRIVE           
WILMINGTON         
New Castle County       
Delaware 19808    
USA 

#### Directors
- **Vaughan Emery** | Founder & CEO of Atonomi | [Linkedin profile](https://www.linkedin.com/in/vaughanemery/) | [Twitter](https://twitter.com/vaughanemery)
- **Don De Loach** | President & COO at Centri Technology [Linkedin profile](https://www.linkedin.com/in/don-deloach-482724/) | [Twitter](https://twitter.com/deloach7kw)   
- **Woody Benson** | Venture Partner at [Launch Capital Partners](https://launchcapital.com) | [Linkedin profile](https://www.linkedin.com/in/woodybenson/) | [Twitter](https://twitter.com/wbenson)
- **Rob Strickland** | Founder & CEO of [M37 Ventures](https://www.m37ventures.com) | [Linkedin profile](https://www.linkedin.com/in/robert-strickland-3414a5/)
- **Wayne Wisehart** | Board of Directors at Centri Technology [Linkedin profile](https://www.linkedin.com/in/wayne-wisehart-1878361/)   

![atonomi-delaware](https://user-images.githubusercontent.com/32852887/38224764-c7686b84-36f1-11e8-822a-d0651d49a811.png)

## CENTRI TECHNOLOGY, INC (Parent company)
**File Number:** 4586591         
**Incorporation Date / Formation Date:** 08 November 2008        
**Entity Kind:** Corporation           
**Entity Type:** General          
**Residency:** Domestic         
**State:** Delaware     
        
**Registered Address:**        
CORPORATION SERVICE COMPANY         
251 LITTLE FALLS DRIVE           
WILMINGTON         
New Castle County       
Delaware 19808    
USA        

![centri-delaware](https://user-images.githubusercontent.com/32852887/38215182-392754ea-36c7-11e8-88f8-90746ba9ccac.png)

### [Source: Delaware entity search](https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx)

![centri-technology-company](https://user-images.githubusercontent.com/32852887/36437731-1fb03808-1668-11e8-944e-3660102e3245.png)

## Smart contract (To verify)
- [Deployed on etherscan](https://etherscan.io/address/0xe6a5c88f870a824dadbe3096de153bbf896fed57#code) | Total Supply: 2,000,000,000 ΑΤΜΙ | Token Decimals: 	18

## Github
N/A

![atonomi-github](https://user-images.githubusercontent.com/32852887/38227730-f769dc1a-36ff-11e8-8fe5-f06c7188d4a6.png)

## Product
![atonomi-product](https://user-images.githubusercontent.com/32852887/38227306-deec2f46-36fd-11e8-8b35-b8a47381fee9.png)

## Vesting
N/A

### [FORM D - Offering and Sales Amounts](https://www.sec.gov/Archives/edgar/data/1725812/000172581218000002/xslFormDX01/primary_doc.xml)
- Total Offering Amount: 35,000,000 USD
- Total Amount Sold: 16,664,962 USD
- Total Remaining to be Sold: 18,335,038 USD

![atonomi-sales](https://user-images.githubusercontent.com/32852887/38225546-b38c285e-36f5-11e8-9e48-cdbd60ed2a0a.png)

### Token distribution
N/A

### Token allocation
N/A

## Q&A
![atonomi-q a](https://user-images.githubusercontent.com/32852887/36437840-70a23310-1668-11e8-9ac1-4c05871f2c9d.png)

# Flags
**Real Team:** ✅       
**GitHub:** -          
**Smart Contract:** -      
**Working Product:** -        
**+2 yr Vesting for team:** -        
**Have a company:** ✅                 
**Transparent:** -          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by sky2018hao** [comment]
This project is about to start ICO. The administrator said that on the 15th, upload code. It feels a certain attraction. Does anyone care about this project?
