### ISSUE TITLE
Airex.io

### ISSUE THREAD

**Issue by Empresaria** [ico-check/ico-check#72]
# [Company name](company website)

## Team
*Here list team members with links to their LinkedIn accounts in here*

## Company
*Here put company information if company exsits. Also provide links (and possibly screenshots) where it can be verified that company exists*

## Smart contract
*Here put e.g. link to contract address on etherscan*

## Github
*Here put link to company's GitHub*

## Product
*Here put link to the product if exists and attach screenshots.*

## Vesting
*Here put information where vesting information was found and attach screenshots.*

## Additional info
*Here put additional comments about the company, with links when possible*

**Comment by icochecker** [comment]
![airex-parked](https://user-images.githubusercontent.com/32852887/36653127-7b8b3d22-1ab3-11e8-9a99-b0a3b54cbcf3.png)

```
Domain Name: AIREX.IO
Registry Domain ID: D503300000040473346-LRMS
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: www.namecheap.com
Updated Date: 2018-02-21T14:11:05Z
Creation Date: 2017-01-22T04:10:25Z
Registry Expiry Date: 2019-01-22T04:10:25Z
Registrar Registration Expiration Date:
Registrar: NameCheap, Inc
Registrar IANA ID: 1068
Registrar Abuse Contact Email: abuse@namecheap.com
Registrar Abuse Contact Phone: +1.6613102107
Reseller:
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: autoRenewPeriod https://icann.org/epp#autoRenewPeriod
Registrant Name: REACTIVATION PERIOD
Registrant Organization: NAMECHEAP
Name Server: DNS101.REGISTRAR-SERVERS.COM
Name Server: DNS102.REGISTRAR-SERVERS.COM
DNSSEC: unsigned
```
# @Empresaria More info needed. Domain name is parked at Namecheap
