### ISSUE TITLE
Telegram (TON) - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#73]
# [Telegram](https://telegram.org/) (TON)

## Founders
- Pavel Valerievich Durov | [Wikipedia](https://en.wikipedia.org/wiki/Pavel_Durov) | [Twitter](https://twitter.com/durov) | [Linkedin](https://www.linkedin.com/in/pavel-durov-80174366/)
- Dr. Nikolai Durov | [Wikipedia](https://en.wikipedia.org/wiki/Nikolai_Durov)

## Developers
- Aliaksei Levin | [Github](https://github.com/levlam): Telegram Database library
- Arseny Smirnov | [Github](https://github.com/arseny30): Telegram Database library | [Linkedin](https://www.linkedin.com/in/arseny-smirnov-36192529/)
- John Preston | [Github](https://github.com/john-preston): Telegram Desktop messaging app | [Telegram](https://telegram.me/preston)
- Dr Klo | [Github](https://github.com/DrKLO): Telegram messenger for Android

# Funding Rounds | $1.7B in 2 rounds

![telegram-formd](https://user-images.githubusercontent.com/32852887/38474436-1715d05c-3b9f-11e8-9958-3522f7b574ea.png)

### Federal Exemption and Exclusion Claimed:
Rule 506(c)

>Purchasers of securities offered pursuant to Rule 506 receive "restricted" securities, meaning that the securities cannot be sold for at least six months or a year without registering them.

### Type of Securities Offered:
Purchase Agreements for Cryptocurrency

### Use of Proceeds:
>The issuers intend to use the proceeds for the development of the TON Blockchain, the development and maintenance of Telegram Messenger and the other purposes described in the offering materials.

### Federal Exemption and Exclusion Claimed:
Rule 506(c)

>Purchasers of securities offered pursuant to Rule 506 receive "restricted" securities, meaning that the securities cannot be sold for at least six months or a year without registering them.

### Type of Securities Offered:
Purchase Agreements for Cryptocurrency

### Use of Proceeds:
>The issuers intend to use the proceeds for the development of the TON Blockchain, the development and maintenance of Telegram Messenger and the other purposes described in the offering materials.

### Telegram Group Inc. 
**Registered Address:**:      
Craigmuir Chambers        
Road Town, Tortola,           
VG1110 British Virgin Islands          

**Registered on:**        
**Registration No:**

### TON Issuer Inc 
**Registered Address:**:      
Craigmuir Chambers        
Road Town, Tortola,           
VG1110 British Virgin Islands          

**Registered on:**        
**Registration No:**

- [BVI Registry](http://www.bvifsc.vg/en-gb/divisions/registryofcorporateaffairs.aspx)

## Smart contract
N/A

## Github
- [Telegram Library](https://github.com/tdlib)
- [Telegram Desktop](https://github.com/telegramdesktop)

## Product
- [Telegram](https://telegram.org/)

## Vesting
N/A

# Additional info

### Token distribution
N/A

### Token allocation
N/A

# Flags
**Real Team:** ✅       
**GitHub:** ✅          
**Smart Contract:** -       
**Working Product:** -       
**+2 yr Vesting for team:** -        
**Have a company:** ✅                
**Transparent:** -          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by AriuzSS** [comment]
Just read today some negative news about this project. But i don't see why even Pavel Durov need to scam this project. It is working product. He probably have some ideas where they can improve telegram and make it profitable

**Comment by larin92** [comment]
I’ve heard it’s a scam. No mentions on official telegram website. And official twitter. And Durov’a twitter.

**Comment by icochecker** [comment]
@larin92 Not a scam. See SEC [Form D](https://www.sec.gov/Archives/edgar/data/1729650/000095017218000030/xslFormDX01/primary_doc.xml).

**Comment by BlockchainInvestment** [comment]
https://steemit.com/scam/@perry.jung/telegram-ico-you-re-invited-to-the-greatest-scam-ico-of-all-time

Telegram ICO is totally Scam. Look at this analysis. Welcome for reply.

**Comment by icochecker** [comment]
@BlockchainInvestment 

Not a scam see SEC Filling:

### [SEC Filling - 29 Mar 2018 - Reported Sold: USD 850M](https://www.sec.gov/Archives/edgar/data/1730853/000095017218000060/xslFormDX01/primary_doc.xml)

### [SEC Filling - 13 Feb 2018 - Reported Sold: USD 850M](https://www.sec.gov/Archives/edgar/data/1729650/000095017218000030/xslFormDX01/primary_doc.xml)

**Comment by BlockchainInvestment** [comment]
You can see at SEC filing, those filing has not been reviewed by SEC. It's voluntary filing. No body confirmed it yet. I am quite sure SEC filing is one part of scam scheme.

**Comment by BlockchainInvestment** [comment]
So simple, Pavel Durov denied, all rumored investors also denied. Only media cover this as historical ICO.
