### ISSUE TITLE
Nexo - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#77]
# [Nexo](https://nexo.io) (NEXO)

## Team
- **Kosta Kantchev** (Managing Partner) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/kostakantchev/)   
[Credissimo](https://www.crunchbase.com/organization/credissimo) | Co-Founder & Board Member - **Month?** 2007 - Present     
[Drooble](https://www.crunchbase.com/organization/drooble) | Founding Investor & Board Member - **Month?** 2015 - Present   
[YouLocal](https://www.crunchbase.com/organization/youlocal-inc) | Founding Investor & Board Member - **Month?** 2015 - Present    

- Georgi Shulev (Managing Partner) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/georgi-shulev-5701589/)

- Antoni Trenchev (Managing Partner) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/antoni-trenchev/)

- Vasil Petrov (CTO) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/v-v-petrov/)

- Kalin Metodiev (Corporate Finance) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/kalinmetodiev/)

- Kamen Trendafilov (Finance Director) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/kamen-trendafilov-mba-acca-cia-711b8666/)

- Bilyana Christova (Marketing) - Feb 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/bilyanastancheva/)

- Plamen Todorov (Blockchain Developer) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/ptfly/)

- Teodora Atanasova (Business Development) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/teodora-p-atanasova/)

- Joro Yordanov (Product Designer) - **Month?** 2017 - Present | [Linkedin profile](https://linkedin.com/in/yordanoff)

- Boris Delev (Technical Lead) - **Month?** - Present 2017 | [Linkedin profile](https://www.linkedin.com/in/borisdelev/)

- Ivan Kostov (Marketing) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/kostovster/)

- Yasen Damyanov (Business Development) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/yasendamyanov/)

- Mario Krastev (Senior Quality Assurance Specialist) - **Month?** 2017- Present | [Linkedin profile](https://www.linkedin.com/in/mario-krastev-203725aa/)

### Advisors
- Michael Arrington (Founder of TechCrunch/Arrington XRP Capital) | [Twitter](https://twitter.com/arrington/status/959116681158144001)
- Trevor Koverko (Founder of Polymath) | [Linkedin profile](https://www.linkedin.com/in/trevorkoverko/)
- Ugo Bechis (Leading Payments & Cards Expert) | [Linkedin profile](https://www.linkedin.com/in/ugo-bechis-0581348/)

## NEXO INC.
**File Number:** 6752499         
**Incorporation Date / Formation Date:** 12 February 2018        
**Entity Kind:** Corporation           
**Entity Type:** General          
**Residency:** Domestic         
**State:** Delaware     
        
**Registered Address:**        
HARVARD BUSINESS SERVICES, INC.         
16192 COASTAL HWY           
LEWES         
Sussex County       
Delaware 19958   
USA        

![nexo-delaware](https://user-images.githubusercontent.com/32852887/37548717-16d57c14-297a-11e8-9fdf-49710fcc2078.png)

## Nexo Capital Inc. (Token Sale)     
**Registered Address:**   
TWO ARTILLERY COURT, 2ND FLOOR       
161 SHEDDEN ROAD, PO BOX 799    
GRAND CAYMAN    
KY1-1103   
CAYMAN ISLANDS    

**Authorisation Code:**           
**Entity File Number:**  

#### Director
- Kosta Kantchev
- Antoni Trenchev
- Georgi Shulev

## Smart contract
- [Deployed - View on Etherscan](https://etherscan.io/address/0x16d66daef9a4bfe9f4138f46096803e394bb4f78#code)

## Github
- N/A

![nexo-github](https://user-images.githubusercontent.com/32852887/37541311-6ef72e08-295a-11e8-9b6b-7c9fa9a2d055.png)

## Product
- Overdraft online demo on the site

## Vesting
- Founder and Team tokens vest over 2 years with quartely vesting.
- Advisors, Legal and PR tokens vest over 1 year with quartely vesting.
- Community building and Airdrop campaign tokens vest over 18 month with quartely vesting.
- Overdfrat Funding reserves vest over 12 months with a 6 month cliff.

### Token distribution
![nexo-distribution](https://user-images.githubusercontent.com/32852887/37548702-048ed0be-297a-11e8-9325-e1de8d902d55.png)

### Token allocation
![nexo-allocation](https://user-images.githubusercontent.com/32852887/37548711-0e1a0d10-297a-11e8-86fa-faec275ed925.png)

## Q&A

> ### Has the code for your product been published, and has is it been audited by an independent cybersecurity company?
- Nexo is not an open-source project and its source code will not be published. We adhere to high security standards, as we have always done for the past 10 years. We have never had any system intrusions.

> ### Are you using a reputable 3rd party for KYC verification? How safe is it to upload my Identity Document on your site?
- Yes, we are using a reputable 3rd party for KYC verification. It will be 100% safe. https://onfido.com/, also used by Coinbase.

> ### Can us investors participate in the sale? If yes did you secure Reg-D?
- We accept US investors only if they are "accredited investors", according to Regulation D 506(c). We do not pretend to be a utility token that could potentially be sold to non accredited investors. We follow SEC's rules.

> ### Where is my money going and what will it be used for? Is my money going to be used to "cash out" others?
- Almost all funds from the Token Sale will be used to fund clients’ Overdraft requests. We are not one of those companies which pretend they will spend $20M on IT with a roadmap for launching in 2020. Our IT has been funded by our own funds and is almost ready at this point and we are launching a live Overdraft product in April. Nexo’s primary mission is to enable the community to enjoy its crypto-wealth without selling it. The team firmly believes that the vast majority of the raised funds need to find their way back to the people that need funding for meeting a short term obligation, seize an attractive investment opportunity or leverage their business operations. Almost all of the funds contributed at the Nexo Token Sale will therefore be allocated towards the funding of the World’s First Instant Overdrafts. There already is huge demand from potential overdraft clients, resulting in requests for over $350 million in overdraft requests as of February 15, 2018.       
Page 5: [https://nexo.io/assets/downloads/NEXO-Token-Terms.pdf](https://nexo.io/assets/downloads/NEXO-Token-Terms.pdf)

> ### What specific rights come with my investment?
- page 2: [https://nexo.io/assets/downloads/NEXO-Token-Terms.pdf](https://nexo.io/assets/downloads/NEXO-Token-Terms.pdf)

> ### Are there financial statements?  If so, are they audited, and by whom?
- There are no financial statements of Nexo but Credissimo does have plenty of audited by Deloitte. Nexo is powered by Credissimo - a Leading European FinTech Group for over 10 years.     
- You can see the audited financial statements at the bottom of the page here: [https://credissimo.com/](https://credissimo.com/)           
- While Nexo is a separate legal entity, the majority shareholders (which are the founders) of Credissimo are majority shareholders and founders of Nexo. They have funded Nexo so far and are contributing their 10 years of know-how in online lending automation.

> ### How, when, and at what cost can I sell my investment?  For example, do I have a right to give the token or coin back to the company or to receive a refund?  Can I resell the coin or token, and if so, are there any limitations on my ability to resell?
- We will not subject our early supporters to a formal lockup.

> ### If a digital wallet is involved, what happens if I lose the key?  Will I still have access to my investment?
- You will be able to recover access to your Nexo Wallet using standard recovery procedures using KYC, email and phone verification.

> ### Has the offering been structured to comply with the securities laws and, if not, what implications will that have for the stability of the enterprise and the value of my investment?
- We tend to comply with all securities law, as you can see we have filed with the SEC which is the toughest regulator in the world.

> ### What legal protections may or may not be available in the event of fraud, a hack, malware, or a downturn in business prospects?  Who will be responsible for refunding my investment if something goes wrong?
- On our end all has been taken care of in term of security. We have never had any system intrusions for over 10 years.

> ### If I do have legal rights, can I effectively enforce them and will there be adequate funds to compensate me if my rights are violated?
- Yes, you can, but please consult with your advisors.

# Flags
**Real Team:** ✅       
**GitHub:** ❌          
**Smart Contract:** ✅      
**Working Product:** ❌ Demo available on website      
**+2 yr Vesting for team:** ❌ Vesting schedule not codified.           
**Have a company:** ✅                 
**Transparent:** -          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by lucacotta** [comment]
security token
