### ISSUE TITLE
TxHash - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#81]
# [TxHash Network](https://txhash.network/)

[![telegram-chat](https://user-images.githubusercontent.com/32852887/38760208-611df88a-3f7a-11e8-83bc-ca7ba4076a10.png)](http://t.me/txhash_community)

### Other site
- [Txhash.com](https://txhash.com/team.html) | [Web Archive 22 May 2018](https://web.archive.org/web/20180228151051/https://txhash.com/)

![txhash-team](https://user-images.githubusercontent.com/32852887/40371870-bbdde9e2-5de3-11e8-84b8-695fbb152228.png)

# Team
- Diego Araos (Founder & CEO) - Aug 2017 - Present | [Linkedin profile](https://linkedin.com/in/diegoaraos) | [Github](https://github.com/daraosn) | [Twitter](https://twitter.com/daraosn) | [AngelList](https://angel.co/daraosn) | [Crunchbase](https://www.crunchbase.com/person/diego-araos) | [Youtube](https://www.youtube.com/user/daraosn) | [Personal website](http://diegoaraos.com)
- Ernane Luis - May 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/ernaneluis/) | [Github](https://github.com/ernaneluis) | [Twitter](https://twitter.com/ernaneluis)
- Norbert Ritter - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/norbert-ritter-06730a120/) | [Github](https://github.com/RitterNorbert)

## Advisors
- Najda Benes | [Linkedin profile](https://www.linkedin.com/in/nadjabenes/) | [Twitter](https://twitter.com/bennadja)
- Michaël Krens | [Linkedin profile](https://www.linkedin.com/in/mkrens/) | [Github](https://github.com/michi88) | [Twitter](https://twitter.com/mkrens)
- Manu Andorra | [Linkedin profile](https://www.linkedin.com/in/manu-andorra-09a32721/) | [AngelList](https://angel.co/manolooo) | [Twitter](https://twitter.com/manu_andorra)
- James Treacher | [Linkedin profile](https://uk.linkedin.com/in/jrtjrtjrt) | [AngelList](https://angel.co/jrosstreacher) | [Twitter](https://twitter.com/JRossTreacher)
- Sean Casey | [Linkedin profile](https://www.linkedin.com/in/sean-casey-3633a089/) | [Github](https://twitter.com/sean_j_casey) | [Twitter](https://twitter.com/seanjcasey)

# Company
### TXHASH NETWORK LTD    
**Company address:**          
Suite 23            
Portland House         
Glacis Road          
Gibraltar GX11 1AA       

**Company Number:** 117006         
**Incorporation Date:** 28 Feb 2018

![txhash-gibraltar](https://user-images.githubusercontent.com/32852887/36890044-c641dce4-1dfc-11e8-9d9b-b474ddd3f652.png)

- [Linkedin company page](https://www.linkedin.com/company/txhash/)

## Smart contract
N/A

## Github
- [TxHash](https://github.com/TxHash)

![txhash-github](https://user-images.githubusercontent.com/32852887/38528899-0620588a-3c62-11e8-9f01-61e848d2425b.png)

### Commits
N/A

# Product
- [Tracker App](https://app.txhash.com)

# Vesting
N/A

# Additional info
> ### TXHASH IS IN BETA, WE WILL HAVE A TOKEN SALE SOON, SUBSCRIBE HERE TO GET MORE INFO

![txhash-footer](https://user-images.githubusercontent.com/32852887/36889129-dc4f4b9c-1df8-11e8-92a4-9060f95c0f97.png)

- Source: Home Page Footer

## Token distribution
![txhash-distribution](https://user-images.githubusercontent.com/32852887/40372352-c47625be-5de4-11e8-9ae1-da89bff2e11c.png)

## Token allocation
![txhash-allocation](https://user-images.githubusercontent.com/32852887/40372339-bbce5b84-5de4-11e8-8d7e-83fd5772ed23.png)

# TxHash Flags
**Real Team:** -       
**GitHub:** -          
**Smart Contract:** -      
**Working Product (Mainnet):** -
**+2 yr Vesting for team:** -        
**Have a company:** -                 
**Transparent:** -          

# IcoCheck.io
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by fccbb** [comment]
github is empty
