### ISSUE TITLE
Irene Energy - Due diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#83]
# [Irene Energy](https://irene-crowdsale.com) (TLU)

## Team
- Guillaume Marchand (Founder, energy lead) - Apr 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/guillaume-marchand-bba96176) | [Twitter](https://twitter.com/tokenisteconomy)
- Julien Murésianu (A.I. Lead) - Apr 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/julienmu) | [Twitter](https://twitter.com/julien_mu)
- Louis Brun (Commercial lead) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/louisbrun/)
- Emilie Cohen-Boulakia (Impact lead) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/emilie-cohen-boulakia-bb60951/)
- Thomas de Roquancourt (ICO marketing lead) - Sep 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/thomas-de-roquancourt-59166b37)
- Charlotte Cohen (Visual identity lead) - Oct 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/charlottecohen/)
- Sebastien Lamy (Blockchain lead) - Apr 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/seblamydlc/)
- Malo Ferriol (Developer) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/malo-ferriol-28721914a/)

## No longer employed at Irene Energy
- Jefferson Le Quellec (Developer) | [Linkedin profile](https://www.linkedin.com/in/jle-quel/) **does not mention Irene Energy**
- Pierre Bouillon (Country lead: France) - Jan 2018 - Mar 2018 | [Linkedin profile](https://www.linkedin.com/in/pierre-bouillon-b284a912b/)

### Advisors
- Vidal Chriqui (Senior Advisor, blockchain) | [Linkedin profile](https://www.linkedin.com/in/vidal-chriqui/)
- Cedric Parent (Senior Advisor, commercial strategy) | [Linkedin profile](https://www.linkedin.com/in/cedric-parent/)
- Jean-Luc Dormoy (Senior Advisor, A.I. and smart meters) | [Linkedin profile](https://www.linkedin.com/in/jean-luc-dormoy-a6a55b)
- David Ly (Senior Advisor, digital marketing) | [Linkedin profile](https://www.linkedin.com/in/davidly22/)
- Stephane Redon (Senior Advisor, ICO investing) | [Linkedin profile](https://www.linkedin.com/in/stephane-redon-a55b71/)

 
# Company
## IRENERGY FRANCE   
121 RUE DE L'UNIVERSITÉ        
75007 PARIS
FRANCE                      
                                
**Incorporated on:** 24 Feb 2017      
**SHARE CAPITAL:** EUR 10        
**SIRET:** 827 900 846 00029      
**LEGAL FORM:** [S.A.R.L.](https://en.wikipedia.org/wiki/Soci%C3%A9t%C3%A9_%C3%A0_responsabilit%C3%A9_limit%C3%A9e)           
**ACTIVITIES (NAF CODE):** 4619B (Other commercial intermediaries in miscellaneous products)     

### Director: Guillaume Marchand     
**DOB:** 5 July 1981

## IRENE-GRID UK LTD
**Company number:** 10832539        
**Registered office address:**            
Flat 9        
61-62 Leinster Square        
London W2 4PS       
United Kingdom         
           
**Incorporated on:** 23 June 2017  
**Share Capital:** GBP 1       
**Nature of business (SIC)**        
35130 - Distribution of electricity

### Director: MARCHAND, Guillaume        
**Nationality:** French         
**Country of residence** United Kingdom          
**Occupation:** Director         

## I-RENEWABLE ENERGY LTD
**Company number:** 10832539        
**Registered office address:**            
Flat 9        
61-62 Leinster Square        
London W2 4PS       
United Kingdom         
           
**Incorporated on:** 24 January 2017  
**Share Capital:** GBP 10       
**Nature of business (SIC)**        
64999 - Financial intermediation not elsewhere classified     
74901 - Environmental consulting activities         

### Director: MARCHAND, Guillaume        
**Nationality:** French         
**Country of residence** United Kingdom          
**Occupation:** Director         

## Github
N/A

## Product
![irene-roadmap](https://user-images.githubusercontent.com/32852887/36911915-5b422fae-1e45-11e8-9464-cf43fd335e3a.png)

### Token distribution
![irene-distribution](https://user-images.githubusercontent.com/32852887/38154731-f82b01e4-3473-11e8-931b-3b114734891c.png)

### Token allocation

# Flags
**Real Team:** ✅       
**GitHub:** ❌          
**Smart Contract:** [Stellar Platform](https://www.stellar.org/)    
**Working Product:** ❌         
**+2 yr Vesting for team:** -        
**Have a company:** ✅                 
**Transparent:** -          

# IcoCheck
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by LouisBrunfromIreneEnergy** [comment]
Hi team - if you need more information please contact us at l.brun@irene.energy or g.marchand@irene.energy. Thank you.
