### ISSUE TITLE
Edenchain - Due diligence

### ISSUE THREAD

**Issue by coinbala** [ico-check/ico-check#87]
# [Edenchain](http://edenchain.io/) (EDN)

## Web archive
- [Mar 21 2018](https://web.archive.org/web/20180321142248/http://edenchain.io/)
- [25 Apr 2018](https://web.archive.org/web/20180425124645/edenchain.io)

![edenchain-team](https://user-images.githubusercontent.com/32852887/40454161-e8937dd0-5ee7-11e8-8801-57856c7cd660.png)

# Team
###  James Myong-ho Ahn (Founder & CEO) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/james-ahn-b5aa02140/) | [Korean Times Article](http://www.koreatimes.co.kr/www/tech/2018/02/133_244027.html) | [Youtube - ML training](https://www.youtube.com/watch?v=U7BxUfULLkw)
 - Deep Numbers | [DeepNumbers article in Korean](https://www.bloter.net/archives/261081) | CEO - **Month?** 2016 - **Month?** 2017
 - [MHR Inc]() | CEO - **Month?** 2008 - **Month?** 2016 

### Jenny Ryoo (Co-Founder & Blockchain Developer) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/jenny-ryoo-017626159/)
 - [MHR Inc]() | Senior Researcher - Jun 2006 - Feb 2017 
 
### HJ Moon (Chief of Business Development, Asia) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/hj-moon-96772b20/)
 - [Byzantine Partners](http://www.byzantinepartners.com/) | Head of Research - Mar 2018 - Present
 - [Barclays](http://www.home.barclays/) | Assistant Vice President - Jun 2012 - Apr 2016
 - [Goldman Sachs](http://www.goldmansachs.com/) | Business Analyst - Jun 2010 - May 2012
 - [Goldman Sachs](http://www.goldmansachs.com/) | Winter Intern - Jan 2010 - Apr 2010

### Richard Jahnke (Business Development Director (US & Europe) - Mar 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/richard-jahnke-554a7a3/)
 - [Plum Alley](http://www.plumalley.co/) | Venture Partner - Oct 2016 - Present
 - [Flatiron Investors](http://flatironinvestors.com/) | Venture Partner - Feb 2016 - Oct 2016

### Aaron Tay (Financial Advisor) - **Month?** 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/aarontwl/)
 - [Byzantine Partners](http://www.byzantinepartners.com/) | Co-founder - **Month?** 2018 - Present
 - [Tikehau Capital](http://www.tikehaucapital.com/) | Principal Investments - **Month?** 2014 - Present

### Kwangho Lee (Technical Advisor) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/kwangho-lee-30767a38/)
 - Seoul Blockchain Investment | VP - Feb 2018 - Present

### Kenneth Lee (Business Development Manager (Singapore) - May 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/kennethleebinglun/)
 - Ministry of Finance | Tax Policy Associate - Jan 2016 - May 2018

## Advisors
- Don Chang, Ph.D. (Advisor) - Oct 2017 - Present  | [Linkedin profile](https://www.linkedin.com/in/don-chang-334b822/)
- Joongheon Kim, Ph.D. (Advisor) - Mar 2018 - Present  | [Linkedin profile](https://www.linkedin.com/in/joongheon/)
- Sungho Kim, Ph.D. (Advisor) - 2018 - ?  | [Linkedin profile](https://www.linkedin.com/in/sungho-kim-12a54a73/)
- IckChan Joo, Ph.D. | [Linkedin profile](https://www.linkedin.com/in/%EC%9D%B5%EC%B0%AC-ick-chan-%EC%A3%BC-joo-51120669/) **does not mention Eden Partners**
- Alan Moonsoo Kim (Advisor) - **Month?** 2017 - Present  | [Linkedin profile](https://www.linkedin.com/in/alanmoonsookim/)
- James Jahnke (Advisor)  | [Linkedin profile](https://www.linkedin.com/in/jojahnke/) **does not mention Eden Partners**
- Mina Jeong (Advisor) - Feb 2018 - Present  | [Linkedin profile](https://www.linkedin.com/in/minajeongkoreaprspecialist/)
- Marat Zhanispayev (Advisor) **does not mention Eden Partners**  | [Linkedin profile](https://www.linkedin.com/in/marat-zhanispayev-61568024/)
- Yoonsang Cho, Lawyer (Advisor) | **No Linkedin profile**
- Hyung Guel Kim (Advisor) | [Google+](https://plus.google.com/103239620411528082979) | [Patents](https://patents.justia.com/inventor/hyung-guel-kim)
- Young Choe, Ph.D. (Advisor) - Mar 2018 - Present  | [Linkedin profile](https://www.linkedin.com/in/young-choe-8033684/)
- Mirza Uddin (Advisor) - **Month?** 2018  - Present  | [Linkedin profile](https://www.linkedin.com/in/themirzauddin/)
- Benn Godenzi (Advisor)  | [Linkedin profile](https://www.linkedin.com/in/outlastnutrition/) **does not mention Eden Partners**

## ‼️ Edenchain has more advisors than team members ‼️

# Company
### Eden Partners Inc.        
**Company number:** 1962929       
**Headquarters Address:**      
Intershore Chambers     
Road Town    
Tortola    
British Virgin Islands  

## Development company
**Company name:????**   
**Company number:????**      
**Office address:**      
The Arcade building        
11 Collyer Quay       
Singapore 049317     

## Office in Seoul
![edenchain-video-office](https://user-images.githubusercontent.com/32852887/40455572-e7af6dc4-5eed-11e8-91ba-ccf40aa46b3c.png)

- [Video of the office in Seoul](https://www.facebook.com/edenchainio/videos/1379729972132968/)

## Smart contract
- [Contract deployed on etherscan](https://etherscan.io/address/0xf907273152dd3317f6fd3a468091fa184667a132#code)

## Github
N/A

![edenchain-github](https://user-images.githubusercontent.com/32852887/37018665-7de329c8-2115-11e8-960d-1adecbf6da18.png)

### Edenchain Q&A page says that Github will be out at the end of April. As of 23 Mar 2018 Github is still not available. ‼️
![edenchain-q a-github](https://user-images.githubusercontent.com/32852887/40455303-a74eaf98-5eec-11e8-8f57-ac7d88f42ab0.png)

- [Edenchain Q&A Page](https://edenchain.io/a-sneak-preview-to-edenchain/) | [Webarchive](https://web.archive.org/web/20180523225640/https://edenchain.io/a-sneak-preview-to-edenchain/)

### No working product
![edenchain-product](https://user-images.githubusercontent.com/32852887/36948839-f4cf16b8-1fe0-11e8-9d47-67a81e52d63d.png)

### Update: Demo of MVP
- [Video demo of MVP 1](https://edenchain.io/demo-of-e-explorer-mvp-the-first-among-many-products/)
- [Video demo of MVP 2](https://edenchain.io/edenchains-second-mvp-e-edge/)

### Advisors & Team tokens vest over 1 year. Not codified.

![edenchain-vesting](https://user-images.githubusercontent.com/32852887/37801332-85a9b33e-2e26-11e8-89e1-7c61a6ae47d5.png)

## RoadMap

![edenchain-roadmap](https://user-images.githubusercontent.com/32852887/37052545-daf90f88-2179-11e8-9427-f03fc5d086f6.png)

## Token distribution

![Edenchain-total_allocation](https://user-images.githubusercontent.com/32852887/37033899-c341fb7a-2147-11e8-96da-2275ad1c9965.png)

## Token allocation

![Edenchain-use_of_proceeds](https://user-images.githubusercontent.com/32852887/37033924-dd26717e-2147-11e8-8f04-1858a6d49d5a.png)

# Edenchain Flags
**Real Team:** ✅       
**GitHub:** ❌         
**Smart Contract:** - Cannot audit smart contract. No Github.     
**Working Product (Mainnet):** ❌ Video demo of MVP     
**+2 yr Vesting for team:** ❌ Founder & Shareholders tokens vest over 1 year. Advisors & Team tokens vest over 1 year. Check for codified vesting.       
**Have a company:** ✅                 
**Transparent:** -          

# IcoCheck.io
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by frenchtoasters** [comment]
Looks like they have uploaded a video of the offices https://www.facebook.com/edenchainio/videos/1379729972132968/
