### ISSUE TITLE
Neurochain - Background check

### ISSUE THREAD

**Issue by fccbb** [ico-check/ico-check#88]
# [Neurochain](https://www.neurochaintech.io/) (NCC)

## Team
Frédéric Goujon CEO | [Linkedin](https://www.linkedin.com/in/fredericgoujon/)
Dr. Billal Chouli CTO  | [Linkedin](https://www.linkedin.com/in/dr-billal-chouli-97a64b1a/)

## Founding Team mentioning Neurochain

Bruno Delahaye CMO - Founding Partner | [Linkedin](https://www.linkedin.com/in/delahayebruno/)

## Founding Team Do not mention Neurochain

Dr. Patrice Guichard - Security Advisor | [Linkedin](https://www.linkedin.com/in/guichard/)
Hugues Bonhomme Administrative and Finance Director | [Linkedin](https://www.linkedin.com/in/hugues-bonhomme-66b6551/) Do not mention Neurochain.
Rogier Van Der Wal - Sales Advisor | [Linkedin](https://www.linkedin.com/in/rogiervanderwal/) Do not mention Neurochain

## Core team who mentions Neurochain

Dr. Maxim Irshkin Scientific Manager  | [Linkedin](https://www.linkedin.com/in/mirishkin/) mention Neurochain
Dr. Luca Comisso Research Fellow  | [Linkedin](https://www.linkedin.com/in/lucacomisso/) mention Neurochain

## Core Team who do not mention Neurochain

Maurizio Cacace Technical Specialist  | [Linkedin](https://www.linkedin.com/in/maurizio-cacace-11266071/)  Do not mention Neurochain in a personal portfolio but leave likes in his linkedin feed.
Dr. Talib Dbouk Technical Specialist  | [Linkedin](http://talibdbouk.com/) Do not mention Neurochain
Nicolas Van Eeckhout Agnostic & Holistic Innovation Catalyst  | [Linkedin](https://www.linkedin.com/in/vaneeckhout/) Do not mention Neurochain on Linkedin - [Facebook](https://www.facebook.com/nicolas.vaneeckhout)
Benjamin Mateo Blockchain Architect  | [Linkedin](https://www.linkedin.com/in/benjamin-mateo-596b74/) Do not mention Neurochain but has likes on his feed
Jérémy Seban Blockchain Project Architect  | [Linkedin](https://www.linkedin.com/in/j%C3%A9r%C3%A9my-seban-2177b893/) Do not mention Neurochain
Yves-Michel Leporcher Lead Dev  | [Linkedin](https://www.linkedin.com/in/yves-michel-leporcher-54143320/) Do not mention Neurochain in his portfolio but has Likes in his feed
Gilles Slomovits Data Scientist  | [Linkedin](https://www.linkedin.com/in/gilles-slomovits-3592336/) Do not mention Neurochain

## Advisors

Dr. John Rice Scientific advisor | [Linkedin](https://www.linkedin.com/in/john-rice-4071277/)
Pascal Lauffer Scientific Advisor | [Linkedin](https://www.linkedin.com/in/pascal-lauffer-7aa0463/)
Renaud Roquebert Legal and Strategy Advisor | [Linkedin](https://www.linkedin.com/in/renaudroquebert/)

## Company
Consilium
50 Boulevard VICTOR HUGO
92200 NEUILLY SUR SEINE
Created: 09/01/2018 

Code Siren : 837529148 
Forme juridique : Société par actions simplifiée 
Mandataires sociaux : Président : FG INNOVATIONS ; Directeur général : BC INNOVATIONS ; Commissaire aux comptes titulaire : KESSOUS Daniel ; Commissaire aux comptes suppléant : MEIER Cédrick 
Capital : 1 000,00 € 

Dénomination : FG INNOVATIONS 
Created: 12/07/2017 
Code Siren : 831323043 
Forme juridique : Société à responsabilité limitée 
Mandataires sociaux : Gérant : GOUJON Frédéric Arnaud Michel 
Capital : 500,00 € 
Adresse :
50 boulevard Victor Hugo
92200 Neuilly-sur-Seine 

Dénomination : BC INNOVATIONS 
Created: 12/07/2017 
Code Siren : 831319371 
Forme juridique : Société à responsabilité limitée 
Mandataires sociaux : Gérant : CHOULI Billal 
Capital : 500,00 € 
Adresse :
7 place Jean Zay
92300 Levallois-Perret 

## Smart contract
*Here put e.g. link to contract address on etherscan*

## Github
https://github.com/neurochain

## Product
No mvp yet
![screenshot](https://user-images.githubusercontent.com/30546271/37033732-3c56affc-2147-11e8-9914-5401f09b665a.png)

## Vesting
![screenshot 2](https://user-images.githubusercontent.com/30546271/37035812-011462d4-214e-11e8-89c4-0e62b5da6d80.png)

## Additional info
Token Metrics [Link pdf](https://www.neurochaintech.io/wp-content/uploads/2018/03/NeuroChainTokenMetricsOnePage.pdf)

![screenshot 1](https://user-images.githubusercontent.com/30546271/37034844-e92c8d70-214a-11e8-899d-72746f2ca56d.png)

**Comment by fccbb** [comment]
```bash
% myth --infura-mainnet -x -a 0x5d48F293BaED247A2D0189058bA37aa238bD4725
~
==== CALL with gas to dynamic address ====
Type: Warning
Contract: 0x5d48F293BaED247A2D0189058bA37aa238bD4725
Function name: _function_0xcae9ca51
PC address: 4113
The function _function_0xcae9ca51 contains a function call to an address provided as a function argument.The available gas is forwarded to the called contract. Make sure that the logic of the calling contract is not adversely affected if the called contract misbehaves (e.g. reentrancy).
--------------------

==== CALL with gas to dynamic address ====
Type: Warning
Contract: 0x5d48F293BaED247A2D0189058bA37aa238bD4725
Function name: _function_0xdc39d06d
PC address: 4313
The function _function_0xdc39d06d contains a function call to an address provided as a function argument.The available gas is forwarded to the called contract. Make sure that the logic of the calling contract is not adversely affected if the called contract misbehaves (e.g. reentrancy).
--------------------


myth --infura-mainnet -x -a 0x5d48F293BaED247A2D0189058bA37aa238bD4725  72.33s user 0.60s system 87% cpu 1:23.02 total
```

**Comment by fccbb** [comment]
Goujon, Chouli and Leporcher wrote a book about blockchain in french:
https://www.amazon.fr/Blockchains-th%C3%A9orie-pratique-lid%C3%A9e-limpl%C3%A9mentation/dp/2409005365/ref=cm_cr_arp_d_product_top?ie=UTF8

> Has the merit of being the first technical work in French on the place.
A lot of typographic shells.
The construction of some parts is a little disjointed.
Gives the effect of bringing together experts without any one being able to re-read the other, or bring the contradiction.
The layout is abominable.

>the worst book I bought in my life in terms of quality / price ratio. For €54, you are exposed to a work that is the aggregation of the work of 3 authors, many inconsistencies. I have been in the blockchain world for a while now and have been horrified by the horrible layout and errors in the description of this ecosystem. By realizing the intellectual effort to question every notion expressed, we can say that 60% of the content is ok, the rest is to put in the trash .... too expensive for this quality, an opportunistic work on a theme in vogue in order to sell ...

**Comment by angryolk** [comment]
ico completed, sold 267958000 tokens. base on their team feedback. unsold tokens will be:
 "The unsold tokens will be locked in the reserve and released progressively. Unlike some did wonder, those tokens and their sale will not be at the benefit of the team. The benefit will help finance NeuroChain if needed. “If” because we expect other financial resources from strategic partnerships and  consulting services. The benefit from the progessive release of the unsold tokens will also go to cofinance applications projects on the NeuroChain."
