### ISSUE TITLE
LCCX - Due diligence

### ISSUE THREAD

**Issue by kuangli2000** [ico-check/ico-check#93]
# [LCCX](https://lccx.io/) (LXT)

### On Linkedin, it says that Robert Benwell is Founder & CEO of LCCX since April 2017. In reality, LCCX LIMITED was incorporated on 29 January 2018.

![bernwell-1](https://user-images.githubusercontent.com/32852887/37560868-46b2f256-2a40-11e8-8943-3c408f262de0.png)
![bernwell-2](https://user-images.githubusercontent.com/32852887/37560869-48ff4aa0-2a40-11e8-931f-44a775591ef8.png)

### [Read Squirrel Ltd](https://beta.companieshouse.gov.uk/company/09996661) | Founder & CEO - Jan 2016 - Present
 
 ![read-squirrel](https://user-images.githubusercontent.com/32852887/37559880-f6f68e56-2a2d-11e8-9b56-23c95da28eba.png)
 ![read-squirrel-2](https://user-images.githubusercontent.com/32852887/37560401-83ac12f4-2a37-11e8-9509-45b370c666b5.png)

### [6ix Ltd](https://beta.companieshouse.gov.uk/company/09738877) | Director - Aug 2015 - Dec 2016

 ![6ix-limited](https://user-images.githubusercontent.com/32852887/37560023-c545c914-2a30-11e8-81a5-b83c6ae46443.png)
 ![6ix-limited-2](https://user-images.githubusercontent.com/32852887/37560402-85072fa8-2a37-11e8-9509-a795457f3757.png)
 
### Advisors
- Simon Cocking | [Linkedin profile](https://www.linkedin.com/in/simon-cocking-20540135/)
- Tobias Schulz | [Linkedin profile](https://www.linkedin.com/in/tobias-schulz-8b852011b/)
- Rumen Slavchov | [Linkedin profile](https://www.linkedin.com/in/%F0%9F%94%B9rumen-slavchov%F0%9F%94%B9-b058a554/)
- Viktor Petrov | [Linkedin profile](https://www.linkedin.com/in/viktorpetrov/)
- Giacomo Arcano | [Linkedin profile](https://www.linkedin.com/in/giacomo-arcaro-crypto/)

### [LCCX LIMITED](https://beta.companieshouse.gov.uk/company/11174171) 
**Company number:** 11174171              
**Registered office address:**            
Kemp House        
160 City Road         
London EC1V 2NX          
United Kingdom     
**Incorporated on:** 29 January 2018  
**Share Capital:** 100 GBP       
**Nature of business (SIC)**        
64999 - Financial intermediation not elsewhere classified

### Director: Robert Benwell        
**Nationality:** United Kingdom         
**Country of residence** United Kingdom          
**Role:** Director       
**Date of birth:** October 1984

## Github
- N/A

![lccx-github](https://user-images.githubusercontent.com/32852887/39552209-881266a4-4e68-11e8-827b-7fc1b21a51b2.png)

### No working product

![lccx-product](https://user-images.githubusercontent.com/32852887/37560924-af20d2d0-2a41-11e8-8120-303e5b6c56f2.png)

### Vesting schedule not codified. No smart contract used for the crowdsale

![lccx-vesting](https://user-images.githubusercontent.com/32852887/37560575-65c6ce1a-2a3b-11e8-86ca-28c43cff4939.png)

### Roadmap
![lcxx-roadmap](https://user-images.githubusercontent.com/32852887/37560564-3424a6f2-2a3b-11e8-8a66-9117124ad477.png)

### Token distribution
![lccx-token_allocation](https://user-images.githubusercontent.com/32852887/37560418-f886d2ee-2a37-11e8-87a1-9f87f7a405cd.png)

### Token allocation
![lccx-useof-funds](https://user-images.githubusercontent.com/32852887/37560419-fa34bbd8-2a37-11e8-95fb-6c8e8b6822a7.png)

# Flags
**Real Team:** -  
**GitHub:** ❌   
**Smart Contract:** ❌ No smart contract for the crowdsale.    
**Working Product:** ❌    
**+2 yr Vesting for team:** ❌ No vesting schedule for Advisors tokens. Vesting schedule not codified. No smart contract used for the crowdsale       
**Have a company:** ✅           
**Transparent:** ❌   

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by icochecker** [comment]
@kuangli2000 Issue updated

**Comment by kuangli2000** [comment]
Great job, thanks. Can't imagine this company cheating in the UK, where the laws are relatively strict.

**Comment by icochecker** [comment]
@kuangli2000 

The issue will stay open until the end of the Crowdsale. Additional checks are ongoing.

**Comment by testos77** [comment]
Office address ist just virtual -> https://yourvirtualofficelondon.co.uk/
Team:

Alice Copilet Lawyer -> https://www.upwork.com/o/profiles/users/_~01fe9b6908c03fcae0/ 
no real experience in the required field worked at jobs like:
"We need help dealing with the FCA supervision dept " !

Praveen Dagdi not really a crypto expert running a company in India Web/Mobile Design & Development
https://www.goodfirms.co/interviews/view/24/1054/techkopra
