### ISSUE TITLE
DFINITY - Due Diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#98]
# [DFINITY](https://dfinity.org/) (DFN)

# Team
## R&D
- Dominic Williams (Chief Scientist) - Jan 2015 - Present | [Linkedin profile](https://www.linkedin.com/in/thedwilliams) | [Twitter](http://twitter.com/dominic_w) | [Medium](https://medium.com/@dominic_w) | [Github](https://github.com/dominicwilliams) **profile shows that joined Dfinity org on 10 Sep 2016**
- Timo Hanke (Head of Engineering) - Jul 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/timo-hanke-62079775) | [Twitter](https://twitter.com/timothanke) | [Github](https://github.com/timohanke)
- Ben Lynn (Senior Staff Scientist & Engineer) - May 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/benjamin-lynn-51832a8) | [Blogger](http://benlynn.blogspot.com/) | [Github](https://github.com/blynn)
- Andreas Rossberg (Senior Staff Scientist & Engineer) | **No Linkedin profile** | [Blogger](https://people.mpi-sws.org/~rossberg/) | [Github](https://github.com/rossberg) **profile shows that joined Dfinity org on 2 Jan 2018**
- Mahnush Movahedi (Senior Researcher and Engineer) - Jun 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/mahnush-movahhedi-74355510) | [Github](https://github.com/mahnushm) | [Yale page](http://www.cs.yale.edu/homes/movahedi/)
- Martin Becze (Virtual Machine Research) | **No Linkedin profile** | [Github](https://github.com/wanderer) **profile shows that joined Dfinity org on 12 Sep 2017**
- Paul Liu (Staff Engineer) - Dec 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/paul-liu-86b880/) | [Blogger](http://thev.net/PaulLiu) | [Github](https://github.com/ninegua)
- Shigeo Mitsunari (Staff Cryptographer) | [Linkedin profile](https://jp.linkedin.com/in/mitsunari-shigeo) **Does not mention DFINITY** | [Github](https://github.com/herumi) **profile shows that joined Dfinity org on 23 Mar 2017** | [Personal Page](http://herumi.in.coocan.jp/)
- Enzo Haussecker (Senior Engineer) - **Month?** 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/ehaussecker)
- Norton Wang (Software Engineer) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/nortonwang)
- Ximin Luo (Software Engineer) | [Linkedin profile](https://www.linkedin.com/in/ximin-luo-64005664/) **Does not mention DFINITY** | [Debian](https://qa.debian.org/developer.php?login=infinity0) | [Github](https://github.com/infinity0) **profile shows that joined Dfinity org on 28 Feb 2018**
- Steve Omohundro (Senior Contributor - AI/Governance Research) | [Linkedin profile](https://linkedin.com/in/steve-omohundro-165399/) **Does not mention DFINITY** | [Twitter](https://twitter.com/steveom) | [Personal Website](https://steveomohundro.com/)
- Robert Lauko (Contributor - Research/Community) - Jul 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/robert-lauko-372030a1)

## Operations
- Tom Ding (CEO, String Labs & SV Liaison) | [Linkedin profile](https://www.linkedin.com/in/tomding) | [Twitter](https://twitter.com/tom_ding) | [Github](https://github.com/toysrtommy)
- Artia Moghbel (Head of Operations) - May 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/artiam) | [Twitter](https://twitter.com/artia)
- Blair Lewis (Head of Talent) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/blairplewis)
- Arthur Falls (Director of Communications) - Nov 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/arthur-falls-29274a55) | [Twitter](https://twitter.com/ArthurFalls)
- Michael Hunte (Director of Community Operations) - Jan 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/mhunte/) | [Twitter](https://twitter.com/TheMikeHunte) 
- Tomomi Menjo (Project Coordinator) - **Month?** 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/tomomi-menjo/) | [Twitter](https://twitter.com/tomomi_menjo)
- Cedric Waldburger (Swiss Operations Manager) - Sep 2016 - Present | [Linkedin profile](https://www.linkedin.com/in/cedricwaldburger/)

## [DEDIS](https://dedis.epfl.ch/) at [EPFL](https://www.epfl.ch/index.en.html)
- Prof. Bryan Ford (Team Lead) | [Linkedin profile](https://www.linkedin.com/in/baford) | [Twitter](https://twitter.com/brynosaurus) | [Github](https://github.com/dedis) | [Personal Blog](http://bford.github.io/)
- Philipp Jovanovic (Research Scientist) - May 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/philipp-jovanovic-01a4898b) | [Twitter](https://twitter.com/daeinar) | [Github](https://github.com/Daeinar)
- Eleftherios Kokoris-Kogias (Doctoral Researcher) - May 2017 - Present | [Linkedin profile](https://www.linkedin.com/in/eleftherios-kokoris-kogias-52836274) | [Twitter](https://twitter.com/LefKok) | [Github](https://github.com/dedis)
- Prof. Ewa Syta (Research Scientist) | [Personal page](http://ewa.syta.us/) | [Twitter](https://twitter.com/ewasyta)
- Stevens Le Blond (Research Scientist) | [Github](https://github.com/dedis)
- Linus Gasser (Software Engineer) | [Linkedin profile](https://www.linkedin.com/in/linus-gasser-8914209a) | [Twitter](https://twitter.com/ineiti) | [Github](https://www.linkedin.com/in/linus-gasser-8914209a)
- Cristina Basescu (Doctoral Researcher) | [Linkedin profile](https://www.linkedin.com/in/cristinabasescu) | [Github](https://github.com/dedis)
- Nicolas Gailly (Security Software Engineer) | [Linkedin profile](https://www.linkedin.com/in/nicolas-gailly-3353688a) | [Github](https://github.com/nikkolasg)

### No advisors

![dfinity-advisor-1](https://user-images.githubusercontent.com/32852887/37742319-74623fcc-2d65-11e8-9d52-1b20ce554b74.png)
![dfinity-advisors](https://user-images.githubusercontent.com/32852887/37729191-9b9b84a0-2d3c-11e8-9012-53409b8dcdb1.png)

# Company
## DFINITY Stiftung (Foundation)       
Gotthardstrasse 20        
6300 Zug       
Switzerland     
**Registered on:** 09 Nov 2016     
**UID:** CHE-189.770.146   
**Commercial register number:** CH-170.7.000.789-7  

**Purpose:** Förderung von neuen Technologieentwicklungen und Applikationen, insbesondere die Förderung und Erhaltung von neuen offenen dezentralisierten Softwarearchitekturen. Im Vordergrund - aber nicht ausschliesslich - steht dabei die Förderung  der Entwicklung des so genannten DFINITY Protokolls und die entsprechende Technologie sowie die Förderung und Unterstützung von Applikationen unter Anwendung des DFINITY Protokolls; vollständige Zweckumschreibung gemäss Statuten        

**Purpose (translated to EN):** Promote new technology developments and applications, in particular the promotion and maintenance of new open decentralized software architectures. In the foreground - but not exclusively - is the promotion of the development of the so-called DFINITY protocol and the corresponding technology as well as the promotion and support of applications using the DFINITY protocol; complete purpose description according to the Articles of Association.

### Management
- **Dominic Williams** | Foundation board-President
- **Gian Alexandre Bochsler** | Foundation board-Member
- [MUTARA Audit AG](http://www.mutara.ch/en/expertise.html) (CHE-113.025.688), in Baar | Audit

#### Source
- [Kanton Zug commercial register](https://zg.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-189.770.146)

## DFINITY ECOSYSTEM FUND LP

![dfinity-reuters](https://user-images.githubusercontent.com/32852887/37735940-cca7af2a-2d4f-11e8-8364-4881ecca950e.png)

### [Source: Reuters](https://www.reuters.com/article/us-blockchain-investment-andreessen/blockchain-project-raises-61-million-from-andreessen-horowitz-u-s-hedge-fund-idUSKBN1FR1IX)

**File Number:** 6711235         
**Incorporation Date / Formation Date:** 16 January 2018        
**Entity Kind:** Corporation           
**Entity Type:** General          
**Residency:** Domestic         
**State:** Delaware
**Industry:** Pooled Investment Fund

**Address:**     
548 Market Street Suite 64375     
San Francisco, CA, 94104    
Phone: 415-613-5108       
        
**Registered Address:**        
VCORP SERVICES, LLC         
1013 CENTRE ROAD SUITE 403-B           
WILMINGTON         
New Castle County       
Delaware 19805    
USA

### Directors and Executives
- **Polychain Venture Partners LLC | General Partner**     
548 Market Street        
Suite 64375        
San Francisco     
CALIFORNIA 94104      
USA 

- **Olaf Carlson-Wee | Managing Member of the General Partner**   
548 Market Street        
Suite 64375        
San Francisco     
CALIFORNIA 94104      
USA       

![dfinity-ecosystem-fund](https://user-images.githubusercontent.com/32852887/37732992-f08929ea-2d46-11e8-99a6-d65be887e97a.png)

#### Exemptions
- Rule 506(b)
- Investment Company Act Section 3(c)
- Section 3(c)(7)

## Github
- [Dfinity](https://github.com/dfinity)

### Asked by user on 26 Feb 2018
![dfinity-testnet](https://user-images.githubusercontent.com/32852887/37742625-b4d695d4-2d66-11e8-9f8c-d781020b7f5c.png)

## Vesting
- N/A

![dfinity-vc-vesting](https://user-images.githubusercontent.com/32852887/37739222-c5da9932-2d59-11e8-8f42-a13f0ab70cb5.png)

### 5 April 2008
- Crowdsale cancelled.
- DFINITY will be airdropping up to 25M Swiss Francs worth of DFN to community members. KYC and AML will be required. US individuals will not be able to participate
- DFINITY will be raising approximately 90M Swiss Francs in a private presale.

### 29 March 2018
![dfinity-token-q4](https://user-images.githubusercontent.com/32852887/38098660-f43102a6-3378-11e8-8cc8-53adc849f1be.png)

### Token distribution
- N/A

### Token allocation
- N/A

# Flags
**Real Team:** ✅  
**GitHub:** ✅   
**Smart Contract:** - Not yet available    
**Working Product:** ❌ Demo available    
**+2 yr Vesting for team:** -      
**Have a company:** ✅           
**Transparent:** -   

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by gaia** [comment]
Red Flag https://twitter.com/ICODrops/status/976104225796214786

**Comment by jens-christian** [comment]
With zero prior knowledge of DFINITY I spent this evening reading the “DFINITY White Paper Consensus system” which I consider the core technical paper. I spent 4 hours and here are my immediate thoughts.

Overall this feels like a work of quality. It is evident that a lot of effort and talent has gone into producing this white paper. I can probably answer many of my open question myself with further study, I get no sense that they are handweaving anywhere.

**Some notable plusses**

DFINITY explicitly addresses CAP and chooses consistency over availability. This should be obligatory for any financial transactional system but is still “forgotten” even in some top 10 coins. In case of network failure, a user will accept a payment being declined but he will not accept being fooled by a double-spend. Sounds pretty basic to me.

The paper describes an underlying random beacon powering the consensus and smart contract layer. The beacon is based on a verifiable random function (VRF). I have studied VRFs and while DFINITY is not the first coin to propose the use of VRFs it still seems a great fit crypto in general for their algorithm in particular.

DFINITY does not rely on clients having synchronized clocks. While I never got around to understanding why, it is still a step ahead of some of the competition.

**A few minusses/open questions**

The use of committees, VRF and “rounds” for consensus makes me wonder if they are at odds with the Algorand patents. I got some Algorand vibe reading it. I am no lawyer so no clue, but could it be an issue?

I didn’t find any description of the incentive of running a client?

Protection against sybil attacks is left as an exercise to the reader? They seem to require stake deposits...

“Scales to millions of clients” and “transaction time in seconds” claims but no empirical evidence in terms of a working prototype or a network simulation analysis in the paper?

There are a ton of attack vectors I didn’t find addressed. Maybe I need to study more, but I kept thinking “How many bad actors is required to deny service of the system? Can an adversary prevent clients from registering their public keys? Can he ddos committee members once they make themselves known?...”

Anyways, good luck to them. Technical foundation seems legit to me. Level of ambition of the overall project seems quite high. Nothing wrong with that, though.

All in my humble opinion. Do you own research!

**Comment by kuangli2000** [comment]
I do not know if I understand correctly? There is no mature product in this crazy company, and the value of ICO will exceed 2 billion U.S. dollars.

https://medium.com/dfinity/announcing-the-dfinity-presale-fundraise-and-public-airdrop-cdea19892ef6


To preserve the foundation’s endowment of tokens for later use, and in pursuit of wider distribution after network launch, DFINITY will restrict the private Presale fundraise to disbursing no more than 4.75% of the genesis tokens for a maximum raise of 90M Swiss Francs. Consequently by network launch, hardly more than 10% of the network will have been distributed to accredited investors who participated in private rounds
