### ISSUE TITLE
PCHAIN - Due Diligence

### ISSUE THREAD

**Issue by icochecker** [ico-check/ico-check#99]
# [PChain](https://pchain.org/) (PCH)

## Team
- Feng (Jeff) Cao (Vision & Science) - Feb 2018 - Present | [Linkedin profile](https://www.linkedin.com/in/feng-cao-79364814/)
- Steven Lv (Architecture) | [Linkedin profile](https://www.linkedin.com/in/lv-steven-093a8240/)
- Frank Ma (Blockchain Storage and Optimization) | [Linkedin profile](https://www.linkedin.com/in/zhanfeng-ma-80964728/)
- Kevin Kai Zheng (郑 凯) (In-memory Data Management) | [Github](https://github.com/kevin-pchain) | [Personal page](http://zheng-kai.com/)
- Zhihong Chong (崇志宏) (Knowledge Graph) | [Personal page](http://cse.seu.edu.cn/people/zhchong/index.htm)
- Zhenjie Zhang (Query Speedup and Indexing) | [Bio](https://sites.google.com/site/zhangzhenjie/)

### Advisors
- Ken Huang
- Danial Wang
- Howard Yuan

## PCHAIN FOUNDATION LTD.
**Registered Address:**    
9 TEMASEK BOULEVARD          
04-02       
SUNTEC TOWER TWO       
SINGAPORE 038989                        

**UEN:** 201806291E       
**Company Type Description:** EXEMPT PRIVATE COMPANY LIMITED BY SHARES           
**Incorporation Date:** 22 February 2018    
**UEN Status:** REGISTERED                    
**Status:** LIVE COMPANY        

![pchain-company](https://user-images.githubusercontent.com/32852887/37793994-72ade342-2e10-11e8-84d9-788c14044d97.png)

## Smart contract
- Token is an ERC20

![pchain-erc20](https://user-images.githubusercontent.com/32852887/38647007-79d0234e-3dea-11e8-8b1e-305829ceb3eb.png)

## Github
- [pchain-org](https://github.com/pchain-org)
- [Stone2water - Ethdata](https://github.com/stone2water/ethdata)

### Commits
- [Pchain-pub commits](https://github.com/pchain-org/pchain-pub/graphs/commit-activity)

### No working product
![pchain-product](https://user-images.githubusercontent.com/32852887/37878495-7b934932-306a-11e8-94aa-cf2fbfe5b4b9.png)

### Team tokens vest over 2 years.

![pchain-vesting](https://user-images.githubusercontent.com/32852887/38646896-1a4da32e-3dea-11e8-9631-769dc789d02d.png)

### Token allocation
• 65% - PCHAIN system research and development, including wages, soft- ware and hardware procurement, etc.
• 20% - Carrying out the marketing campaign, including wages, promotion expenses, etc.
• 10% - Carrying out operations, including holding all kinds of activities, etc.
• 5% - Conducting legal compliance, including the payment of counsel fees, etc.

# Flags
**Real Team:** -       
**GitHub:** ✅          
**Smart Contract:** -      
**Working Product:** ❌        
**+2 yr Vesting for team:** - To check in the deployed smart contract.       
**Have a company:** -                 
**Transparent:** -          

# IcoCheck
- Added to [icocheck.io](https://icocheck.io/)
- Discuss this project and others on **ICO Check** Telegram Group chat [https://t.me/checkico](https://t.me/checkico)

**Comment by fccbb** [comment]
A link to Andre Conj's review on the cpchain's code : [https://cryptobriefing.com/cpchain-code-review-iot-sidechains/](https://cryptobriefing.com/cpchain-code-review-iot-sidechains/) :+1:

**Comment by zebracrossingblog** [comment]
https://steemit.com/pchain/@bitcoinstartrek/pchain-mvp

**Comment by zebracrossingblog** [comment]
![image](https://user-images.githubusercontent.com/38685179/40869981-fcf273f4-6657-11e8-92ae-efa805fd52a3.png)
